//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTBANK
    {
        public int COMPANYID { get; set; }
        public int ACTID { get; set; }
        public int ITEMNO { get; set; }
        public Nullable<int> ACTBANKID { get; set; }
        public string ACTBANKNAME { get; set; }
        public string BANKBILLNO { get; set; }
        public Nullable<int> BANKID { get; set; }
        public string IBANNO { get; set; }
        public string BRANCHNO { get; set; }
        public string BRANCHDESC { get; set; }
        public string BANKCODE { get; set; }
        public string CURRCODE { get; set; }
        public Nullable<int> NOTESID { get; set; }
        public Nullable<bool> DEFAULTBANK { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
