//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTRECEIPTDCITEMNEW
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public double RECEIPTID { get; set; }
        public short ITEMNO { get; set; }
        public Nullable<short> ITEMTYPE { get; set; }
        public Nullable<int> ACTID { get; set; }
        public Nullable<double> DEBIT { get; set; }
        public Nullable<double> CREDIT { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> ACCID { get; set; }
        public string CURRCODE { get; set; }
        public Nullable<System.DateTime> CURRDATE { get; set; }
        public Nullable<double> CURREXC { get; set; }
        public string CURRCODETRANS { get; set; }
        public Nullable<System.DateTime> CURRDATETRANS { get; set; }
        public Nullable<double> CURREXCTRANS { get; set; }
        public Nullable<double> CURRDEBIT { get; set; }
        public Nullable<double> CURRCREDIT { get; set; }
        public Nullable<double> CURRDEBITTRANS { get; set; }
        public Nullable<double> CURRCREDITTRANS { get; set; }
        public string GROUPCODE { get; set; }
        public string SPECCODE1 { get; set; }
        public string SPECCODE2 { get; set; }
        public Nullable<System.DateTime> DUEDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
    }
}
