//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPRODUCT
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int BPRODUCTID { get; set; }
        public Nullable<int> BPROORDERID { get; set; }
        public Nullable<System.DateTime> TRANSDATE { get; set; }
        public Nullable<short> EMPLOYEEID { get; set; }
        public Nullable<double> QUANTITYMT { get; set; }
        public Nullable<double> QUANTITYKG { get; set; }
        public Nullable<bool> STATUS { get; set; }
    }
}
