//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUDGETITEM
    {
        public int COMPANYID { get; set; }
        public int BUDGETID { get; set; }
        public Nullable<int> GLBPERIODID { get; set; }
        public short ITEMNO { get; set; }
        public Nullable<int> STOCKID { get; set; }
        public Nullable<int> EXPREVID { get; set; }
        public Nullable<int> ACCID { get; set; }
        public Nullable<int> ACCCOSTCENTERID { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public Nullable<double> PRICE { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<double> TOTALACTUAL { get; set; }
        public Nullable<double> QUANTITYACTUAL { get; set; }
        public string CURRCODE { get; set; }
        public Nullable<double> CURRTOTAL { get; set; }
        public Nullable<double> CURRTOTALACTUAL { get; set; }
        public string SPECCODE1 { get; set; }
        public string SPECCODE2 { get; set; }
        public string GROUPCODE { get; set; }
        public Nullable<System.DateTime> BEGINDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
