//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCASCYCLE
    {
        public short COMPANYID { get; set; }
        public Nullable<int> PWORKCENTERID { get; set; }
        public short PWORKSTATIONID { get; set; }
        public int STOCKID { get; set; }
        public Nullable<int> PPROCESSID { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<System.DateTime> TRANSDATE { get; set; }
        public Nullable<int> PSHIFTTIMEID { get; set; }
        public Nullable<int> SHIFT { get; set; }
        public Nullable<int> TEAMID { get; set; }
        public Nullable<int> PIDSTOCKCOUNT { get; set; }
        public Nullable<int> ISROBOT { get; set; }
        public Nullable<int> CYCLEUNIT { get; set; }
        public Nullable<double> CYCLEPERIOD { get; set; }
        public Nullable<double> SPEED { get; set; }
        public Nullable<int> CYCLECOUNT { get; set; }
        public Nullable<double> QTY { get; set; }
    }
}
