//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCASLOTS
    {
        public int COMPANYID { get; set; }
        public int PWORKSTATIONID { get; set; }
        public int STOCKID { get; set; }
        public int GRADEID { get; set; }
        public int STOCKLOTSID { get; set; }
        public string LOTNO { get; set; }
        public string PARENTLOTNO { get; set; }
        public Nullable<int> DEPOTID { get; set; }
        public Nullable<byte> SECTION { get; set; }
        public Nullable<double> QENTRY { get; set; }
        public Nullable<double> QEXIT { get; set; }
        public Nullable<double> QREZERVE { get; set; }
        public Nullable<double> QREZERVE2 { get; set; }
        public Nullable<double> QREZERVE3 { get; set; }
        public Nullable<double> QREZERVE4 { get; set; }
        public Nullable<int> SOURCEITEMREF { get; set; }
        public Nullable<int> SOURCEINVENNO { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> ITEMNO { get; set; }
        public Nullable<bool> LOTCHANGE { get; set; }
    }
}
