//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCASMSG
    {
        public int COMPANYID { get; set; }
        public int DCASMSGID { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<int> MESSAGETYPE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> PWORKSTATIONID { get; set; }
        public string OUTMASK { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
