//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERY
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int RECEIPTID { get; set; }
        public Nullable<short> TRANSTYPE { get; set; }
        public string RECEIPTNO { get; set; }
        public Nullable<System.DateTime> TRANSDATE { get; set; }
        public string GROUPCODE { get; set; }
        public string SPECCODE1 { get; set; }
        public string SPECCODE2 { get; set; }
        public string TRANSCODE { get; set; }
        public Nullable<int> EMPLOYEEID { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<int> NOTEID { get; set; }
        public Nullable<System.DateTime> CANCELDATE { get; set; }
        public string DESCRIPTION { get; set; }
        public string DOCUMENTNO { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string CURRCODE { get; set; }
        public Nullable<System.DateTime> CURRDATE { get; set; }
        public Nullable<double> CURREXC { get; set; }
        public Nullable<double> CURRTOTAL { get; set; }
        public string CURRCODETRANS { get; set; }
        public Nullable<System.DateTime> CURRDATETRANS { get; set; }
        public Nullable<double> CURREXCTRANS { get; set; }
        public Nullable<decimal> CURRTOTALTRANS { get; set; }
        public string TAXOFFICE { get; set; }
        public string TAXNO { get; set; }
        public string TAXCITY { get; set; }
        public Nullable<System.DateTime> DUEDATE { get; set; }
        public Nullable<short> DUEDAY { get; set; }
        public Nullable<System.DateTime> DUEOPSDATE { get; set; }
        public Nullable<short> CATEGORYID { get; set; }
        public Nullable<short> PAYMENTTYPE { get; set; }
        public Nullable<bool> EXPORTENTRY { get; set; }
        public Nullable<double> DISCOUNTTOTAL1 { get; set; }
        public Nullable<decimal> DISCOUNT1 { get; set; }
        public Nullable<double> DISCOUNTTOTAL2 { get; set; }
        public Nullable<decimal> DISCOUNT2 { get; set; }
        public Nullable<decimal> PRODUCTSUM { get; set; }
        public Nullable<decimal> DISCOUNTSUM { get; set; }
        public Nullable<decimal> PRODUCTSUMOUTVAT { get; set; }
        public Nullable<decimal> DISCOUNTSUMOUTVAT { get; set; }
        public Nullable<decimal> BREAKTOTALOUTVAT { get; set; }
        public Nullable<decimal> VATSUM { get; set; }
        public Nullable<decimal> TAXPRIVATESUM { get; set; }
        public Nullable<decimal> TAKEUPTAXSUM { get; set; }
        public Nullable<bool> ACCCHECK { get; set; }
        public Nullable<double> COSTPRICE { get; set; }
        public Nullable<System.DateTime> DUEDATEVAT { get; set; }
        public Nullable<decimal> ROTATETOTAL { get; set; }
        public Nullable<decimal> TAKEUPMULT { get; set; }
        public Nullable<decimal> TAKEUPDIV { get; set; }
        public Nullable<decimal> STOPAJRATE { get; set; }
        public Nullable<decimal> STOPAJ { get; set; }
        public Nullable<int> CASHID { get; set; }
        public Nullable<int> DEPOTID { get; set; }
        public Nullable<int> ACTID { get; set; }
        public Nullable<int> BANKID { get; set; }
        public Nullable<decimal> BANKTOTAL { get; set; }
        public string NAME1 { get; set; }
        public string NAME2 { get; set; }
        public Nullable<int> ADDRESSID { get; set; }
        public Nullable<System.DateTime> DELIVERYDATE { get; set; }
        public Nullable<int> DELIVERYACTID { get; set; }
        public string DELIVERYNAME { get; set; }
        public string DELIVERYNAME2 { get; set; }
        public Nullable<int> DELIVERYADDRESSID { get; set; }
        public string DESCRIPTION1 { get; set; }
        public string DESCRIPTION2 { get; set; }
        public Nullable<int> PROJECTID { get; set; }
        public Nullable<int> ACCCOSTCENTERID { get; set; }
        public Nullable<bool> CURRTRANSTYPE { get; set; }
        public Nullable<int> RECEIPTTYPE { get; set; }
        public Nullable<int> SID { get; set; }
        public Nullable<int> STOCKPACKAGEID { get; set; }
        public Nullable<short> PARTCOUNT { get; set; }
        public Nullable<short> GLBPAYMENTID { get; set; }
        public Nullable<double> SHIPPING { get; set; }
        public Nullable<int> ACCRECEIPTID { get; set; }
        public Nullable<bool> MANUELVAT { get; set; }
        public Nullable<int> STOCKPRICETYPEID { get; set; }
        public Nullable<int> BUDGETID { get; set; }
        public Nullable<double> BREAKTOTAL { get; set; }
        public Nullable<bool> SENDDOC { get; set; }
        public Nullable<int> CRMCONTACTSID { get; set; }
        public Nullable<decimal> CURRDISCOUNTTOTAL1 { get; set; }
        public Nullable<double> BONUS { get; set; }
        public Nullable<int> RECEIPTIDRELATION { get; set; }
        public string DOCUMENTTYPE { get; set; }
        public Nullable<System.DateTime> DUEAVG { get; set; }
        public Nullable<decimal> BABSTOTAL { get; set; }
        public string IHRACATREASON { get; set; }
        public string EDESGUID { get; set; }
        public string EEDESGUID { get; set; }
        public string EDESSTATUS { get; set; }
        public Nullable<int> EDESTYPE { get; set; }
        public string EDESSTATUSDESC { get; set; }
        public string YKDEVICENO { get; set; }
        public string YKZNO { get; set; }
        public string YKSICNO { get; set; }
        public string YKFISNO { get; set; }
        public string CHECKMD5SUM { get; set; }
        public Nullable<int> CARRIERID { get; set; }
        public string DRIVERIDS { get; set; }
        public string VECHICLEIDS { get; set; }
        public string DORSEIDS { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
