//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPORTDATAITEM
    {
        public int COMPANYID { get; set; }
        public int EXPORTID { get; set; }
        public int ITEMNO { get; set; }
        public Nullable<int> CHARCOUNT { get; set; }
        public string ENDCHAR { get; set; }
        public string LEFTCHAR { get; set; }
        public string RIGHTCHAR { get; set; }
    }
}
