//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIELDWFORM
    {
        public int USERID { get; set; }
        public string TABLENAME { get; set; }
        public string QRYNAME { get; set; }
        public string FIELDNAME { get; set; }
        public Nullable<short> WPAGENO { get; set; }
        public Nullable<short> WPAGEITEMNO { get; set; }
    }
}
