//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLBTABLEDESC
    {
        public int LANGID { get; set; }
        public string TABLENAME { get; set; }
        public string SHORTNAME { get; set; }
        public string CAPTION { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> MODGROUPID { get; set; }
        public string MODGROUPNAME { get; set; }
        public Nullable<int> GENGROUPID { get; set; }
    }
}
