//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSTTNMISLEM
    {
        public int STOCKID { get; set; }
        public Nullable<double> BUTFIYAT { get; set; }
        public Nullable<double> BUTPAKETFIYAT { get; set; }
        public Nullable<double> BUTBIRIMI { get; set; }
        public string UYGULAMACINSIYETI { get; set; }
    }
}
