//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LABELPRINTHISTORY
    {
        public int ID { get; set; }
        public Nullable<int> COMPANYID { get; set; }
        public Nullable<int> PWORKSTATIONID { get; set; }
        public string BARCODEPRINTFILE { get; set; }
        public Nullable<bool> SENDPRINT { get; set; }
        public Nullable<int> RECEIPTID { get; set; }
        public Nullable<int> STOCKID { get; set; }
        public string BARCODE { get; set; }
        public string COMPORT { get; set; }
        public Nullable<int> SUBEID { get; set; }
        public string PRINTERNAME { get; set; }
        public string REPORTNAME { get; set; }
        public string SQLTEXT { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> LABELNO { get; set; }
    }
}
