//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUNIT
    {
        public int COMPANYID { get; set; }
        public int MUNITID { get; set; }
        public string MUNITNO { get; set; }
        public string MUNITNAME { get; set; }
        public Nullable<int> MUNITTYPE { get; set; }
        public string MAKE { get; set; }
        public string MODEL { get; set; }
        public string CAPACITY { get; set; }
        public string YEAR { get; set; }
        public string SERIALNO { get; set; }
        public Nullable<double> CURRENTCOUNT { get; set; }
        public Nullable<System.DateTime> CURRENTDATE { get; set; }
        public Nullable<System.DateTime> INSTALLEDDATE { get; set; }
        public string WORKGROUP { get; set; }
        public Nullable<int> PWORKCENTERID { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<bool> LEASED { get; set; }
        public string LEASECOMPANY { get; set; }
        public Nullable<System.DateTime> LEASESTARTDATE { get; set; }
        public Nullable<System.DateTime> LEASEENDDATE { get; set; }
        public Nullable<int> LEASEPERIOD { get; set; }
        public Nullable<int> LEASEINTERVAL { get; set; }
        public Nullable<System.DateTime> WARRANTYSTARTDATE { get; set; }
        public Nullable<System.DateTime> WARRANTYENDDATE { get; set; }
        public Nullable<int> WARRANTYPERIOD { get; set; }
        public Nullable<int> WARRANTYINTERVAL { get; set; }
        public Nullable<System.DateTime> LASTCALIBRATION { get; set; }
        public Nullable<System.DateTime> NEXTCALIBRATION { get; set; }
        public Nullable<int> PWORKSTATIONID { get; set; }
        public Nullable<int> PEQUIPMENTID { get; set; }
        public Nullable<int> MUNITIDPARENT { get; set; }
        public string VENDOR { get; set; }
        public string VENDORPARTNO { get; set; }
        public string MANUFACTURER { get; set; }
        public string MANUFACTURERPARTNO { get; set; }
        public Nullable<System.DateTime> ACQUISITIONDATE { get; set; }
        public Nullable<double> ACQUISITIONCOST { get; set; }
        public Nullable<double> ADDITIONALCOST { get; set; }
        public Nullable<int> ACCCOSTCENTERID { get; set; }
        public string GROUPCODE { get; set; }
        public string SPECCODE1 { get; set; }
        public string SPECCODE2 { get; set; }
        public Nullable<System.DateTime> MAKINGDATE { get; set; }
        public Nullable<System.DateTime> PURCHASEDATE { get; set; }
        public byte[] UNITPICTURE { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
