//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MY_191GIDERLER
    {
        public int SIRKETID { get; set; }
        public int DONEMID { get; set; }
        public Nullable<int> ISLEMTIPI { get; set; }
        public int FISID { get; set; }
        public string EVRAKNO { get; set; }
        public Nullable<int> CARIID { get; set; }
        public string CARINO { get; set; }
        public string CARIADI { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public string ADI { get; set; }
        public Nullable<double> MIKTAR { get; set; }
        public Nullable<decimal> HESAPLANANKDV { get; set; }
        public string FATURABASLIK_GRUPKODU { get; set; }
        public string FATURADETAY_BIRIMADI { get; set; }
    }
}
