//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPCTAGSTATUS
    {
        public int COMPANYID { get; set; }
        public int OPCTAGDEFID { get; set; }
        public Nullable<double> TAGVALUEFLOAT { get; set; }
        public Nullable<double> TAGVALUEBIT { get; set; }
        public string TAGVALUESTRING { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
    }
}
