//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFOLLOWSTOCK
    {
        public int COMPANYID { get; set; }
        public int PFOLLOWID { get; set; }
        public Nullable<int> STOCKID { get; set; }
        public Nullable<int> GRADEID { get; set; }
        public Nullable<int> STOCKLOTSID { get; set; }
        public Nullable<int> ACTIDSUPPLIER { get; set; }
        public Nullable<int> ACTID { get; set; }
        public Nullable<int> ACTIDTRANSPORT { get; set; }
        public Nullable<int> ACTIDDELIVERY { get; set; }
        public Nullable<int> PFALLOWSTATUS { get; set; }
        public Nullable<int> ROOT { get; set; }
        public Nullable<int> ROOTID { get; set; }
        public Nullable<int> ROOTRECEIPTITEMNO { get; set; }
        public string ROOTRECEIPTNO { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> NOTEID { get; set; }
        public string PLACE1 { get; set; }
        public string PLACE2 { get; set; }
        public string PLACE3 { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<double> QUANTITY2 { get; set; }
        public Nullable<double> QUANTITY3 { get; set; }
        public Nullable<short> SLICEDIV { get; set; }
        public Nullable<double> SINGLESLICEKG { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
