//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIDLOTS
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int RECEIPTID { get; set; }
        public Nullable<int> PJOBORDERID { get; set; }
        public Nullable<int> STOCKID { get; set; }
        public Nullable<int> STOCKLOTSID { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<double> QUANTITY2 { get; set; }
        public Nullable<double> QUANTITY3 { get; set; }
        public Nullable<int> DEPOTID { get; set; }
        public Nullable<int> GRADEID { get; set; }
        public Nullable<double> QREM { get; set; }
        public Nullable<double> QREM2 { get; set; }
        public Nullable<double> QREM3 { get; set; }
        public Nullable<double> QERROR { get; set; }
        public Nullable<double> QERROR2 { get; set; }
        public Nullable<double> QERROR3 { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
    }
}
