//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PJOBWORKTIME
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int PRECEIPTID { get; set; }
        public int TREEROUTEITEMNO { get; set; }
        public int ITEMNO { get; set; }
        public Nullable<int> POPERATIONTYPEID { get; set; }
        public Nullable<int> PJOBORDERID { get; set; }
        public Nullable<int> PPROTREEID { get; set; }
        public Nullable<int> STOCKID { get; set; }
        public Nullable<int> GRADEID { get; set; }
        public Nullable<int> EMPLOYEEID { get; set; }
        public Nullable<int> PPROCESSID { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<double> QUANTITY2 { get; set; }
        public Nullable<double> QUANTITY3 { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<double> DURATION { get; set; }
        public Nullable<double> MATMULT { get; set; }
        public Nullable<double> EMPLOYEEMULT { get; set; }
        public Nullable<double> SETUPDURATION { get; set; }
        public Nullable<int> PEQUIPMENTID { get; set; }
        public Nullable<int> PWORKCENTERID { get; set; }
        public Nullable<int> PWORKSTATIONID { get; set; }
    }
}
