//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class POFFER
    {
        public int COMPANYID { get; set; }
        public int POFFERID { get; set; }
        public string POFFERNO { get; set; }
        public Nullable<System.DateTime> TRANSDATE { get; set; }
        public Nullable<int> STOCKID { get; set; }
        public string PARTNAME { get; set; }
        public string CUSTOMERREFERANS { get; set; }
        public string PICTURENO { get; set; }
        public Nullable<int> ACTID { get; set; }
        public string CUSTOMERNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string CURRCODE { get; set; }
        public Nullable<double> CURREXC { get; set; }
        public Nullable<double> SALESTOTAL { get; set; }
        public Nullable<double> SALESCURRTOTAL { get; set; }
        public Nullable<double> COSTTOTAL { get; set; }
        public Nullable<double> COSTCURRTOTAL { get; set; }
        public Nullable<double> MATTOTAL { get; set; }
        public Nullable<double> MATCURRTOTAL { get; set; }
        public Nullable<double> PROCESSTOTAL { get; set; }
        public Nullable<double> PROCESSCURRTOTAL { get; set; }
        public Nullable<double> OTHERTOTAL { get; set; }
        public Nullable<double> OTHERCURRTOTAL { get; set; }
        public Nullable<double> SALESPRICE { get; set; }
        public Nullable<double> SALESCURRPRICE { get; set; }
        public Nullable<double> COSTPRICE { get; set; }
        public Nullable<double> COSTCURRPRICE { get; set; }
        public Nullable<double> ANNUALUSAGE { get; set; }
        public Nullable<double> PROJECTLIFE { get; set; }
        public Nullable<double> PROFITPERCENT { get; set; }
        public Nullable<double> PROFITTOTAL { get; set; }
        public Nullable<double> NETWEIGHT { get; set; }
        public Nullable<int> DELIVERYFREQ { get; set; }
        public Nullable<double> DELIVERYQUANTITY { get; set; }
        public Nullable<double> DELIVERYWEIGHT { get; set; }
        public Nullable<double> CASEINQUANTITY { get; set; }
        public Nullable<double> CASEWEIGHT { get; set; }
        public Nullable<double> PALETTECASEQUANTITY { get; set; }
        public Nullable<double> PALETTEWEIGHT { get; set; }
        public Nullable<double> PALETTEQUANTITY { get; set; }
        public Nullable<double> CASEQUANTITY { get; set; }
        public Nullable<int> STOCKPRICETYPEID { get; set; }
        public byte[] STOCKPICTURE { get; set; }
        public Nullable<System.DateTime> REQUESTDATE { get; set; }
        public Nullable<System.DateTime> DELIVERYDATE { get; set; }
        public Nullable<System.DateTime> DUEDATE { get; set; }
        public Nullable<bool> APPROWED { get; set; }
        public Nullable<int> OFFERSTATUS { get; set; }
        public string CONTACTNAME { get; set; }
        public string GROUPCODE { get; set; }
        public string SPECCODE1 { get; set; }
        public string SPECCODE2 { get; set; }
        public Nullable<int> EMPLOYEEID { get; set; }
        public Nullable<int> PROJECTID { get; set; }
        public byte[] PICTURE { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<int> NOTEID { get; set; }
        public Nullable<System.DateTime> CANCELDATE { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
