//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORDERSPLANMAT
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int PORDERSPLANID { get; set; }
        public int GLBPERIODID { get; set; }
        public int STOCKID { get; set; }
        public int GRADEID { get; set; }
        public int ITEMNO { get; set; }
        public int STOCKIDMAT { get; set; }
        public int GRADEIDMAT { get; set; }
        public Nullable<short> STARTSTOCKTOP { get; set; }
        public Nullable<double> STARTSTOCK { get; set; }
        public Nullable<double> ORDERQUANTITY { get; set; }
        public Nullable<double> QUANTITYPLAN { get; set; }
        public Nullable<double> QUANTITYUSE { get; set; }
        public Nullable<double> QUANTITYPRO { get; set; }
        public Nullable<double> ORDERQUANTITYREQ { get; set; }
        public Nullable<int> ORDERTYPE { get; set; }
        public Nullable<double> QREM { get; set; }
        public Nullable<double> QUANTITYACTUAL { get; set; }
        public Nullable<int> PPROTREEID { get; set; }
        public Nullable<int> ITEMID { get; set; }
        public Nullable<int> PARENTID { get; set; }
        public Nullable<int> TREELEFT { get; set; }
        public Nullable<int> TREERIGHT { get; set; }
        public Nullable<int> PPROCESSID { get; set; }
        public Nullable<int> PWORKSTATIONID { get; set; }
        public Nullable<double> DURATION { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
