//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPACKAGE
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int PPACKAGEID { get; set; }
        public string PPACKAGENO { get; set; }
        public Nullable<int> STOCKPACKAGEID { get; set; }
        public Nullable<System.DateTime> TRANSDATE { get; set; }
        public Nullable<short> LABELID { get; set; }
        public Nullable<int> ACTID { get; set; }
        public Nullable<int> DEPOTIDENTRY { get; set; }
        public Nullable<int> DEPOTIDEXIT { get; set; }
        public string GROUPCODE { get; set; }
        public string SPECCODE1 { get; set; }
        public string SPECCODE2 { get; set; }
        public string SPECCODE3 { get; set; }
        public string SPECCODE4 { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<int> PRINTCOUNT { get; set; }
        public Nullable<double> TARE { get; set; }
        public Nullable<double> WEIGHT { get; set; }
        public Nullable<int> PORDERSID { get; set; }
        public string NOTES { get; set; }
        public Nullable<int> PRECEIPTOTID { get; set; }
        public Nullable<int> EMPLOYEEID { get; set; }
        public Nullable<int> ORDERSID { get; set; }
        public Nullable<int> ORDERSPITEMNO { get; set; }
        public Nullable<int> DELIVERYID { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
