//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPROTREEEQUIPMENT
    {
        public int COMPANYID { get; set; }
        public int PPROTREEID { get; set; }
        public int ITEMID { get; set; }
        public int PEQUIPMENTID { get; set; }
        public Nullable<short> PRIORITY { get; set; }
        public Nullable<int> ITEMNO { get; set; }
    }
}
