//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPROCONFITEM
    {
        public int COMPANYID { get; set; }
        public int PPROCONFID { get; set; }
        public int ITEMID { get; set; }
        public Nullable<int> PARENTID { get; set; }
        public Nullable<int> PARENTIDPRO { get; set; }
        public Nullable<short> ITEMTYPE { get; set; }
        public Nullable<int> PROCESSORDERNO { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> STOCKID { get; set; }
        public Nullable<int> GRADEID { get; set; }
        public Nullable<int> UNITID { get; set; }
        public Nullable<int> PPROCESSID { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<double> QUANTITY2 { get; set; }
        public Nullable<double> QUANTITY3 { get; set; }
        public Nullable<double> NETQUANTITY { get; set; }
        public Nullable<double> MINPRODUCTQUANTITY { get; set; }
        public Nullable<double> RATIOLOSSPERCENT { get; set; }
        public Nullable<int> PPROTREEIDMAT { get; set; }
        public Nullable<int> PPROTREEIDMATITEMID { get; set; }
        public Nullable<double> MATQUANTITY { get; set; }
        public Nullable<double> MATDURATION { get; set; }
        public Nullable<int> DEPOTID { get; set; }
        public Nullable<decimal> DURATION { get; set; }
        public Nullable<decimal> SETUPDURATION { get; set; }
        public string OPSSTOCKDESC { get; set; }
        public Nullable<bool> MATIDPRODUCTID { get; set; }
        public Nullable<bool> WSCAPACITYOPTIONAL { get; set; }
        public Nullable<bool> DEGRADEPAINT { get; set; }
        public Nullable<bool> MATSTOCKIDPROSTOCKID { get; set; }
        public Nullable<double> PRICE { get; set; }
        public string CURRCODE { get; set; }
        public Nullable<double> CURRPRICE { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public Nullable<bool> OPTIONAL { get; set; }
        public Nullable<bool> OPTIONALSEL { get; set; }
        public Nullable<bool> MANYPRODUCT { get; set; }
        public Nullable<bool> MANYPRODUCTOPTIONAL { get; set; }
        public string GRADENAMETOP { get; set; }
        public Nullable<int> STOCKPRICETYPEID { get; set; }
        public Nullable<int> PWORKSTATIONID { get; set; }
        public Nullable<int> PWORKCENTERID { get; set; }
        public Nullable<int> PEQUIPMENTID { get; set; }
        public Nullable<double> EMPLOYEECOUNT { get; set; }
        public Nullable<int> EMPLOYEETASKID { get; set; }
        public Nullable<int> STOCKIDLOSS { get; set; }
        public Nullable<int> GRADEIDLOSS { get; set; }
        public Nullable<double> LOSSQUANTITY { get; set; }
        public Nullable<double> LOSSPERCENT { get; set; }
        public Nullable<bool> DISPLAYORDERSTATUS { get; set; }
        public string ORDERSTATUSDESC { get; set; }
        public Nullable<short> ORDERNO { get; set; }
        public Nullable<short> TREELEVEL { get; set; }
        public Nullable<int> TREELEFT { get; set; }
        public Nullable<int> TREERIGHT { get; set; }
        public Nullable<int> NOTESID { get; set; }
        public string NOTES { get; set; }
        public Nullable<int> PHARMONYID { get; set; }
        public Nullable<bool> OPTIONALQUA { get; set; }
        public Nullable<double> LOSSQUANTITY2 { get; set; }
        public Nullable<double> LOSSQUANTITY3 { get; set; }
        public string OPSFILTER { get; set; }
        public Nullable<int> RELPROC { get; set; }
        public Nullable<bool> OPSQUANGRADE { get; set; }
        public Nullable<bool> OPSSTGRADESTCARD { get; set; }
        public Nullable<bool> ISGRADESELECT { get; set; }
        public Nullable<int> VIEWITEMNO { get; set; }
        public Nullable<short> PROCMULT { get; set; }
        public Nullable<short> PROCDIV { get; set; }
        public Nullable<bool> OPTIONALPAINTQUA { get; set; }
    }
}
