//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRECEIPTOT
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int RECEIPTID { get; set; }
        public string RECEIPTNO { get; set; }
        public Nullable<int> PJOBORDERID { get; set; }
        public Nullable<System.DateTime> TRANSDATE { get; set; }
        public Nullable<int> RECEIPTTYPE { get; set; }
        public Nullable<int> PPROTREEID { get; set; }
        public Nullable<int> ITEMID { get; set; }
        public Nullable<int> STOCKID { get; set; }
        public Nullable<int> GRADEID { get; set; }
        public Nullable<int> PORDERSID { get; set; }
        public Nullable<int> STOCKLOTSID { get; set; }
        public Nullable<int> PORDERSITEMID { get; set; }
        public Nullable<int> PWORKSTATIONID { get; set; }
        public Nullable<int> PWORKCENTERID { get; set; }
        public Nullable<int> PEQUIPMENTID { get; set; }
        public Nullable<int> PROCESSORDERNO { get; set; }
        public Nullable<int> PPROCESSID { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<double> QUANTITY2 { get; set; }
        public Nullable<double> QUANTITY3 { get; set; }
        public Nullable<double> QRETOUCH { get; set; }
        public Nullable<double> QREFUSE { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<double> CAPACITY { get; set; }
        public Nullable<int> DEPOTID { get; set; }
        public string GROUPCODE { get; set; }
        public string SPECCODE1 { get; set; }
        public string SPECCODE2 { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<int> NOTEID { get; set; }
        public Nullable<System.DateTime> CANCELDATE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<bool> CLOSEJOBORDER { get; set; }
        public Nullable<int> PROJECTID { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<int> ACCCOSTCENTERID { get; set; }
        public Nullable<double> UNDEFSTOPDURATION { get; set; }
        public Nullable<double> TARE { get; set; }
        public Nullable<double> WEIGHT { get; set; }
        public Nullable<double> VARUNITVALUE { get; set; }
        public Nullable<decimal> MATCOST { get; set; }
        public Nullable<decimal> PROCESSCOST { get; set; }
        public Nullable<double> RESFLOAT1 { get; set; }
        public Nullable<double> RESFLOAT2 { get; set; }
        public string NOTES { get; set; }
        public Nullable<short> REVITEMNO { get; set; }
        public Nullable<int> STOCKPACKAGEID { get; set; }
        public Nullable<int> SOURCEREFID { get; set; }
        public string SOURCEREFDESC { get; set; }
        public string SPECBATCHNO { get; set; }
        public Nullable<bool> SERIALOK { get; set; }
        public Nullable<double> WORKKW { get; set; }
        public Nullable<double> STOPKW { get; set; }
        public Nullable<double> STANDBYKW { get; set; }
        public Nullable<double> WORKKW1 { get; set; }
        public Nullable<double> STOPKW1 { get; set; }
        public Nullable<double> STANDBYKW1 { get; set; }
        public Nullable<int> ENTALERTID { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
        public Nullable<int> PJOBLOADINGID { get; set; }
    }
}
