//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRECEIPTMAT
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int RECEIPTID { get; set; }
        public short ITEMNO { get; set; }
        public Nullable<int> STOCKID { get; set; }
        public Nullable<int> GRADEID { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<double> QUANTITY2 { get; set; }
        public Nullable<double> QUANTITY3 { get; set; }
        public Nullable<double> QUANTITYTRANS { get; set; }
        public Nullable<short> UNITIDTRANS { get; set; }
        public Nullable<double> QUANTITYSUM { get; set; }
        public Nullable<double> QUANTITY2SUM { get; set; }
        public Nullable<double> QUANTITY3SUM { get; set; }
        public Nullable<double> QUANTITYTRANSSUM { get; set; }
        public Nullable<int> DEPOTIDMAT { get; set; }
        public Nullable<int> STOCKIDLOSS { get; set; }
        public Nullable<int> GRADEIDLOSS { get; set; }
        public Nullable<double> QUANTITYLOSS { get; set; }
        public Nullable<double> QUANTITYTRANSLOSS { get; set; }
        public Nullable<short> UNITIDTRANSLOSS { get; set; }
        public Nullable<int> DEPOTIDLOSS { get; set; }
        public Nullable<decimal> LOSSPERCENT { get; set; }
        public Nullable<double> COSTPRICE { get; set; }
        public Nullable<double> COSTTOTAL { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
