//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRECEIPTERRORS
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int RECEIPTID { get; set; }
        public int PERRORSID { get; set; }
        public Nullable<int> STOCKID { get; set; }
        public Nullable<int> GRADEID { get; set; }
        public Nullable<double> QRETOUCH { get; set; }
        public Nullable<double> QREFUSE { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<double> QUANTITY2 { get; set; }
        public Nullable<double> QUANTITY3 { get; set; }
        public int PRECEIPTERRORSINC { get; set; }
        public Nullable<int> SHIFT { get; set; }
        public Nullable<int> QREFUSEDEPOTID { get; set; }
        public Nullable<int> QRETOUCHDEPOTID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> EMPLOYEEID { get; set; }
        public Nullable<System.DateTime> TRANSDATE { get; set; }
        public Nullable<int> ROOT { get; set; }
        public Nullable<int> ROOTID { get; set; }
        public Nullable<bool> NEXTPROCSEND { get; set; }
        public Nullable<bool> OTHERPRODUCT { get; set; }
        public Nullable<int> PJOBORDERID { get; set; }
        public Nullable<int> STOCKLOTSID { get; set; }
        public string ERRORDETAIL { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
