//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROLLDEFECT
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int PROLLPROID { get; set; }
        public int ITEMNO { get; set; }
        public Nullable<int> ERRORID { get; set; }
        public Nullable<int> EMPLOYEEID { get; set; }
        public Nullable<int> ERRTYPEID { get; set; }
        public Nullable<double> ERRSTARTMT { get; set; }
        public Nullable<double> ERRFINISHMT { get; set; }
        public string ERRSTARTSHIFT { get; set; }
        public string ERRFINISSHIFT { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
