//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSTRONGBOXGROUPSTOCK
    {
        public int COMPANYID { get; set; }
        public int PSTRONGBOXGROUPID { get; set; }
        public int STOCKID { get; set; }
        public Nullable<int> TYPE { get; set; }
        public string SPECCODE1 { get; set; }
        public string SPECCODE2 { get; set; }
        public string SPECCODE3 { get; set; }
        public string GROUPCODE1 { get; set; }
        public string GROUPCODE2 { get; set; }
        public string GROUPCODE3 { get; set; }
        public Nullable<int> EDITUSER { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> INSERTUSER { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
    }
}
