//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCKTECPRM
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int STOCKID { get; set; }
        public int GRADEID { get; set; }
        public int STOCKTECPRMTYPEID { get; set; }
        public Nullable<decimal> NUMVALUE { get; set; }
        public string CHARVALUE { get; set; }
    }
}
