//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCKGRADETRANS
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int STOCKID { get; set; }
        public int GRADEID { get; set; }
        public System.DateTime TRANSDATE { get; set; }
        public short ITEMNO { get; set; }
        public Nullable<int> TRANSTYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public string GROUPCODE { get; set; }
        public string SPECCODE1 { get; set; }
        public string SPECCODE2 { get; set; }
        public string TRANSCODE { get; set; }
        public Nullable<int> EMPLOYEEID { get; set; }
        public Nullable<int> PROJECTID { get; set; }
        public Nullable<int> ACCCOSTCENTERID { get; set; }
        public Nullable<short> ROOT { get; set; }
        public Nullable<int> ROOTID { get; set; }
        public string ROOTRECEIPTNO { get; set; }
        public Nullable<int> ROOTRECEIPTITEMNO { get; set; }
        public Nullable<short> UNITID { get; set; }
        public Nullable<double> QENTRY { get; set; }
        public Nullable<double> QEXIT { get; set; }
        public Nullable<double> QUANTITY2 { get; set; }
        public Nullable<double> QUANTITY3 { get; set; }
        public Nullable<short> UNITIDTRANS { get; set; }
        public Nullable<double> QENTRYTRANS { get; set; }
        public Nullable<double> QEXITTRANS { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<double> CURRPRICE { get; set; }
        public Nullable<decimal> CURRPRICETRANS { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string CURRCODE { get; set; }
        public Nullable<System.DateTime> CURRDATE { get; set; }
        public Nullable<double> CURREXC { get; set; }
        public Nullable<double> CURRTOTAL { get; set; }
        public string CURRCODETRANS { get; set; }
        public Nullable<System.DateTime> CURRDATETRANS { get; set; }
        public Nullable<double> CURREXCTRANS { get; set; }
        public Nullable<decimal> CURRTOTALTRANS { get; set; }
        public Nullable<int> ACTID { get; set; }
        public Nullable<int> DEPOTID { get; set; }
        public Nullable<int> STOCKLOTSID { get; set; }
        public Nullable<double> COSTPRICE { get; set; }
        public Nullable<decimal> EXPENSETOTAL { get; set; }
        public Nullable<decimal> DISCOUNTTOTAL { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> VATTOTAL { get; set; }
        public Nullable<decimal> TAXPRIVATE { get; set; }
        public Nullable<decimal> TAXPRIVATETOTAL { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
