//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDOFFERSWFTITEMS
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int RECEIPTID { get; set; }
        public int ITEMSNO { get; set; }
        public int ITEMNO { get; set; }
        public Nullable<int> SIRA { get; set; }
        public Nullable<int> IPKOD { get; set; }
        public string IPNO { get; set; }
        public string YAPI { get; set; }
        public string CINS { get; set; }
        public Nullable<int> TUR { get; set; }
        public string RKOD { get; set; }
        public string RENK { get; set; }
        public Nullable<double> ATKIAG { get; set; }
        public Nullable<double> FIYAT { get; set; }
        public Nullable<double> AM2FIYAT { get; set; }
        public Nullable<double> AMTULFIYAT { get; set; }
    }
}
