//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDPAINTINGSENDITEMS
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int RECEIPTID { get; set; }
        public int ITEMNO { get; set; }
        public Nullable<int> ROLLID { get; set; }
        public Nullable<bool> ACTST { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<double> QUANTITYKG { get; set; }
    }
}
