//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRSCHEDULER
    {
        public int COMPANYID { get; set; }
        public int TRSCHEDULERID { get; set; }
        public Nullable<int> PARENTID { get; set; }
        public Nullable<int> TYPEID { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> FINISHDATE { get; set; }
        public Nullable<int> OPTIONS { get; set; }
        public string CAPTION { get; set; }
        public Nullable<int> RECURRENCEINDEX { get; set; }
        public byte[] RECURRENCEINFO { get; set; }
        public byte[] RESOURCEID { get; set; }
        public string LOCATION { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<System.DateTime> REMINDERDATE { get; set; }
        public Nullable<int> REMINDERMINUTES { get; set; }
        public Nullable<int> STATE { get; set; }
        public Nullable<int> LABELCOLOR { get; set; }
        public Nullable<System.DateTime> ACTUALSTART { get; set; }
        public Nullable<System.DateTime> ACTUALFINISH { get; set; }
        public string SYNCIDFIELD { get; set; }
        public Nullable<int> EMPLOYEEID { get; set; }
        public Nullable<int> ROOT { get; set; }
        public Nullable<int> ROOTID { get; set; }
        public Nullable<int> ROOTRECEIPTITEMNO { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
        public Nullable<System.DateTime> SUCCESSDATE { get; set; }
        public Nullable<System.DateTime> FAILDATE { get; set; }
    }
}
