//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPSYSPARAM
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int GROUPID { get; set; }
        public int UPSYSPARAMID { get; set; }
        public Nullable<byte> GROUPITEMID { get; set; }
        public Nullable<int> GROUPTYPE { get; set; }
        public Nullable<int> USERID { get; set; }
        public string PARAMNAME { get; set; }
        public string PARAMVALUE { get; set; }
        public Nullable<int> PARAMTYPE { get; set; }
        public string PARAMDESCRIPTION { get; set; }
        public string PARAMDEFAULT { get; set; }
        public Nullable<bool> CHANGEUSER { get; set; }
        public string TABSHEETNAME { get; set; }
        public string NOTES { get; set; }
        public string LANGNOTES { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
