//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_ACTFOOD
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int ACTFOODID { get; set; }
        public Nullable<System.DateTime> TRANSDATE { get; set; }
        public string ACTNO { get; set; }
        public string ACTNAME { get; set; }
        public string ACTTYPE { get; set; }
        public Nullable<int> ACTID { get; set; }
        public Nullable<int> LUNCH { get; set; }
        public Nullable<int> LUNCHFREE { get; set; }
        public Nullable<int> LUNCHBREAK { get; set; }
        public Nullable<int> LUNCHBREAKFREE { get; set; }
        public Nullable<int> LUNCHBREAD { get; set; }
        public Nullable<int> LUNCHDIET { get; set; }
        public Nullable<int> EVENING { get; set; }
        public Nullable<int> EVENINGFREE { get; set; }
        public Nullable<int> EVENINGBREAK { get; set; }
        public Nullable<int> EVENINGBREAKFREE { get; set; }
        public Nullable<int> EVENINGBREAD { get; set; }
        public Nullable<int> EVENINGDIET { get; set; }
        public Nullable<int> NIGHT { get; set; }
        public Nullable<int> NIGHTFREE { get; set; }
        public Nullable<int> NIGHTBREAK { get; set; }
        public Nullable<int> NIGHTBREAKFREE { get; set; }
        public Nullable<int> NIGHTBREAD { get; set; }
        public Nullable<int> NIGHTDIET { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> RECEIPTID { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
