//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_ACTSTOCKCONTGP
    {
        public int COMPANYID { get; set; }
        public string ACTNO { get; set; }
        public string ACTNAME { get; set; }
        public string ACTTYPE { get; set; }
        public int ACTID { get; set; }
        public string STOCKGROUP { get; set; }
        public Nullable<short> STOCKPRICETYPEID { get; set; }
        public Nullable<decimal> DISCOUNT1 { get; set; }
        public Nullable<decimal> DISCOUNT2 { get; set; }
        public Nullable<decimal> DISCOUNT3 { get; set; }
        public Nullable<decimal> DISCOUNT4 { get; set; }
        public Nullable<decimal> DISCOUNT5 { get; set; }
        public Nullable<decimal> DISCOUNT6 { get; set; }
        public Nullable<double> PRICE { get; set; }
        public string PACKAGENAME { get; set; }
        public Nullable<int> STOCKPACKAGEID { get; set; }
        public Nullable<short> PAYMENTDAY { get; set; }
        public Nullable<short> PAYMENTPERIOD { get; set; }
        public string PAYMENTPERIODTYPENAME { get; set; }
        public Nullable<short> PAYMENTPERIODTYPE { get; set; }
        public Nullable<short> PAYMENTPERIODITEM { get; set; }
        public Nullable<short> PAYMENTPERIODDAY { get; set; }
    }
}
