//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_BDELIVERY
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int BDELIVERYID { get; set; }
        public Nullable<System.DateTime> TRANSDATE { get; set; }
        public Nullable<int> ACTID { get; set; }
        public Nullable<int> ACTITEMNO { get; set; }
        public Nullable<int> STOCKID { get; set; }
        public string DESC1 { get; set; }
        public string DESC2 { get; set; }
        public string DESC3 { get; set; }
        public string VARIANT { get; set; }
        public string DESIGN { get; set; }
        public Nullable<double> ENTERTOP { get; set; }
        public Nullable<double> ENTERBALYA { get; set; }
        public Nullable<double> ENTERMT { get; set; }
        public Nullable<double> ENTERKG { get; set; }
        public Nullable<short> PCOLORTYPE { get; set; }
        public Nullable<short> PBPACKAGEID { get; set; }
        public Nullable<int> PDEPOTID { get; set; }
        public Nullable<int> PCOLORID { get; set; }
        public Nullable<double> PHAMWIDTH { get; set; }
        public Nullable<System.DateTime> PTRANSDATE { get; set; }
        public string PPARTYNO { get; set; }
        public Nullable<double> PPRODUCTWIDTH { get; set; }
        public Nullable<int> PNOTEID { get; set; }
        public string STOCKNO { get; set; }
        public string STOCKNAME { get; set; }
        public string ACTNO { get; set; }
        public string ACTNAME { get; set; }
        public string PDEPOTNO { get; set; }
        public Nullable<int> BPARTYENTERID { get; set; }
        public Nullable<bool> PARTYCLOSE { get; set; }
        public string INVOICENO { get; set; }
        public Nullable<int> NOTEID { get; set; }
        public string STATUSNAME { get; set; }
        public Nullable<int> STATUS { get; set; }
    }
}
