//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_BUDGETTRANS
    {
        public int COMPANYID { get; set; }
        public string BUDGETNO { get; set; }
        public string BUDGETNAME { get; set; }
        public string BUDGETTYPE { get; set; }
        public int BUDGETID { get; set; }
        public int ITEMNO { get; set; }
        public Nullable<System.DateTime> TRANSDATE { get; set; }
        public string BUDGETTRANSTYPENAME { get; set; }
        public Nullable<int> BUDGETTRANSTYPE { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public Nullable<double> CURRTOTAL { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
