//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_BANKCREDITPER
    {
        public int COMPANYID { get; set; }
        public string BANKNO { get; set; }
        public string BANKNAME { get; set; }
        public string BANKTYPE { get; set; }
        public int BANKID { get; set; }
        public short ITEMNO { get; set; }
        public Nullable<System.DateTime> PAYMENTDATE { get; set; }
        public Nullable<int> BANKRECEIPTID { get; set; }
        public Nullable<double> CURRTOTAL { get; set; }
        public string CURRCODE { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public Nullable<double> INTERESTTOTAL { get; set; }
        public Nullable<double> REMTOTAL { get; set; }
        public Nullable<double> REMCURRTOTAL { get; set; }
        public Nullable<double> RATEKKDF { get; set; }
        public Nullable<double> RATEBSMV { get; set; }
        public Nullable<double> TOTALKKDF { get; set; }
        public Nullable<double> TOTALBSMV { get; set; }
        public Nullable<double> CREDITRATE { get; set; }
        public string DESCRIPTION { get; set; }
        public string STATUSNAME { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
