//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_EXTMACSTATUS
    {
        public int COMPANYID { get; set; }
        public string PWORKSTATIONNO { get; set; }
        public string PWORKSTATIONNAME { get; set; }
        public string PWORKSTATIONTYPE { get; set; }
        public int PWORKSTATIONID { get; set; }
        public int PID { get; set; }
        public string PSTOPCAUSENO { get; set; }
        public string PSTOPCAUSENAME { get; set; }
        public string PSTOPCAUSETYPE { get; set; }
        public int PSTOPCAUSEID { get; set; }
    }
}
