//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_EFATURAGELENBELGELERIAL
    {
        public Nullable<int> UNIID { get; set; }
        public string PROVIDER { get; set; }
        public string gonderenVknTckn { get; set; }
        public string gonderenEtiket { get; set; }
        public string belgeTuru { get; set; }
        public string belgeNo { get; set; }
        public string belgeVerisi { get; set; }
        public string ettn { get; set; }
        public string belgeSiraNo { get; set; }
        public string belgeTarihi { get; set; }
    }
}
