//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_EXPREVAPART
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int EXPREVAPARTID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> TRANSDATE { get; set; }
        public string EXPREVNO { get; set; }
        public string EXPREVNAME { get; set; }
        public string EXPREVTYPE { get; set; }
        public Nullable<int> EXPREVID { get; set; }
        public string EMPLOYEENO { get; set; }
        public string EMPLOYEENAME { get; set; }
        public string EMPLOYEETYPE { get; set; }
        public Nullable<int> EMPLOYEEID { get; set; }
        public string CURRCODE { get; set; }
        public Nullable<System.DateTime> CURRDATE { get; set; }
        public Nullable<decimal> CURREXC { get; set; }
        public Nullable<double> CURRTOTAL { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
