//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_INCOMETABLE
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int INCOMETABLEID { get; set; }
        public Nullable<int> PERIOD { get; set; }
        public string ACCNO { get; set; }
        public string ACCNAME { get; set; }
        public string ACCTYPE { get; set; }
        public Nullable<int> ACCID { get; set; }
        public Nullable<double> RATE { get; set; }
        public Nullable<double> DEBIT { get; set; }
        public Nullable<double> CREDIT { get; set; }
        public Nullable<int> KACCID { get; set; }
        public Nullable<double> KDEBIT { get; set; }
        public Nullable<double> KCREDIT { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
