//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_MAINTENANCETYPE
    {
        public int COMPANYID { get; set; }
        public int MAINTENANCETYPEID { get; set; }
        public string MAINTENANCETYPENO { get; set; }
        public string MAINTENANCETYPENAME { get; set; }
        public Nullable<int> MWORKGROUPID { get; set; }
        public Nullable<int> MPERIOD { get; set; }
        public Nullable<int> INTERVAL { get; set; }
        public Nullable<int> MDIRECTIONSID { get; set; }
        public string NOTEGENERAL { get; set; }
        public string NOTESAFETY { get; set; }
        public string NOTESPEC { get; set; }
        public string GROUPCODE { get; set; }
        public string SPECCODE1 { get; set; }
        public string SPECCODE2 { get; set; }
        public string STATUSNAME { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
