//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_MEMPLOYEE
    {
        public int COMPANYID { get; set; }
        public int MEMPLOYEEID { get; set; }
        public string MEMPLOYEETYPENAME { get; set; }
        public short MEMPLOYEETYPE { get; set; }
        public string MEMPLOYEENO { get; set; }
        public string MEMPLOYEENAME { get; set; }
        public string GROUPCODE { get; set; }
        public string SPECCODE1 { get; set; }
        public string SPECCODE2 { get; set; }
        public string EMPLOYEENO { get; set; }
        public string EMPLOYEENAME { get; set; }
        public string EMPLOYEETYPE { get; set; }
        public Nullable<int> EMPLOYEEID { get; set; }
        public string STATUSNAME { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> NOTEID { get; set; }
        public Nullable<System.DateTime> CANCELDATE { get; set; }
        public string DESCRIPTION { get; set; }
        public string CONTACTNAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string POSTALCODE { get; set; }
        public string CITY { get; set; }
        public string TOWN { get; set; }
        public string COUNTRY { get; set; }
        public string STATE { get; set; }
        public string REGION { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE2 { get; set; }
        public string FAX { get; set; }
        public string GSM { get; set; }
        public string EMAIL { get; set; }
        public string WEB { get; set; }
        public Nullable<int> ADRESSID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string BANKBILLNO { get; set; }
        public Nullable<double> PAYMENT { get; set; }
        public string PAYMENTTYPENAME { get; set; }
        public Nullable<short> PAYMENTTYPE { get; set; }
        public Nullable<System.DateTime> ENTRYDATE { get; set; }
        public Nullable<System.DateTime> EXITDATE { get; set; }
        public Nullable<short> GENDER { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public string BLOODGROUP { get; set; }
        public string TASKTYPENAME { get; set; }
        public Nullable<short> TASKTYPE { get; set; }
        public string SPECCODEUNVAN { get; set; }
        public string COUNTRYIDNO { get; set; }
        public string INSURANCENO { get; set; }
        public string TAXNO { get; set; }
        public string PASS { get; set; }
        public string SPECCODEUZMANLIK { get; set; }
        public Nullable<int> HSTTNMUNITEID { get; set; }
        public Nullable<bool> SALESEMPLOYEE { get; set; }
        public Nullable<int> MWORKGROUPID { get; set; }
        public Nullable<bool> MWORKGROUPMANAGER { get; set; }
        public Nullable<int> MSTATUS { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
