//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_ORDERSTATUSMATRIX
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int ROOT { get; set; }
        public int ROOTID { get; set; }
        public int ROOTITEMNO { get; set; }
        public int MATRIXDEFIDCOL { get; set; }
        public int MATRIXDEFIDROW { get; set; }
        public int ORDERSID { get; set; }
        public int ORDERSITEMNO { get; set; }
        public Nullable<short> PHASE { get; set; }
        public string STOCKNO { get; set; }
        public string STOCKNAME { get; set; }
        public string STOCKTYPE { get; set; }
        public int STOCKID { get; set; }
        public System.DateTime TRANSDATE { get; set; }
        public int ITEMNO { get; set; }
        public Nullable<double> QUANTITY { get; set; }
    }
}
