//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_PLINEINF
    {
        public int COMPANYID { get; set; }
        public int PLINEID { get; set; }
        public Nullable<int> PID { get; set; }
        public string STOCKNO { get; set; }
        public string STOCKNAME { get; set; }
        public string STOCKTYPE { get; set; }
        public Nullable<int> STOCKID { get; set; }
        public string GRADENAME { get; set; }
        public Nullable<int> GRADEID { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<double> JOBQUANTITY { get; set; }
        public Nullable<double> CAPACITY { get; set; }
        public string STATUSNAME { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string PSTOPCAUSENO { get; set; }
        public string PSTOPCAUSENAME { get; set; }
        public string PSTOPCAUSETYPE { get; set; }
        public Nullable<int> PSTOPCAUSEID { get; set; }
        public Nullable<int> STOPPWORKSTATIONID { get; set; }
        public Nullable<double> DURATIONTOTAL { get; set; }
    }
}
