//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_PARTSALESINFO
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int RECEIPTID { get; set; }
        public Nullable<double> CASHTOTAL { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<int> PARTCOUNT { get; set; }
        public Nullable<int> WEEKMONTH { get; set; }
        public Nullable<int> STARTDAY { get; set; }
        public Nullable<int> MONTHDAY { get; set; }
    }
}
