//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_PWFTINFO
    {
        public int COMPANYID { get; set; }
        public int PDSGNCARDID { get; set; }
        public int ITEMNO { get; set; }
        public string CARDNO { get; set; }
        public string PTHREADNO { get; set; }
        public string PTHREADUNIT { get; set; }
        public string PTHREADCODE { get; set; }
        public string PTHREADTYPE { get; set; }
        public string PHYSICAL { get; set; }
        public string COLOURCODE { get; set; }
        public Nullable<int> STOCKID { get; set; }
        public int PTHREADCARDID { get; set; }
        public Nullable<int> SUMWIRE { get; set; }
        public Nullable<double> WRPITEMSHRRO { get; set; }
        public Nullable<int> ORDERNUM { get; set; }
        public Nullable<int> PARENTID { get; set; }
        public Nullable<double> AG { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
