//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_PDSGNCARD
    {
        public int COMPANYID { get; set; }
        public int PDSGNCARDID { get; set; }
        public string DSGNNO { get; set; }
        public string DSGNVARIANT { get; set; }
        public Nullable<int> PARENTID { get; set; }
        public string QUALITY1 { get; set; }
        public string QUALITY2 { get; set; }
        public string QUALITYNAME { get; set; }
        public string DISCNO { get; set; }
        public string LOOMTYPE { get; set; }
        public string DSGNTYPE { get; set; }
        public Nullable<double> WFTSHRRO { get; set; }
        public Nullable<double> WFTDENSITY { get; set; }
        public Nullable<double> WFTDENSITY2 { get; set; }
        public Nullable<double> WFTDENSITY3 { get; set; }
        public Nullable<double> WFTDENSITY4 { get; set; }
        public Nullable<double> WFTDENSITY5 { get; set; }
        public Nullable<double> WFTDENSITY6 { get; set; }
        public Nullable<double> WFTDENSITY7 { get; set; }
        public Nullable<double> WFTDENSITY8 { get; set; }
        public Nullable<double> WFTSUMWDTH { get; set; }
        public Nullable<double> WFTSUMEN { get; set; }
        public Nullable<double> COMBWDTH { get; set; }
        public string PAINTTYPE { get; set; }
        public string APRETYPE { get; set; }
        public Nullable<double> PAINTSHRRO { get; set; }
        public Nullable<int> WRPREPNO { get; set; }
        public Nullable<int> WFTREPNO { get; set; }
        public Nullable<int> ARMKNNO { get; set; }
        public Nullable<int> TAHAREPNO { get; set; }
        public string UPWRPTENS { get; set; }
        public string DOWNWRPTENS { get; set; }
        public string MIXTURE { get; set; }
        public Nullable<int> ROOTSTOCKID { get; set; }
        public Nullable<int> CVARIANT { get; set; }
        public string DOUBLEWEFT { get; set; }
        public Nullable<int> PPROTREEID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> PROUTEID { get; set; }
        public string UNITNAME { get; set; }
        public string UNITIDNAME { get; set; }
        public string INTUNITCODE { get; set; }
        public Nullable<int> UNITID { get; set; }
        public string DEPOTNO { get; set; }
        public string DEPOTNAME { get; set; }
        public string DEPOTTYPE { get; set; }
        public Nullable<int> DEPOTID { get; set; }
        public string ACTNO { get; set; }
        public string ACTNAME { get; set; }
        public string ACTTYPE { get; set; }
        public Nullable<int> ACTID { get; set; }
        public Nullable<bool> APPROVE { get; set; }
        public string GROUPCODE { get; set; }
        public string SPECCODE1 { get; set; }
        public string SPECCODE2 { get; set; }
        public string HS { get; set; }
        public string STATUSNAME { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<double> ORTATKISIK { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
