//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_PTHREADROLL
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int PTHREADROLLID { get; set; }
        public string PTHREADROLLNO { get; set; }
        public string PJOBORDERRECEIPTNO { get; set; }
        public Nullable<int> PJOBORDERID { get; set; }
        public Nullable<System.DateTime> TRANSDATE { get; set; }
        public string RECEIPTTYPENAME { get; set; }
        public Nullable<int> RECEIPTTYPE { get; set; }
        public string STOCKNO { get; set; }
        public string STOCKNAME { get; set; }
        public string STOCKTYPE { get; set; }
        public Nullable<int> STOCKID { get; set; }
        public string GRADENAME { get; set; }
        public Nullable<int> GRADEID { get; set; }
        public string EMPLOYEENO { get; set; }
        public string EMPLOYEENAME { get; set; }
        public string EMPLOYEETYPE { get; set; }
        public Nullable<int> EMPLOYEEID { get; set; }
        public string GROUPCODE { get; set; }
        public string SPECCODE1 { get; set; }
        public string SPECCODE2 { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<double> BRUTQTY { get; set; }
        public Nullable<double> BOBINDARA { get; set; }
        public Nullable<double> BOBINQTY { get; set; }
        public Nullable<double> KOLIDARA { get; set; }
        public Nullable<int> STOCKIDKOLI { get; set; }
        public Nullable<int> STOCKIDBOBIN { get; set; }
        public Nullable<int> STOCKLOTSID { get; set; }
        public string LOTNO { get; set; }
        public string OPPLOTNO { get; set; }
        public string PARTY { get; set; }
        public string DEPOTNO { get; set; }
        public string DEPOTNAME { get; set; }
        public string DEPOTTYPE { get; set; }
        public Nullable<int> DEPOTID { get; set; }
        public Nullable<int> STOREHOUSEID { get; set; }
        public string DEPOTNOEXIT { get; set; }
        public string DEPOTNAMEEXIT { get; set; }
        public string DEPOTTYPEEXIT { get; set; }
        public Nullable<int> DEPOTIDEXIT { get; set; }
        public Nullable<int> STOREHOUSEIDEXIT { get; set; }
        public Nullable<bool> ISPRINT { get; set; }
        public Nullable<bool> CLOSEJOBORDER { get; set; }
        public string PPACKAGENO { get; set; }
        public Nullable<int> PPACKAGEID { get; set; }
        public string ACTNO { get; set; }
        public string ACTNAME { get; set; }
        public string ACTTYPE { get; set; }
        public Nullable<int> ACTID { get; set; }
        public Nullable<int> ORDERSID { get; set; }
        public Nullable<int> ORDERSITEMNO { get; set; }
        public string STATUSNAME { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<double> FIRE { get; set; }
        public Nullable<int> KASAADET { get; set; }
        public Nullable<double> GREASE { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
