//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_PPROSERIESRAW
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int PPROSERIESID { get; set; }
        public int ITEMNO { get; set; }
        public int ITEMNO2 { get; set; }
        public string STOCKNO { get; set; }
        public string STOCKNAME { get; set; }
        public string STOCKTYPE { get; set; }
        public Nullable<int> STOCKID { get; set; }
        public string DEPOTNO { get; set; }
        public string DEPOTNAME { get; set; }
        public string DEPOTTYPE { get; set; }
        public Nullable<int> DEPOTID { get; set; }
        public string SERIESNO { get; set; }
        public Nullable<int> STOCKSERIESID { get; set; }
        public string LOTNO { get; set; }
        public string OPPLOTNO { get; set; }
        public string BATCHNO { get; set; }
        public Nullable<int> STOCKLOTSID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> RECEIPTITEMNO { get; set; }
        public Nullable<short> ROOT { get; set; }
        public Nullable<int> ROOTID { get; set; }
        public Nullable<int> ROOTRECEIPTITEMNO { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
