//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_PPROCNCITEM
    {
        public int COMPANYID { get; set; }
        public int PPROCNCID { get; set; }
        public int ITEMNO { get; set; }
        public string STOCKNO { get; set; }
        public string STOCKNAME { get; set; }
        public string STOCKTYPE { get; set; }
        public Nullable<int> STOCKID { get; set; }
        public string DESCRIPTION { get; set; }
        public string IMAGENUMBER { get; set; }
        public Nullable<double> MULTQTY { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<double> QUANTITY2 { get; set; }
        public Nullable<double> QUANTITY3 { get; set; }
        public string NUNITNAME { get; set; }
        public string CURRCODE { get; set; }
        public Nullable<double> CURRPRICE { get; set; }
        public Nullable<double> CURRRPRICE { get; set; }
        public Nullable<System.DateTime> CURRDATE { get; set; }
        public Nullable<double> CURREXC { get; set; }
        public Nullable<double> PRICE { get; set; }
        public string RAWMATERIALSTOCKNO { get; set; }
        public string RAWMATERIALSTOCKNAME { get; set; }
        public Nullable<int> RAWMATERIALID { get; set; }
        public Nullable<double> RAWMATERIALPRICE { get; set; }
        public string PPROCCUTPPROCESSNO { get; set; }
        public string PPROCCUTPPROCESSNAME { get; set; }
        public Nullable<int> PPROCCUTID { get; set; }
        public Nullable<double> PPROCCUTPRICE { get; set; }
        public string PPROCBLACKOUTDESC { get; set; }
        public string PPROCHEATOPDESC { get; set; }
        public string PPROCOTHERDESC { get; set; }
        public Nullable<double> PPROCOTHERPRICE { get; set; }
        public Nullable<double> PPROCOTHERRPRICE { get; set; }
        public string PPROCACTDESC { get; set; }
        public Nullable<double> PPROCTAILINGDURATION { get; set; }
        public Nullable<double> PPROCTAILINGRDURATION { get; set; }
        public Nullable<double> PPROCCNCDURATION { get; set; }
        public Nullable<double> PPROCCNCRDURATION { get; set; }
        public Nullable<double> PPROCWELDDURATION { get; set; }
        public Nullable<double> PPROCWELDRDURATION { get; set; }
        public Nullable<double> PPROCMONTAGEDURATION { get; set; }
        public Nullable<double> PPROCMONTAGERDURATION { get; set; }
        public Nullable<double> PPROCMEASUREDURATION { get; set; }
        public Nullable<double> PPROCMEASURERDURATION { get; set; }
        public Nullable<double> PPROCSTARTUPDURATION { get; set; }
        public Nullable<double> PPROCSTARTUPRDURATION { get; set; }
        public string MAKEBUY { get; set; }
        public Nullable<decimal> RAWMATERIALTOTAL { get; set; }
        public Nullable<decimal> PPROCCUTTOTAL { get; set; }
        public Nullable<decimal> PPROCBLACKOUTTOTAL { get; set; }
        public Nullable<decimal> PPROCHEATOPTOTAL { get; set; }
        public Nullable<decimal> LABORTOTAL { get; set; }
        public Nullable<decimal> LABORRTOTAL { get; set; }
        public Nullable<decimal> SUMCOSTTOTAL { get; set; }
        public Nullable<decimal> RSUMCOSTOTAL { get; set; }
        public Nullable<decimal> CURRSUMCOSTTOTAL { get; set; }
        public Nullable<decimal> CURRRSUMCOSTOTAL { get; set; }
        public string SIZEDESC { get; set; }
        public Nullable<double> WEIGHT { get; set; }
        public Nullable<int> PITEMNO { get; set; }
        public Nullable<double> STOCKPRICE { get; set; }
    }
}
