//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_PURCHOFFER
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int RECEIPTID { get; set; }
        public string TRANSTYPENAME { get; set; }
        public Nullable<short> TRANSTYPE { get; set; }
        public string RECEIPTNO { get; set; }
        public Nullable<System.DateTime> TRANSDATE { get; set; }
        public string GROUPCODE { get; set; }
        public string SPECCODE1 { get; set; }
        public string SPECCODE2 { get; set; }
        public string TRANSCODE { get; set; }
        public string EMPLOYEENO { get; set; }
        public string EMPLOYEENAME { get; set; }
        public string EMPLOYEETYPE { get; set; }
        public Nullable<int> EMPLOYEEID { get; set; }
        public Nullable<bool> APPROVE { get; set; }
        public Nullable<bool> APPROVE2 { get; set; }
        public Nullable<bool> APPROVE3 { get; set; }
        public string STATUSNAME { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<int> NOTEID { get; set; }
        public Nullable<System.DateTime> CANCELDATE { get; set; }
        public string DESCRIPTION { get; set; }
        public string DOCUMENTNO { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string CURRCODE { get; set; }
        public Nullable<System.DateTime> CURRDATE { get; set; }
        public Nullable<double> CURREXC { get; set; }
        public Nullable<double> CURRTOTAL { get; set; }
        public string CURRCODETRANS { get; set; }
        public Nullable<System.DateTime> CURRDATETRANS { get; set; }
        public Nullable<double> CURREXCTRANS { get; set; }
        public Nullable<decimal> CURRTOTALTRANS { get; set; }
        public string TAXOFFICE { get; set; }
        public string TAXNO { get; set; }
        public string TAXCITY { get; set; }
        public Nullable<System.DateTime> DUEDATE { get; set; }
        public Nullable<short> DUEDAY { get; set; }
        public Nullable<System.DateTime> DUEOPSDATE { get; set; }
        public Nullable<short> CATEGORYID { get; set; }
        public string PAYMENTTYPENAME { get; set; }
        public Nullable<short> PAYMENTTYPE { get; set; }
        public Nullable<bool> EXPORTENTRY { get; set; }
        public Nullable<double> DISCOUNTTOTAL1 { get; set; }
        public Nullable<decimal> DISCOUNT1 { get; set; }
        public Nullable<double> DISCOUNTTOTAL2 { get; set; }
        public Nullable<decimal> DISCOUNT2 { get; set; }
        public Nullable<decimal> PRODUCTSUM { get; set; }
        public Nullable<decimal> DISCOUNTSUM { get; set; }
        public Nullable<decimal> PRODUCTSUMOUTVAT { get; set; }
        public Nullable<decimal> DISCOUNTSUMOUTVAT { get; set; }
        public Nullable<decimal> BREAKTOTALOUTVAT { get; set; }
        public Nullable<decimal> VATSUM { get; set; }
        public Nullable<decimal> TAXPRIVATESUM { get; set; }
        public Nullable<decimal> TAKEUPTAXSUM { get; set; }
        public Nullable<decimal> TAKEUPMULT { get; set; }
        public Nullable<decimal> TAKEUPDIV { get; set; }
        public Nullable<decimal> STOPAJRATE { get; set; }
        public Nullable<decimal> STOPAJ { get; set; }
        public Nullable<bool> ACCCHECK { get; set; }
        public Nullable<double> COSTPRICE { get; set; }
        public Nullable<System.DateTime> DUEDATEVAT { get; set; }
        public Nullable<decimal> ROTATETOTAL { get; set; }
        public string CASHNO { get; set; }
        public string CASHNAME { get; set; }
        public string CASHTYPE { get; set; }
        public Nullable<int> CASHID { get; set; }
        public string DEPOTNO { get; set; }
        public string DEPOTNAME { get; set; }
        public string DEPOTTYPE { get; set; }
        public Nullable<int> DEPOTID { get; set; }
        public string ACTNO { get; set; }
        public string ACTNAME { get; set; }
        public string ACTTYPE { get; set; }
        public Nullable<int> ACTID { get; set; }
        public string BANKNO { get; set; }
        public string BANKNAME { get; set; }
        public string BANKTYPE { get; set; }
        public Nullable<int> BANKID { get; set; }
        public Nullable<decimal> BANKTOTAL { get; set; }
        public string NAME1 { get; set; }
        public string NAME2 { get; set; }
        public Nullable<int> ADDRESSID { get; set; }
        public Nullable<System.DateTime> VALIDDATE { get; set; }
        public Nullable<System.DateTime> DELIVERYDATE { get; set; }
        public Nullable<int> DELIVERYACTID { get; set; }
        public string DELIVERYNAME { get; set; }
        public string DELIVERYNAME2 { get; set; }
        public Nullable<int> DELIVERYADDRESSID { get; set; }
        public string DESCRIPTION1 { get; set; }
        public string DESCRIPTION2 { get; set; }
        public string PROJECTNO { get; set; }
        public string PROJECTNAME { get; set; }
        public Nullable<int> PROJECTID { get; set; }
        public string ACCCOSTCENTERNO { get; set; }
        public string ACCCOSTCENTERNAME { get; set; }
        public Nullable<int> ACCCOSTCENTERID { get; set; }
        public string CURRTRANSTYPENAME { get; set; }
        public Nullable<bool> CURRTRANSTYPE { get; set; }
        public string RECEIPTTYPENAME { get; set; }
        public Nullable<int> RECEIPTTYPE { get; set; }
        public Nullable<int> SID { get; set; }
        public string PACKAGENAME { get; set; }
        public Nullable<int> STOCKPACKAGEID { get; set; }
        public Nullable<short> PARTCOUNT { get; set; }
        public Nullable<short> GLBPAYMENTID { get; set; }
        public Nullable<int> ACCRECEIPTID { get; set; }
        public Nullable<bool> MANUELVAT { get; set; }
        public Nullable<double> PARTYSIZE { get; set; }
        public Nullable<int> STOCKPRICETYPEID { get; set; }
        public Nullable<int> CRMINTERVIEWID { get; set; }
        public string CRMCONTACTSFULLNAME { get; set; }
        public Nullable<int> CRMCONTACTSID { get; set; }
        public string BUDGETNO { get; set; }
        public string BUDGETNAME { get; set; }
        public string BUDGETTYPE { get; set; }
        public Nullable<int> BUDGETID { get; set; }
        public Nullable<double> BREAKTOTAL { get; set; }
        public Nullable<bool> SENDDOC { get; set; }
        public Nullable<decimal> CURRDISCOUNTTOTAL1 { get; set; }
        public string REJECTREASON { get; set; }
        public string CHECKMD5SUM { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
