//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_PSHIFTTIME
    {
        public int COMPANYID { get; set; }
        public int PSHIFTTIMEID { get; set; }
        public string PWORKSTATIONNO { get; set; }
        public string PWORKSTATIONNAME { get; set; }
        public string PWORKSTATIONTYPE { get; set; }
        public Nullable<int> PWORKSTATIONID { get; set; }
        public string PWORKCENTERNO { get; set; }
        public string PWORKCENTERNAME { get; set; }
        public string PWORKCENTERTYPE { get; set; }
        public Nullable<int> PWORKCENTERID { get; set; }
        public Nullable<int> SHIFT { get; set; }
        public string STATUSNAME { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> FINISHTIME { get; set; }
        public Nullable<System.DateTime> FIRSTTEABREAKS { get; set; }
        public Nullable<System.DateTime> FIRSTTEABREAKF { get; set; }
        public Nullable<int> FBPSCID { get; set; }
        public Nullable<System.DateTime> SECONDTEABREAKS { get; set; }
        public Nullable<System.DateTime> SECONDTEABREAKF { get; set; }
        public Nullable<int> SBPSCID { get; set; }
        public Nullable<System.DateTime> EATBREAKS { get; set; }
        public Nullable<System.DateTime> EATBREAKF { get; set; }
        public Nullable<int> EBPSCID { get; set; }
        public Nullable<System.DateTime> OVERTIMEBREAKS { get; set; }
        public Nullable<System.DateTime> OVERTIMEBREAKF { get; set; }
        public Nullable<int> OTBPSCID { get; set; }
        public Nullable<System.DateTime> OVERTIMES { get; set; }
        public Nullable<System.DateTime> OVERTIMEF { get; set; }
        public Nullable<int> OTPSCID { get; set; }
        public string STARTTIMESTR { get; set; }
        public string FINISHTIMESTR { get; set; }
        public string FIRSTTEABREAKSSTR { get; set; }
        public string FIRSTTEABREAKFSTR { get; set; }
        public string SECONDTEABREAKSSTR { get; set; }
        public string SECONDTEABREAKFSTR { get; set; }
        public string EATBREAKSSTR { get; set; }
        public string EATBREAKFSTR { get; set; }
        public string OVERTIMEBREAKSSTR { get; set; }
        public string OVERTIMEBREAKFSTR { get; set; }
        public string OVERTIMESSTR { get; set; }
        public string OVERTIMEFSTR { get; set; }
        public Nullable<bool> WORKDAY1 { get; set; }
        public Nullable<bool> WORKDAY2 { get; set; }
        public Nullable<bool> WORKDAY3 { get; set; }
        public Nullable<bool> WORKDAY4 { get; set; }
        public Nullable<bool> WORKDAY5 { get; set; }
        public Nullable<bool> WORKDAY6 { get; set; }
        public Nullable<bool> WORKDAY7 { get; set; }
        public string PSHIFTTIMENAME { get; set; }
        public Nullable<bool> OPTIONAL { get; set; }
        public Nullable<int> TOTALWORKMINUTE { get; set; }
        public Nullable<int> TOTALWORKTIME { get; set; }
        public Nullable<bool> ADDDAYSTARTTIME { get; set; }
        public Nullable<bool> ADDDAYFINISHTIME { get; set; }
        public Nullable<bool> MINUSSTARTTIME { get; set; }
        public Nullable<bool> MINUSFINISHTIME { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
        public Nullable<int> TOTALOVERMINUTE { get; set; }
    }
}
