//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_PRECEIPTROUTE
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int RECEIPTID { get; set; }
        public short ITEMNO { get; set; }
        public string PPROCESSNO { get; set; }
        public string PPROCESSNAME { get; set; }
        public string PPROCESSTYPE { get; set; }
        public Nullable<int> PPROCESSID { get; set; }
        public Nullable<decimal> DURATION { get; set; }
        public Nullable<decimal> SETUPDURATION { get; set; }
        public Nullable<decimal> DURATIONSUM { get; set; }
        public string PWORKSTATIONNO { get; set; }
        public string PWORKSTATIONNAME { get; set; }
        public string PWORKSTATIONTYPE { get; set; }
        public Nullable<int> PWORKSTATIONID { get; set; }
        public string PWORKCENTERNO { get; set; }
        public string PWORKCENTERNAME { get; set; }
        public string PWORKCENTERTYPE { get; set; }
        public Nullable<int> PWORKCENTERID { get; set; }
        public string PEQUIPMENTNO { get; set; }
        public string PEQUIPMENTNAME { get; set; }
        public string PEQUIPMENTTYPE { get; set; }
        public Nullable<int> PEQUIPMENTID { get; set; }
        public Nullable<short> EMPLOYEECOUNT { get; set; }
        public Nullable<double> COSTPRICE { get; set; }
        public Nullable<double> COSTTOTAL { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
