//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_PJOBORDEROTHERPROE
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int RECEIPTID { get; set; }
        public int ITEMNO { get; set; }
        public string STOCKNO { get; set; }
        public string STOCKNAME { get; set; }
        public string STOCKTYPE { get; set; }
        public Nullable<int> STOCKID { get; set; }
        public string GRADENAME { get; set; }
        public Nullable<int> GRADEID { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<double> QUANTITY2 { get; set; }
        public Nullable<double> QUANTITY3 { get; set; }
        public Nullable<int> PPROTREEID { get; set; }
        public Nullable<int> ITEMID { get; set; }
        public string PORDERSNO { get; set; }
        public Nullable<int> PORDERSID { get; set; }
        public Nullable<int> PORDERSITEMID { get; set; }
        public string DEPOTNO { get; set; }
        public string DEPOTNAME { get; set; }
        public string DEPOTTYPE { get; set; }
        public Nullable<int> DEPOTID { get; set; }
        public Nullable<bool> MATCALC { get; set; }
        public Nullable<bool> PORDERSSELECTED { get; set; }
        public Nullable<bool> LOSSSTOCK { get; set; }
        public string REVNO { get; set; }
        public Nullable<short> REVITEMNO { get; set; }
        public Nullable<double> QUANTITYSEND { get; set; }
        public Nullable<double> QUANTITYPRO { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
