//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_PCOSTWORKCENTERDEF
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int PCOSTTYPEID { get; set; }
        public string GLBPERIODNO { get; set; }
        public string GLBPERIODNAME { get; set; }
        public int GLBPERIODID { get; set; }
        public string PWORKCENTERNO { get; set; }
        public string PWORKCENTERNAME { get; set; }
        public string PWORKCENTERTYPE { get; set; }
        public int PWORKCENTERID { get; set; }
        public string ACCNO { get; set; }
        public string ACCNAME { get; set; }
        public string ACCTYPE { get; set; }
        public int ACCID { get; set; }
        public string ACCCOSTCENTERNO { get; set; }
        public string ACCCOSTCENTERNAME { get; set; }
        public int ACCCOSTCENTERID { get; set; }
        public Nullable<double> PERCENTAGE { get; set; }
        public Nullable<bool> EMPLOYEECOUNT { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
