//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_PPACKAGEITEM
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public string PPACKAGENO { get; set; }
        public int PPACKAGEID { get; set; }
        public short ITEMNO { get; set; }
        public string STOCKNO { get; set; }
        public string STOCKNAME { get; set; }
        public string STOCKTYPE { get; set; }
        public Nullable<int> STOCKID { get; set; }
        public string GRADENAME { get; set; }
        public Nullable<int> GRADEID { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<double> QUANTITY2 { get; set; }
        public Nullable<double> QUANTITY3 { get; set; }
        public Nullable<int> ORDERSID { get; set; }
        public Nullable<int> ORDERSITEMNO { get; set; }
        public Nullable<int> PJOBORDERID { get; set; }
        public string LOTNO { get; set; }
        public string OPPLOTNO { get; set; }
        public string BATCHNO { get; set; }
        public Nullable<int> STOCKLOTSID { get; set; }
        public Nullable<int> PJOBENTRYID { get; set; }
        public string DELIVERYNO { get; set; }
        public Nullable<int> DELIVERYID { get; set; }
        public Nullable<int> DELIVERYITEMNO { get; set; }
        public Nullable<int> PJOBORDERIDE { get; set; }
        public string DESCRIPTION1 { get; set; }
        public string DESCRIPTION2 { get; set; }
        public string GROUPCODE { get; set; }
        public string SPECCODE1 { get; set; }
        public string SPECCODE2 { get; set; }
        public string SPECCODE3 { get; set; }
        public string SPECCODE4 { get; set; }
        public Nullable<double> DQUANTITY { get; set; }
        public Nullable<double> DQUANTITY2 { get; set; }
        public Nullable<double> DQUANTITY3 { get; set; }
        public Nullable<double> GREASE { get; set; }
        public string STATUSNAME { get; set; }
        public Nullable<short> STATUS { get; set; }
        public string SOURCEPPACKAGENO { get; set; }
        public Nullable<int> PPACKAGEIDSOURCE { get; set; }
        public string SERIESNO { get; set; }
        public Nullable<int> STOCKSERIESID { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
        public Nullable<int> DEPOTID { get; set; }
        public Nullable<int> PSTRONGBOXID { get; set; }
        public string DEPOTNAME { get; set; }
    }
}
