//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_REPORTFILTERS
    {
        public int USERID { get; set; }
        public int REPORTID { get; set; }
        public int FILTERID { get; set; }
        public Nullable<bool> DEFAULTFILTER { get; set; }
        public string FILTERNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string FILTERTEXT { get; set; }
        public string FSORTFIELD { get; set; }
        public Nullable<bool> LASTSHOW { get; set; }
    }
}
