//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_STOCKMIXED
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int RECEIPTID { get; set; }
        public string RECEIPTNO { get; set; }
        public string STOCKNO { get; set; }
        public string STOCKNAME { get; set; }
        public string STOCKTYPE { get; set; }
        public int STOCKID { get; set; }
        public string GRADENAME { get; set; }
        public int GRADEID { get; set; }
        public string DEPOTNO { get; set; }
        public string DEPOTNAME { get; set; }
        public string DEPOTTYPE { get; set; }
        public Nullable<int> DEPOTID { get; set; }
        public string DEPOTNOLOSS { get; set; }
        public string DEPOTNAMELOSS { get; set; }
        public string DEPOTTYPELOSS { get; set; }
        public Nullable<int> DEPOTIDLOSS { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<double> QUANTITY2 { get; set; }
        public Nullable<double> QUANTITY3 { get; set; }
        public string DESCRIPTION { get; set; }
        public string STATUSNAME { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string GROUPCODE { get; set; }
        public string SPECCODE1 { get; set; }
        public string SPECCODE2 { get; set; }
        public string UNITNAME { get; set; }
        public string UNITIDNAME { get; set; }
        public string INTUNITCODE { get; set; }
        public Nullable<int> UNITID { get; set; }
        public string STOCKNOLOSS { get; set; }
        public string STOCKNAMELOSS { get; set; }
        public Nullable<int> STOCKIDLOSS { get; set; }
        public string GRADENAMELOSS { get; set; }
        public Nullable<int> GRADEIDLOSS { get; set; }
        public Nullable<double> LOSSQUANTITY { get; set; }
        public Nullable<double> LOSSPERCENT { get; set; }
        public Nullable<int> INSERTUSERID { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<int> EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> GLBALERTID { get; set; }
    }
}
