//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_SQLQUERY
    {
        public int QUERYID { get; set; }
        public string SQLNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string SQL { get; set; }
        public string LINKNAME { get; set; }
    }
}
