//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_TDBLOKESTOCKS
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int ITEMNO { get; set; }
        public int JOBORDERID { get; set; }
        public string STOCKNO { get; set; }
        public string STOCKNAME { get; set; }
        public string STOCKTYPE { get; set; }
        public Nullable<int> STOCKID { get; set; }
        public string SLNO { get; set; }
        public string LOTNO { get; set; }
        public string DEPOTNO { get; set; }
        public string DEPOTNAME { get; set; }
        public string DEPOTTYPE { get; set; }
        public Nullable<int> DEPOTID { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<System.DateTime> TRANSDATE { get; set; }
    }
}
