//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_TBOBBINSTOCK
    {
        public int COMPANYID { get; set; }
        public int DOCUMENTTYPEID { get; set; }
        public string STOCKNO { get; set; }
        public string STOCKNAME { get; set; }
        public string STOCKTYPE { get; set; }
        public int STOCKID { get; set; }
        public Nullable<short> BOBINKOLI { get; set; }
    }
}
