//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_TDSENDINGPLANS
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int ITEMNO { get; set; }
        public int ORDERID { get; set; }
        public Nullable<System.DateTime> STIME { get; set; }
        public Nullable<double> SENDMT { get; set; }
        public Nullable<int> WEEKNUM { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
    }
}
