//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_TDJOBORDERS
    {
        public int COMPANYID { get; set; }
        public int CPERIODID { get; set; }
        public int JOBORDERID { get; set; }
        public string JOBORDERNO { get; set; }
        public Nullable<System.DateTime> TRANSDATE { get; set; }
        public Nullable<bool> APPLYST { get; set; }
        public Nullable<bool> APPLYSTCOZGU { get; set; }
        public Nullable<bool> STOCKAPPLYST { get; set; }
        public Nullable<bool> STOCKAPPLYSTCOZGU { get; set; }
        public Nullable<bool> BLOCKST { get; set; }
        public Nullable<bool> BLOCKSTCOZGU { get; set; }
        public Nullable<bool> FASONST { get; set; }
        public Nullable<bool> FASONSTCOZGU { get; set; }
        public Nullable<int> ORDERID { get; set; }
        public Nullable<int> ORDERITEMID { get; set; }
        public string DESENNO { get; set; }
        public string KALITE { get; set; }
        public string VARYANT { get; set; }
        public string SIPNO { get; set; }
        public Nullable<int> DSGNID { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public string LOOMTYPENAME { get; set; }
        public Nullable<int> LOOMTYPE { get; set; }
        public Nullable<int> LOOMID { get; set; }
        public Nullable<int> RAWWDTH { get; set; }
        public Nullable<int> ROOLNUM { get; set; }
        public string PRODUCER { get; set; }
        public string DESCRIPTION { get; set; }
        public string UPWRPTENS { get; set; }
        public string DOWNWRPTENS { get; set; }
        public string WFTDENSITY { get; set; }
    }
}
