//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_ACTRECONCILEITEM
    {
        public int ACTRECONCILEITEM_SIRKETID { get; set; }
        public int ACTRECONCILEITEM_DONEMID { get; set; }
        public int ACTRECONCILEITEM_ACTRECONCILEID { get; set; }
        public int ACTRECONCILEITEM_PARCANO { get; set; }
        public string ACTRECONCILEITEM_CARINO { get; set; }
        public string ACTRECONCILEITEM_CARIADI { get; set; }
        public string ACTRECONCILEITEM_CARITIPI { get; set; }
        public string ACTRECONCILEITEM_VERGINO { get; set; }
        public string ACTRECONCILEITEM_TCNO { get; set; }
        public string ACTRECONCILEITEM_YETKILIADI { get; set; }
        public string ACTRECONCILEITEM_TELEFON1 { get; set; }
        public string ACTRECONCILEITEM_TELEFON2 { get; set; }
        public string ACTRECONCILEITEM_FAX { get; set; }
        public Nullable<int> ACTRECONCILEITEM_CARIID { get; set; }
        public string ACTRECONCILEITEM_ACTCURRCODE { get; set; }
        public Nullable<decimal> ACTRECONCILEITEM_TRANSFEROR { get; set; }
        public string ACTRECONCILEITEM_TRANSFERORREMTYPENAME { get; set; }
        public Nullable<short> ACTRECONCILEITEM_TRANSFERORREMTYPE { get; set; }
        public Nullable<decimal> ACTRECONCILEITEM_DOVIZBORC { get; set; }
        public Nullable<decimal> ACTRECONCILEITEM_DOVIZALACAK { get; set; }
        public Nullable<decimal> ACTRECONCILEITEM_DOVIZBAKIYE { get; set; }
        public string ACTRECONCILEITEM_TRANSCURRCODE { get; set; }
        public string ACTRECONCILEITEM_MMESSAGE { get; set; }
        public string ACTRECONCILEITEM_MFILEPATH { get; set; }
        public Nullable<short> ACTRECONCILEITEM_RECONCILE_STATUS { get; set; }
        public Nullable<short> ACTRECONCILEITEM_MARKED { get; set; }
        public string ACTRECONCILEITEM_SENDEDMAILS { get; set; }
        public Nullable<bool> ACTRECONCILEITEM_SENDED { get; set; }
        public Nullable<int> ACTRECONCILEITEM_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> ACTRECONCILEITEM_KAYITTARIHI { get; set; }
        public Nullable<int> ACTRECONCILEITEM_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> ACTRECONCILEITEM_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> ACTRECONCILEITEM_UYARIID { get; set; }
    }
}
