//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_ACTSTOCKCONT
    {
        public int ACTSTOCKCONT_SIRKETID { get; set; }
        public string ACTSTOCKCONT_CARINO { get; set; }
        public string ACTSTOCKCONT_CARIADI { get; set; }
        public string ACTSTOCKCONT_CARITIPI { get; set; }
        public int ACTSTOCKCONT_CARIID { get; set; }
        public string ACTSTOCKCONT_STOKNO { get; set; }
        public string ACTSTOCKCONT_STOKADI { get; set; }
        public string ACTSTOCKCONT_STOKTIPI { get; set; }
        public int ACTSTOCKCONT_STOKID { get; set; }
        public string ACTSTOCKCONT_NITELIKADI { get; set; }
        public int ACTSTOCKCONT_NITELIKID { get; set; }
        public System.DateTime ACTSTOCKCONT_SOZLESMEBASLANGICTARIHI { get; set; }
        public Nullable<System.DateTime> ACTSTOCKCONT_SOZLESMEBITISTARIHI { get; set; }
        public string ACTSTOCKCONT_DOVIZ { get; set; }
        public Nullable<double> ACTSTOCKCONT_DOVIZKURU { get; set; }
        public Nullable<int> ACTSTOCKCONT_SEVKGUNU { get; set; }
        public Nullable<decimal> ACTSTOCKCONT_SAGLANMASURESI { get; set; }
        public string ACTSTOCKCONT_PROVIDEDURATIONTYPENAME { get; set; }
        public Nullable<int> ACTSTOCKCONT_SAGLANMASURETIPI { get; set; }
        public Nullable<double> ACTSTOCKCONT_INDIRIMO1 { get; set; }
        public Nullable<double> ACTSTOCKCONT_INDIRIMO2 { get; set; }
        public Nullable<double> ACTSTOCKCONT_INDIRIMO3 { get; set; }
        public Nullable<double> ACTSTOCKCONT_DISCOUNT4 { get; set; }
        public Nullable<double> ACTSTOCKCONT_DISCOUNT5 { get; set; }
        public Nullable<double> ACTSTOCKCONT_DISCOUNT6 { get; set; }
        public Nullable<int> ACTSTOCKCONT_PRIORTY { get; set; }
        public Nullable<int> ACTSTOCKCONT_NOTLARID { get; set; }
        public Nullable<double> ACTSTOCKCONT_FIYAT { get; set; }
        public string ACTSTOCKCONT_STOKKODCARI { get; set; }
        public Nullable<short> ACTSTOCKCONT_STKFIYATTIPID { get; set; }
        public string ACTSTOCKCONT_PAKETADI { get; set; }
        public Nullable<short> ACTSTOCKCONT_STOKPAKETID { get; set; }
        public string ACTSTOCKCONT_OZELKOD1 { get; set; }
        public string ACTSTOCKCONT_OZELKOD2 { get; set; }
        public string ACTSTOCKCONT_OZELKOD3 { get; set; }
        public string ACTSTOCKCONT_OZELKOD4 { get; set; }
        public string ACTSTOCKCONT_REZERVEC1 { get; set; }
        public string ACTSTOCKCONT_REZERVEC2 { get; set; }
        public string ACTSTOCKCONT_REZERVEC3 { get; set; }
        public string ACTSTOCKCONT_REZERVEC4 { get; set; }
        public string ACTSTOCKCONT_REZERVEC5 { get; set; }
        public Nullable<int> ACTSTOCKCONT_PAKETMIKTAR { get; set; }
        public Nullable<short> ACTSTOCKCONT_ODEMEGUNU { get; set; }
        public Nullable<short> ACTSTOCKCONT_PAYMENTPERIOD { get; set; }
        public string ACTSTOCKCONT_PAYMENTPERIODTYPENAME { get; set; }
        public Nullable<short> ACTSTOCKCONT_PAYMENTPERIODTYPE { get; set; }
        public Nullable<short> ACTSTOCKCONT_PAYMENTPERIODITEM { get; set; }
        public Nullable<short> ACTSTOCKCONT_PAYMENTPERIODDAY { get; set; }
        public Nullable<int> ACTSTOCKCONT_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> ACTSTOCKCONT_KAYITTARIHI { get; set; }
        public Nullable<int> ACTSTOCKCONT_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> ACTSTOCKCONT_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> ACTSTOCKCONT_UYARIID { get; set; }
    }
}
