//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_ANDONDEFINITIONITEM
    {
        public int ANDONDEFINITIONITEM_ID { get; set; }
        public Nullable<int> ANDONDEFINITIONITEM_AndonDefinationId { get; set; }
        public Nullable<int> ANDONDEFINITIONITEM_AndonDesignId { get; set; }
        public Nullable<int> ANDONDEFINITIONITEM_DisplayOrder { get; set; }
        public Nullable<int> ANDONDEFINITIONITEM_DisplayDuration { get; set; }
        public string ANDONDEFINITIONITEM_SqlResult { get; set; }
        public string ANDONDEFINITIONITEM_DisplaySQL { get; set; }
        public Nullable<int> ANDONDEFINITIONITEM_MasterCount { get; set; }
        public Nullable<int> ANDONDEFINITIONITEM_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> ANDONDEFINITIONITEM_KAYITTARIHI { get; set; }
        public Nullable<int> ANDONDEFINITIONITEM_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> ANDONDEFINITIONITEM_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> ANDONDEFINITIONITEM_UYARIID { get; set; }
    }
}
