//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_ACTPICTURE
    {
        public int ACTPICTURE_SIRKETID { get; set; }
        public string ACTPICTURE_CARINO { get; set; }
        public string ACTPICTURE_CARIADI { get; set; }
        public string ACTPICTURE_CARITIPI { get; set; }
        public int ACTPICTURE_CARIID { get; set; }
        public short ACTPICTURE_PARCANO { get; set; }
        public byte[] ACTPICTURE_ACTPICTURE { get; set; }
        public Nullable<bool> ACTPICTURE_UZAT { get; set; }
        public string ACTPICTURE_GRUPKODU { get; set; }
        public Nullable<int> ACTPICTURE_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> ACTPICTURE_KAYITTARIHI { get; set; }
        public Nullable<int> ACTPICTURE_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> ACTPICTURE_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> ACTPICTURE_UYARIID { get; set; }
    }
}
