//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_ACTEVENTS
    {
        public int ACTEVENTS_SIRKETID { get; set; }
        public string ACTEVENTS_CARINO { get; set; }
        public string ACTEVENTS_CARIADI { get; set; }
        public string ACTEVENTS_CARITIPI { get; set; }
        public int ACTEVENTS_CARIID { get; set; }
        public int ACTEVENTS_ACTEVENTSID { get; set; }
        public Nullable<int> ACTEVENTS_TRANST { get; set; }
        public Nullable<System.DateTime> ACTEVENTS_TARIH { get; set; }
        public string ACTEVENTS_EVENT { get; set; }
        public Nullable<System.DateTime> ACTEVENTS_EVENTDATE { get; set; }
        public string ACTEVENTS_ACIKLAMA1 { get; set; }
        public string ACTEVENTS_ACIKLAMA2 { get; set; }
        public string ACTEVENTS_ACIKLAMA3 { get; set; }
        public Nullable<System.DateTime> ACTEVENTS_ALERTDATE { get; set; }
        public string ACTEVENTS_PERSONELNO { get; set; }
        public string ACTEVENTS_PERSONELADI { get; set; }
        public string ACTEVENTS_PERSONELTIPI { get; set; }
        public Nullable<int> ACTEVENTS_PERSONELID { get; set; }
        public Nullable<int> ACTEVENTS_PROCESS { get; set; }
        public Nullable<int> ACTEVENTS_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> ACTEVENTS_KAYITTARIHI { get; set; }
        public Nullable<int> ACTEVENTS_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> ACTEVENTS_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> ACTEVENTS_UYARIID { get; set; }
    }
}
