//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_ACTSTOCKPRICE
    {
        public int ACTSTOCKPRICE_SIRKETID { get; set; }
        public int ACTSTOCKPRICE_ACTSTOCKPRICEID { get; set; }
        public string ACTSTOCKPRICE_CARINO { get; set; }
        public string ACTSTOCKPRICE_CARIADI { get; set; }
        public string ACTSTOCKPRICE_CARITIPI { get; set; }
        public Nullable<int> ACTSTOCKPRICE_CARIID { get; set; }
        public string ACTSTOCKPRICE_ACIKLAMA { get; set; }
        public Nullable<System.DateTime> ACTSTOCKPRICE_TARIH { get; set; }
        public Nullable<System.DateTime> ACTSTOCKPRICE_BEGINDATE { get; set; }
        public Nullable<System.DateTime> ACTSTOCKPRICE_BITISTARIHI { get; set; }
        public string ACTSTOCKPRICE_GRUPKODU { get; set; }
        public string ACTSTOCKPRICE_OZELKOD1 { get; set; }
        public string ACTSTOCKPRICE_OZELKOD2 { get; set; }
        public string ACTSTOCKPRICE_STATUSNAME { get; set; }
        public Nullable<short> ACTSTOCKPRICE_DURUM { get; set; }
        public Nullable<int> ACTSTOCKPRICE_SUBEID { get; set; }
        public Nullable<int> ACTSTOCKPRICE_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> ACTSTOCKPRICE_KAYITTARIHI { get; set; }
        public Nullable<int> ACTSTOCKPRICE_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> ACTSTOCKPRICE_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> ACTSTOCKPRICE_UYARIID { get; set; }
    }
}
