//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_ASORTI
    {
        public int ASORTI_SIRKETID { get; set; }
        public int ASORTI_ASORTIID { get; set; }
        public string ASORTI_ASORTINO { get; set; }
        public string ASORTI_ACIKLAMA { get; set; }
        public string ASORTI_STOKNO { get; set; }
        public string ASORTI_STOKADI { get; set; }
        public string ASORTI_STOKTIPI { get; set; }
        public Nullable<int> ASORTI_STOKID { get; set; }
        public Nullable<int> ASORTI_MATRIXID { get; set; }
        public string ASORTI_STATUSNAME { get; set; }
        public Nullable<int> ASORTI_DURUM { get; set; }
        public string ASORTI_BARKOD { get; set; }
        public Nullable<int> ASORTI_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> ASORTI_KAYITTARIHI { get; set; }
        public Nullable<int> ASORTI_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> ASORTI_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> ASORTI_UYARIID { get; set; }
    }
}
