//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_AUTUSERSROLES
    {
        public int AUTUSERSROLES_SIRKETID { get; set; }
        public int AUTUSERSROLES_KULLANICIID { get; set; }
        public int AUTUSERSROLES_ROLID { get; set; }
        public Nullable<int> AUTUSERSROLES_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> AUTUSERSROLES_KAYITTARIHI { get; set; }
        public Nullable<int> AUTUSERSROLES_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> AUTUSERSROLES_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> AUTUSERSROLES_UYARIID { get; set; }
    }
}
