//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_BANKCREDITPER
    {
        public int BANKCREDITPER_SIRKETID { get; set; }
        public string BANKCREDITPER_BANKANO { get; set; }
        public string BANKCREDITPER_BANKAADI { get; set; }
        public string BANKCREDITPER_BANKATIPI { get; set; }
        public int BANKCREDITPER_BANKAID { get; set; }
        public short BANKCREDITPER_PARCANO { get; set; }
        public Nullable<System.DateTime> BANKCREDITPER_PAYMENTDATE { get; set; }
        public Nullable<int> BANKCREDITPER_BANKRECEIPTID { get; set; }
        public Nullable<double> BANKCREDITPER_DOVIZTUTAR { get; set; }
        public string BANKCREDITPER_DOVIZ { get; set; }
        public Nullable<double> BANKCREDITPER_TUTAR { get; set; }
        public Nullable<double> BANKCREDITPER_INTERESTTOTAL { get; set; }
        public Nullable<double> BANKCREDITPER_BAKIYE { get; set; }
        public Nullable<double> BANKCREDITPER_REMCURRTOTAL { get; set; }
        public Nullable<double> BANKCREDITPER_RATEKKDF { get; set; }
        public Nullable<double> BANKCREDITPER_RATEBSMV { get; set; }
        public Nullable<double> BANKCREDITPER_TOTALKKDF { get; set; }
        public Nullable<double> BANKCREDITPER_TOTALBSMV { get; set; }
        public Nullable<double> BANKCREDITPER_CREDITRATE { get; set; }
        public string BANKCREDITPER_ACIKLAMA { get; set; }
        public string BANKCREDITPER_STATUSNAME { get; set; }
        public Nullable<short> BANKCREDITPER_DURUM { get; set; }
        public Nullable<int> BANKCREDITPER_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> BANKCREDITPER_KAYITTARIHI { get; set; }
        public Nullable<int> BANKCREDITPER_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> BANKCREDITPER_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> BANKCREDITPER_UYARIID { get; set; }
    }
}
