//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_BREFAKATDETAY
    {
        public int BREFAKATDETAY_SIRKETID { get; set; }
        public int BREFAKATDETAY_DONEMID { get; set; }
        public int BREFAKATDETAY_REFAKATID { get; set; }
        public short BREFAKATDETAY_PARCANO { get; set; }
        public int BREFAKATDETAY_ISLEMTIPID { get; set; }
        public Nullable<int> BREFAKATDETAY_MAKINATIPID { get; set; }
        public string BREFAKATDETAY_ACIKLAMA1 { get; set; }
        public string BREFAKATDETAY_ACIKLAMA2 { get; set; }
        public string BREFAKATDETAY_ACIKLAMA3 { get; set; }
    }
}
