//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_CRMINTERVIEW
    {
        public int CRMINTERVIEW_SIRKETID { get; set; }
        public int CRMINTERVIEW_CRMINTERVIEWID { get; set; }
        public string CRMINTERVIEW_CRMINTERVIEWNO { get; set; }
        public string CRMINTERVIEW_INTERVIEWTYPENAME { get; set; }
        public Nullable<int> CRMINTERVIEW_INTERVIEWTYPE { get; set; }
        public string CRMINTERVIEW_ASTATUSNAME { get; set; }
        public Nullable<int> CRMINTERVIEW_ASTATUS { get; set; }
        public string CRMINTERVIEW_CRMCONTACTSFULLNAME { get; set; }
        public Nullable<int> CRMINTERVIEW_CARIID { get; set; }
        public string CRMINTERVIEW_CARINO { get; set; }
        public string CRMINTERVIEW_CARIADI { get; set; }
        public Nullable<int> CRMINTERVIEW_CRMCONTACTSID { get; set; }
        public Nullable<System.DateTime> CRMINTERVIEW_INTERVIEWDATE { get; set; }
        public Nullable<System.DateTime> CRMINTERVIEW_INTERVIEWTIME { get; set; }
        public Nullable<System.DateTime> CRMINTERVIEW_INTERVIEWENDDATE { get; set; }
        public Nullable<System.DateTime> CRMINTERVIEW_INTERVIEWENDTIME { get; set; }
        public string CRMINTERVIEW_PERSONELNO { get; set; }
        public string CRMINTERVIEW_PERSONELADI { get; set; }
        public string CRMINTERVIEW_PERSONELTIPI { get; set; }
        public Nullable<int> CRMINTERVIEW_PERSONELID { get; set; }
        public string CRMINTERVIEW_SUBJECT { get; set; }
        public string CRMINTERVIEW_ACIKLAMA { get; set; }
        public string CRMINTERVIEW_NOTLAR { get; set; }
        public string CRMINTERVIEW_GRUPKODU { get; set; }
        public string CRMINTERVIEW_OZELKOD1 { get; set; }
        public string CRMINTERVIEW_OZELKOD2 { get; set; }
        public string CRMINTERVIEW_RESFIELDC1 { get; set; }
        public string CRMINTERVIEW_RESFIELDC2 { get; set; }
        public string CRMINTERVIEW_RESFIELDC3 { get; set; }
        public string CRMINTERVIEW_RESFIELDC4 { get; set; }
        public string CRMINTERVIEW_RESFIELDC5 { get; set; }
        public Nullable<bool> CRMINTERVIEW_RESFIELDB1 { get; set; }
        public Nullable<bool> CRMINTERVIEW_RESFIELDB2 { get; set; }
        public Nullable<bool> CRMINTERVIEW_RESFIELDB3 { get; set; }
        public Nullable<bool> CRMINTERVIEW_RESFIELDB4 { get; set; }
        public Nullable<bool> CRMINTERVIEW_RESFIELDB5 { get; set; }
        public Nullable<int> CRMINTERVIEW_CRMOFFERSTATUS { get; set; }
        public Nullable<int> CRMINTERVIEW_ACTCONTACTID { get; set; }
        public Nullable<int> CRMINTERVIEW_CRMACTIVITYID { get; set; }
        public string CRMINTERVIEW_CRMRECEIPTNO { get; set; }
        public Nullable<int> CRMINTERVIEW_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> CRMINTERVIEW_KAYITTARIHI { get; set; }
        public Nullable<int> CRMINTERVIEW_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> CRMINTERVIEW_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> CRMINTERVIEW_UYARIID { get; set; }
    }
}
