//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_CRMINTERVIEWPRODUCT
    {
        public int CRMINTERVIEWPRODUCT_SIRKETID { get; set; }
        public int CRMINTERVIEWPRODUCT_CRMINTERVIEWID { get; set; }
        public int CRMINTERVIEWPRODUCT_PARCANO { get; set; }
        public string CRMINTERVIEWPRODUCT_STOKNO { get; set; }
        public string CRMINTERVIEWPRODUCT_STOKADI { get; set; }
        public string CRMINTERVIEWPRODUCT_STOKTIPI { get; set; }
        public Nullable<int> CRMINTERVIEWPRODUCT_STOKID { get; set; }
        public Nullable<double> CRMINTERVIEWPRODUCT_MIKTAR { get; set; }
        public string CRMINTERVIEWPRODUCT_ACIKLAMA { get; set; }
        public string CRMINTERVIEWPRODUCT_DOVIZ { get; set; }
        public Nullable<double> CRMINTERVIEWPRODUCT_DOVIZKURU { get; set; }
        public Nullable<double> CRMINTERVIEWPRODUCT_DOVIZTUTAR { get; set; }
    }
}
