//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_CSGIRCIKBASLIK
    {
        public int CSGIRCIKBASLIK_SIRKETID { get; set; }
        public int CSGIRCIKBASLIK_DONEMID { get; set; }
        public int CSGIRCIKBASLIK_FISID { get; set; }
        public string CSGIRCIKBASLIK_ISLEMTIPIADI { get; set; }
        public Nullable<short> CSGIRCIKBASLIK_ISLEMTIPI { get; set; }
        public string CSGIRCIKBASLIK_FISNO { get; set; }
        public Nullable<System.DateTime> CSGIRCIKBASLIK_TARIH { get; set; }
        public string CSGIRCIKBASLIK_GRUPKODU { get; set; }
        public string CSGIRCIKBASLIK_OZELKOD1 { get; set; }
        public string CSGIRCIKBASLIK_OZELKOD2 { get; set; }
        public string CSGIRCIKBASLIK_TRANSCODE { get; set; }
        public string CSGIRCIKBASLIK_PERSONELNO { get; set; }
        public string CSGIRCIKBASLIK_PERSONELADI { get; set; }
        public string CSGIRCIKBASLIK_PERSONELTIPI { get; set; }
        public Nullable<int> CSGIRCIKBASLIK_PERSONELID { get; set; }
        public string CSGIRCIKBASLIK_STATUSNAME { get; set; }
        public Nullable<short> CSGIRCIKBASLIK_DURUM { get; set; }
        public Nullable<int> CSGIRCIKBASLIK_NOTEID { get; set; }
        public Nullable<System.DateTime> CSGIRCIKBASLIK_IPTALTARIHI { get; set; }
        public string CSGIRCIKBASLIK_ACIKLAMA { get; set; }
        public string CSGIRCIKBASLIK_DOKUMANNO { get; set; }
        public Nullable<decimal> CSGIRCIKBASLIK_TUTAR { get; set; }
        public string CSGIRCIKBASLIK_DOVIZ { get; set; }
        public Nullable<System.DateTime> CSGIRCIKBASLIK_DOVIZTARIHI { get; set; }
        public Nullable<double> CSGIRCIKBASLIK_DOVIZKUR { get; set; }
        public Nullable<double> CSGIRCIKBASLIK_DOVIZTUTAR { get; set; }
        public string CSGIRCIKBASLIK_HARDOVIZI { get; set; }
        public Nullable<System.DateTime> CSGIRCIKBASLIK_HARDOVIZTARIHI { get; set; }
        public Nullable<double> CSGIRCIKBASLIK_HARDOVIZKUR { get; set; }
        public Nullable<decimal> CSGIRCIKBASLIK_DOVIZHAR { get; set; }
        public string CSGIRCIKBASLIK_CARINO { get; set; }
        public string CSGIRCIKBASLIK_CARIADI { get; set; }
        public string CSGIRCIKBASLIK_CARITIPI { get; set; }
        public Nullable<int> CSGIRCIKBASLIK_CARIID { get; set; }
        public string CSGIRCIKBASLIK_KASANO { get; set; }
        public string CSGIRCIKBASLIK_KASAADI { get; set; }
        public string CSGIRCIKBASLIK_KASATIPI { get; set; }
        public Nullable<int> CSGIRCIKBASLIK_KASAID { get; set; }
        public Nullable<bool> CSGIRCIKBASLIK_MUHASEBEKONTROL { get; set; }
        public Nullable<bool> CSGIRCIKBASLIK_ERA { get; set; }
        public Nullable<decimal> CSGIRCIKBASLIK_VADEFARKI { get; set; }
        public Nullable<System.DateTime> CSGIRCIKBASLIK_ORTALAMOPSIYON { get; set; }
        public string CSGIRCIKBASLIK_PROJENO { get; set; }
        public string CSGIRCIKBASLIK_PROJEADI { get; set; }
        public Nullable<int> CSGIRCIKBASLIK_PROJEID { get; set; }
        public string CSGIRCIKBASLIK_MASRAFYERKODU { get; set; }
        public string CSGIRCIKBASLIK_MASRAFYERADI { get; set; }
        public Nullable<int> CSGIRCIKBASLIK_MASRAFYERREF { get; set; }
        public string CSGIRCIKBASLIK_DOVIZHARTIPIADI { get; set; }
        public Nullable<bool> CSGIRCIKBASLIK_DOVIZHARTIPI { get; set; }
        public string CSGIRCIKBASLIK_BANKANO { get; set; }
        public string CSGIRCIKBASLIK_BANKAADI { get; set; }
        public string CSGIRCIKBASLIK_BANKATIPI { get; set; }
        public Nullable<int> CSGIRCIKBASLIK_BANKAID { get; set; }
        public string CSGIRCIKBASLIK_RECEIPTTYPENAME { get; set; }
        public Nullable<int> CSGIRCIKBASLIK_RECEIPTTYPE { get; set; }
        public Nullable<int> CSGIRCIKBASLIK_SID { get; set; }
        public Nullable<int> CSGIRCIKBASLIK_ACCRECEIPTID { get; set; }
        public Nullable<int> CSGIRCIKBASLIK_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> CSGIRCIKBASLIK_KAYITTARIHI { get; set; }
        public Nullable<int> CSGIRCIKBASLIK_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> CSGIRCIKBASLIK_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> CSGIRCIKBASLIK_UYARIID { get; set; }
    }
}
