//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_COMTRANSIDVALUE
    {
        public string COMTRANSIDVALUE_TBLNAME { get; set; }
        public string COMTRANSIDVALUE_FLDNAME { get; set; }
        public int COMTRANSIDVALUE_SENDCOMPANYID { get; set; }
        public int COMTRANSIDVALUE_SENDID { get; set; }
        public int COMTRANSIDVALUE_TRANSFERCOMPANYID { get; set; }
        public int COMTRANSIDVALUE_TRANSFERID { get; set; }
        public string COMTRANSIDVALUE_ISLEMTIPIADI { get; set; }
        public short COMTRANSIDVALUE_ISLEMTIPI { get; set; }
    }
}
