//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_CSRECEIPT
    {
        public int CSRECEIPT_SIRKETID { get; set; }
        public int CSRECEIPT_DONEMID { get; set; }
        public int CSRECEIPT_FISID { get; set; }
        public string CSRECEIPT_ISLEMTIPIADI { get; set; }
        public Nullable<short> CSRECEIPT_ISLEMTIPI { get; set; }
        public string CSRECEIPT_FISNO { get; set; }
        public Nullable<System.DateTime> CSRECEIPT_TARIH { get; set; }
        public string CSRECEIPT_GRUPKODU { get; set; }
        public string CSRECEIPT_OZELKOD1 { get; set; }
        public string CSRECEIPT_OZELKOD2 { get; set; }
        public string CSRECEIPT_TRANSCODE { get; set; }
        public string CSRECEIPT_PERSONELNO { get; set; }
        public string CSRECEIPT_PERSONELADI { get; set; }
        public string CSRECEIPT_PERSONELTIPI { get; set; }
        public Nullable<int> CSRECEIPT_PERSONELID { get; set; }
        public string CSRECEIPT_STATUSNAME { get; set; }
        public Nullable<short> CSRECEIPT_DURUM { get; set; }
        public Nullable<int> CSRECEIPT_NOTEID { get; set; }
        public Nullable<System.DateTime> CSRECEIPT_IPTALTARIHI { get; set; }
        public string CSRECEIPT_ACIKLAMA { get; set; }
        public string CSRECEIPT_DOKUMANNO { get; set; }
        public Nullable<decimal> CSRECEIPT_TUTAR { get; set; }
        public string CSRECEIPT_DOVIZ { get; set; }
        public Nullable<System.DateTime> CSRECEIPT_DOVIZTARIHI { get; set; }
        public Nullable<double> CSRECEIPT_DOVIZKUR { get; set; }
        public Nullable<double> CSRECEIPT_DOVIZTUTAR { get; set; }
        public string CSRECEIPT_HARDOVIZI { get; set; }
        public Nullable<System.DateTime> CSRECEIPT_HARDOVIZTARIHI { get; set; }
        public Nullable<double> CSRECEIPT_HARDOVIZKUR { get; set; }
        public Nullable<decimal> CSRECEIPT_DOVIZHAR { get; set; }
        public string CSRECEIPT_CARINO { get; set; }
        public string CSRECEIPT_CARIADI { get; set; }
        public string CSRECEIPT_CARITIPI { get; set; }
        public Nullable<int> CSRECEIPT_CARIID { get; set; }
        public string CSRECEIPT_KASANO { get; set; }
        public string CSRECEIPT_KASAADI { get; set; }
        public string CSRECEIPT_KASATIPI { get; set; }
        public Nullable<int> CSRECEIPT_KASAID { get; set; }
        public Nullable<bool> CSRECEIPT_MUHASEBEKONTROL { get; set; }
        public Nullable<bool> CSRECEIPT_ERA { get; set; }
        public Nullable<decimal> CSRECEIPT_VADEFARKI { get; set; }
        public Nullable<System.DateTime> CSRECEIPT_ORTALAMOPSIYON { get; set; }
        public string CSRECEIPT_PROJENO { get; set; }
        public string CSRECEIPT_PROJEADI { get; set; }
        public Nullable<int> CSRECEIPT_PROJEID { get; set; }
        public string CSRECEIPT_MASRAFYERKODU { get; set; }
        public string CSRECEIPT_MASRAFYERADI { get; set; }
        public Nullable<int> CSRECEIPT_MASRAFYERREF { get; set; }
        public string CSRECEIPT_DOVIZHARTIPIADI { get; set; }
        public Nullable<bool> CSRECEIPT_DOVIZHARTIPI { get; set; }
        public string CSRECEIPT_BANKANO { get; set; }
        public string CSRECEIPT_BANKAADI { get; set; }
        public string CSRECEIPT_BANKATIPI { get; set; }
        public Nullable<int> CSRECEIPT_BANKAID { get; set; }
        public string CSRECEIPT_RECEIPTTYPENAME { get; set; }
        public Nullable<int> CSRECEIPT_RECEIPTTYPE { get; set; }
        public Nullable<int> CSRECEIPT_SID { get; set; }
        public Nullable<int> CSRECEIPT_ACCRECEIPTID { get; set; }
        public Nullable<int> CSRECEIPT_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> CSRECEIPT_KAYITTARIHI { get; set; }
        public Nullable<int> CSRECEIPT_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> CSRECEIPT_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> CSRECEIPT_UYARIID { get; set; }
    }
}
