//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_CRMPOOLGRP
    {
        public int CRMPOOLGRP_SIRKETID { get; set; }
        public int CRMPOOLGRP_CRMPOOLGRPID { get; set; }
        public string CRMPOOLGRP_CRMPOOLGRPNO { get; set; }
        public string CRMPOOLGRP_CRMPOOLGRPNAME { get; set; }
        public string CRMPOOLGRP_STATUSNAME { get; set; }
        public Nullable<int> CRMPOOLGRP_DURUM { get; set; }
        public string CRMPOOLGRP_PERSONELNO { get; set; }
        public string CRMPOOLGRP_PERSONELADI { get; set; }
        public string CRMPOOLGRP_PERSONELTIPI { get; set; }
        public Nullable<int> CRMPOOLGRP_PERSONELID { get; set; }
        public string CRMPOOLGRP_GRUPKODU { get; set; }
        public string CRMPOOLGRP_OZELKOD1 { get; set; }
        public string CRMPOOLGRP_OZELKOD2 { get; set; }
        public string CRMPOOLGRP_ACIKLAMA { get; set; }
        public string CRMPOOLGRP_NOTLAR { get; set; }
        public Nullable<int> CRMPOOLGRP_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> CRMPOOLGRP_KAYITTARIHI { get; set; }
        public Nullable<int> CRMPOOLGRP_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> CRMPOOLGRP_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> CRMPOOLGRP_UYARIID { get; set; }
    }
}
