//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_CARIFISBASLIK
    {
        public int CARIFISBASLIK_SIRKETID { get; set; }
        public int CARIFISBASLIK_DONEMID { get; set; }
        public int CARIFISBASLIK_FISID { get; set; }
        public string CARIFISBASLIK_ISLEMTIPIADI { get; set; }
        public Nullable<short> CARIFISBASLIK_ISLEMTIPI { get; set; }
        public string CARIFISBASLIK_FISNO { get; set; }
        public Nullable<System.DateTime> CARIFISBASLIK_TARIH { get; set; }
        public string CARIFISBASLIK_GRUPKODU { get; set; }
        public string CARIFISBASLIK_OZELKOD1 { get; set; }
        public string CARIFISBASLIK_OZELKOD2 { get; set; }
        public string CARIFISBASLIK_TRANSCODE { get; set; }
        public string CARIFISBASLIK_PERSONELNO { get; set; }
        public string CARIFISBASLIK_PERSONELADI { get; set; }
        public string CARIFISBASLIK_PERSONELTIPI { get; set; }
        public Nullable<int> CARIFISBASLIK_PERSONELID { get; set; }
        public string CARIFISBASLIK_STATUSNAME { get; set; }
        public Nullable<short> CARIFISBASLIK_DURUM { get; set; }
        public Nullable<int> CARIFISBASLIK_NOTEID { get; set; }
        public Nullable<System.DateTime> CARIFISBASLIK_IPTALTARIHI { get; set; }
        public string CARIFISBASLIK_ACIKLAMA { get; set; }
        public string CARIFISBASLIK_DOKUMANNO { get; set; }
        public Nullable<decimal> CARIFISBASLIK_TUTAR { get; set; }
        public string CARIFISBASLIK_DOVIZ { get; set; }
        public Nullable<System.DateTime> CARIFISBASLIK_DOVIZTARIHI { get; set; }
        public Nullable<double> CARIFISBASLIK_DOVIZKUR { get; set; }
        public Nullable<double> CARIFISBASLIK_DOVIZTUTAR { get; set; }
        public string CARIFISBASLIK_PROJENO { get; set; }
        public string CARIFISBASLIK_PROJEADI { get; set; }
        public Nullable<int> CARIFISBASLIK_PROJEID { get; set; }
        public string CARIFISBASLIK_MASRAFYERKODU { get; set; }
        public string CARIFISBASLIK_MASRAFYERADI { get; set; }
        public Nullable<int> CARIFISBASLIK_MASRAFYERREF { get; set; }
        public string CARIFISBASLIK_CARINO { get; set; }
        public string CARIFISBASLIK_CARIADI { get; set; }
        public string CARIFISBASLIK_CARITIPI { get; set; }
        public Nullable<int> CARIFISBASLIK_CARIID { get; set; }
        public string CARIFISBASLIK_KASANO { get; set; }
        public string CARIFISBASLIK_KASAADI { get; set; }
        public string CARIFISBASLIK_KASATIPI { get; set; }
        public Nullable<int> CARIFISBASLIK_KASAID { get; set; }
        public string CARIFISBASLIK_GGNO { get; set; }
        public string CARIFISBASLIK_GGADI { get; set; }
        public string CARIFISBASLIK_GGTIPI { get; set; }
        public Nullable<int> CARIFISBASLIK_GGID { get; set; }
        public string CARIFISBASLIK_BANKANO { get; set; }
        public string CARIFISBASLIK_BANKAADI { get; set; }
        public string CARIFISBASLIK_BANKATIPI { get; set; }
        public Nullable<int> CARIFISBASLIK_BANKAID { get; set; }
        public string CARIFISBASLIK_DOVIZHARTIPIADI { get; set; }
        public Nullable<bool> CARIFISBASLIK_DOVIZHARTIPI { get; set; }
        public Nullable<bool> CARIFISBASLIK_MUHASEBEKONTROL { get; set; }
        public string CARIFISBASLIK_RECEIPTTYPENAME { get; set; }
        public Nullable<int> CARIFISBASLIK_RECEIPTTYPE { get; set; }
        public Nullable<int> CARIFISBASLIK_SID { get; set; }
        public Nullable<int> CARIFISBASLIK_ACCRECEIPTID { get; set; }
        public Nullable<bool> CARIFISBASLIK_SENDDOC { get; set; }
        public Nullable<int> CARIFISBASLIK_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> CARIFISBASLIK_KAYITTARIHI { get; set; }
        public Nullable<int> CARIFISBASLIK_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> CARIFISBASLIK_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> CARIFISBASLIK_UYARIID { get; set; }
    }
}
