//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_CRMPOOLITEM
    {
        public int CRMPOOLITEM_SIRKETID { get; set; }
        public int CRMPOOLITEM_CRMPOOLID { get; set; }
        public int CRMPOOLITEM_PARCANO { get; set; }
        public string CRMPOOLITEM_CRMPOOLDEFDESCRIPTION { get; set; }
        public Nullable<int> CRMPOOLITEM_CRMPOOLDEFID { get; set; }
        public Nullable<int> CRMPOOLITEM_CRMPOOLRATING { get; set; }
        public string CRMPOOLITEM_ACIKLAMA { get; set; }
    }
}
