//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_DCASLOTSHISTORY
    {
        public int DCASLOTSHISTORY_SIRKETID { get; set; }
        public int DCASLOTSHISTORY_FISID { get; set; }
        public string DCASLOTSHISTORY_ISISTASYONUNO { get; set; }
        public string DCASLOTSHISTORY_ISISTASYONUADI { get; set; }
        public string DCASLOTSHISTORY_ISISTASYONUTIPI { get; set; }
        public int DCASLOTSHISTORY_ISISTASYONUID { get; set; }
        public string DCASLOTSHISTORY_STOKNO { get; set; }
        public string DCASLOTSHISTORY_STOKADI { get; set; }
        public string DCASLOTSHISTORY_STOKTIPI { get; set; }
        public int DCASLOTSHISTORY_STOKID { get; set; }
        public string DCASLOTSHISTORY_NITELIKADI { get; set; }
        public int DCASLOTSHISTORY_NITELIKID { get; set; }
        public int DCASLOTSHISTORY_STOKLOTID { get; set; }
        public string DCASLOTSHISTORY_LOTNO { get; set; }
        public string DCASLOTSHISTORY_PARENTLOTNO { get; set; }
        public Nullable<double> DCASLOTSHISTORY_QREZERVE { get; set; }
        public Nullable<double> DCASLOTSHISTORY_QREZERVE2 { get; set; }
        public Nullable<double> DCASLOTSHISTORY_QREZERVE3 { get; set; }
        public Nullable<double> DCASLOTSHISTORY_QREZERVE4 { get; set; }
        public string DCASLOTSHISTORY_DEPONO { get; set; }
        public string DCASLOTSHISTORY_DEPOADI { get; set; }
        public string DCASLOTSHISTORY_DEPOTIPI { get; set; }
        public Nullable<int> DCASLOTSHISTORY_DEPOREF { get; set; }
        public Nullable<byte> DCASLOTSHISTORY_SECTION { get; set; }
        public Nullable<double> DCASLOTSHISTORY_GIRISMIKTARI { get; set; }
        public Nullable<double> DCASLOTSHISTORY_CIKISMIKTARI { get; set; }
        public Nullable<int> DCASLOTSHISTORY_SOURCEITEMREF { get; set; }
        public Nullable<int> DCASLOTSHISTORY_SOURCEINVENNO { get; set; }
        public Nullable<System.DateTime> DCASLOTSHISTORY_KAYITTARIHI { get; set; }
        public Nullable<int> DCASLOTSHISTORY_PARCANO { get; set; }
        public Nullable<bool> DCASLOTSHISTORY_LOTCHANGE { get; set; }
    }
}
