//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_DTEZDURBASLIK
    {
        public int DTEZDURBASLIK_SIRKETID { get; set; }
        public int DTEZDURBASLIK_DONEMID { get; set; }
        public int DTEZDURBASLIK_FISID { get; set; }
        public int DTEZDURBASLIK_TEZGAHID { get; set; }
        public Nullable<System.DateTime> DTEZDURBASLIK_KAYITTARIHI { get; set; }
        public Nullable<int> DTEZDURBASLIK_DSGNID { get; set; }
        public Nullable<int> DTEZDURBASLIK_DSGNPARENTID { get; set; }
        public Nullable<int> DTEZDURBASLIK_AWFTCOUNT { get; set; }
        public Nullable<int> DTEZDURBASLIK_BWFTCOUNT { get; set; }
        public Nullable<int> DTEZDURBASLIK_CWFTCOUNT { get; set; }
        public Nullable<int> DTEZDURBASLIK_AWRPBRCOUNT { get; set; }
        public Nullable<int> DTEZDURBASLIK_BWRPBRCOUNT { get; set; }
        public Nullable<int> DTEZDURBASLIK_CWRPBRCOUNT { get; set; }
        public Nullable<int> DTEZDURBASLIK_AWFTBRCOUNT { get; set; }
        public Nullable<int> DTEZDURBASLIK_BWFTBRCOUNT { get; set; }
        public Nullable<int> DTEZDURBASLIK_CWFTBRCOUNT { get; set; }
        public Nullable<int> DTEZDURBASLIK_ASUMPOSES { get; set; }
        public Nullable<int> DTEZDURBASLIK_BSUMPOSES { get; set; }
        public Nullable<int> DTEZDURBASLIK_CSUMPOSES { get; set; }
    }
}
