//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_DOKUMANLAR
    {
        public int DOKUMANLAR_SIRKETID { get; set; }
        public int DOKUMANLAR_DONEMID { get; set; }
        public short DOKUMANLAR_KAYNAK { get; set; }
        public int DOKUMANLAR_KAYNAKID { get; set; }
        public short DOKUMANLAR_PARCANO { get; set; }
        public string DOKUMANLAR_ACIKLAMA { get; set; }
        public byte[] DOKUMANLAR_DOKUMAN { get; set; }
        public Nullable<int> DOKUMANLAR_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> DOKUMANLAR_KAYITTARIHI { get; set; }
        public Nullable<int> DOKUMANLAR_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> DOKUMANLAR_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> DOKUMANLAR_UYARIID { get; set; }
    }
}
