//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_DKKONTROLBASLIK
    {
        public int DKKONTROLBASLIK_SIRKETID { get; set; }
        public int DKKONTROLBASLIK_DONEMID { get; set; }
        public int DKKONTROLBASLIK_TOPID { get; set; }
        public string DKKONTROLBASLIK_TOPNO { get; set; }
        public string DKKONTROLBASLIK_ROLLNO2 { get; set; }
        public Nullable<int> DKKONTROLBASLIK_ROLLNOITEM { get; set; }
        public Nullable<int> DKKONTROLBASLIK_ROLLNOPARENTID { get; set; }
        public string DKKONTROLBASLIK_QUALITYTYPENAME { get; set; }
        public Nullable<int> DKKONTROLBASLIK_QUALITYTYPE { get; set; }
        public int DKKONTROLBASLIK_ISEMIRID { get; set; }
        public Nullable<double> DKKONTROLBASLIK_TOPKG { get; set; }
        public Nullable<double> DKKONTROLBASLIK_TOPMT { get; set; }
        public Nullable<double> DKKONTROLBASLIK_HATAMT { get; set; }
        public Nullable<System.DateTime> DKKONTROLBASLIK_TARIH { get; set; }
        public Nullable<int> DKKONTROLBASLIK_QMACHINEID { get; set; }
        public string DKKONTROLBASLIK_QSHIFT { get; set; }
        public string DKKONTROLBASLIK_ACIKLAMA { get; set; }
        public string DKKONTROLBASLIK_TOPKALITE { get; set; }
        public string DKKONTROLBASLIK_LOOMTYPENAME { get; set; }
        public Nullable<int> DKKONTROLBASLIK_TEZGAHTIPI { get; set; }
        public Nullable<int> DKKONTROLBASLIK_TEZGAHID { get; set; }
        public Nullable<bool> DKKONTROLBASLIK_SEVKDURUM { get; set; }
        public Nullable<int> DKKONTROLBASLIK_SEVKDEPOID { get; set; }
        public Nullable<bool> DKKONTROLBASLIK_MUSTSENDST { get; set; }
        public Nullable<bool> DKKONTROLBASLIK_BOYASEVKDURUM { get; set; }
        public Nullable<int> DKKONTROLBASLIK_HAMEN { get; set; }
        public Nullable<double> DKKONTROLBASLIK_KDV { get; set; }
        public Nullable<double> DKKONTROLBASLIK_UPRICE { get; set; }
        public Nullable<int> DKKONTROLBASLIK_ROOTRECEIPTID { get; set; }
        public Nullable<int> DKKONTROLBASLIK_ROOTRECEIPTITEM { get; set; }
        public Nullable<int> DKKONTROLBASLIK_ROOTRECEIPTID2 { get; set; }
        public Nullable<int> DKKONTROLBASLIK_ROOTRECEIPTITEM2 { get; set; }
        public Nullable<bool> DKKONTROLBASLIK_INPUTST { get; set; }
        public Nullable<bool> DKKONTROLBASLIK_OUTPUTST { get; set; }
    }
}
