//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_DCPLANORDERS
    {
        public int DCPLANORDERS_SIRKETID { get; set; }
        public int DCPLANORDERS_DONEMID { get; set; }
        public int DCPLANORDERS_KAYNAK { get; set; }
        public int DCPLANORDERS_KAYNAKID { get; set; }
        public int DCPLANORDERS_PARCANO { get; set; }
        public System.DateTime DCPLANORDERS_TARIH { get; set; }
        public string DCPLANORDERS_KOD { get; set; }
        public string DCPLANORDERS_ACIKLAMA { get; set; }
        public Nullable<decimal> DCPLANORDERS_TUTAR { get; set; }
        public Nullable<double> DCPLANORDERS_DOVIZTUTAR { get; set; }
        public string DCPLANORDERS_DOVIZ { get; set; }
        public Nullable<System.DateTime> DCPLANORDERS_DOVIZTARIHI { get; set; }
        public Nullable<double> DCPLANORDERS_DOVIZKUR { get; set; }
    }
}
