//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_DEPOT
    {
        public int DEPOT_SIRKETID { get; set; }
        public int DEPOT_DEPOREF { get; set; }
        public string DEPOT_DEPOTIPIADI { get; set; }
        public Nullable<short> DEPOT_DEPOTIPI { get; set; }
        public string DEPOT_DEPONO { get; set; }
        public string DEPOT_DEPOADI { get; set; }
        public string DEPOT_GRUPKODU { get; set; }
        public string DEPOT_OZELKOD1 { get; set; }
        public string DEPOT_OZELKOD2 { get; set; }
        public string DEPOT_PERSONELNO { get; set; }
        public string DEPOT_PERSONELADI { get; set; }
        public string DEPOT_PERSONELTIPI { get; set; }
        public Nullable<int> DEPOT_PERSONELID { get; set; }
        public string DEPOT_STATUSNAME { get; set; }
        public Nullable<short> DEPOT_DURUM { get; set; }
        public Nullable<int> DEPOT_NOTEID { get; set; }
        public Nullable<System.DateTime> DEPOT_IPTALTARIHI { get; set; }
        public string DEPOT_ACIKLAMA { get; set; }
        public Nullable<bool> DEPOT_DEPOMU { get; set; }
        public Nullable<int> DEPOT_USTREF { get; set; }
        public Nullable<short> DEPOT_DEPOGURUPID { get; set; }
        public Nullable<int> DEPOT_ADRESID { get; set; }
        public string DEPOT_REMCONTROL { get; set; }
        public Nullable<bool> DEPOT_MRPDEPOT { get; set; }
        public Nullable<int> DEPOT_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> DEPOT_KAYITTARIHI { get; set; }
        public Nullable<int> DEPOT_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> DEPOT_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> DEPOT_UYARIID { get; set; }
    }
}
