//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_DCASCEPROGLIST
    {
        public int DCASCEPROGLIST_SIRKETID { get; set; }
        public int DCASCEPROGLIST_DEVICEID { get; set; }
        public int DCASCEPROGLIST_PARCANO { get; set; }
        public string DCASCEPROGLIST_PROGNAME { get; set; }
        public string DCASCEPROGLIST_URL { get; set; }
        public Nullable<int> DCASCEPROGLIST_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> DCASCEPROGLIST_KAYITTARIHI { get; set; }
        public Nullable<int> DCASCEPROGLIST_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> DCASCEPROGLIST_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> DCASCEPROGLIST_UYARIID { get; set; }
    }
}
