//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_DBOYADONUS
    {
        public int DBOYADONUS_SIRKETID { get; set; }
        public int DBOYADONUS_DONEMID { get; set; }
        public int DBOYADONUS_FISID { get; set; }
        public string DBOYADONUS_FISNO { get; set; }
        public Nullable<System.DateTime> DBOYADONUS_TARIH { get; set; }
        public string DBOYADONUS_ACIKLAMA { get; set; }
    }
}
