//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_DELIVERY
    {
        public int DELIVERY_SIRKETID { get; set; }
        public int DELIVERY_DONEMID { get; set; }
        public int DELIVERY_FISID { get; set; }
        public string DELIVERY_ISLEMTIPIADI { get; set; }
        public Nullable<short> DELIVERY_ISLEMTIPI { get; set; }
        public string DELIVERY_FISNO { get; set; }
        public Nullable<System.DateTime> DELIVERY_TARIH { get; set; }
        public string DELIVERY_GRUPKODU { get; set; }
        public string DELIVERY_OZELKOD1 { get; set; }
        public string DELIVERY_OZELKOD2 { get; set; }
        public string DELIVERY_TRANSCODE { get; set; }
        public string DELIVERY_PERSONELNO { get; set; }
        public string DELIVERY_PERSONELADI { get; set; }
        public string DELIVERY_PERSONELTIPI { get; set; }
        public Nullable<int> DELIVERY_PERSONELID { get; set; }
        public string DELIVERY_STATUSNAME { get; set; }
        public Nullable<short> DELIVERY_DURUM { get; set; }
        public Nullable<int> DELIVERY_NOTEID { get; set; }
        public Nullable<System.DateTime> DELIVERY_IPTALTARIHI { get; set; }
        public string DELIVERY_ACIKLAMA { get; set; }
        public string DELIVERY_DOKUMANNO { get; set; }
        public Nullable<decimal> DELIVERY_TUTAR { get; set; }
        public string DELIVERY_DOVIZ { get; set; }
        public Nullable<System.DateTime> DELIVERY_DOVIZTARIHI { get; set; }
        public Nullable<double> DELIVERY_DOVIZKUR { get; set; }
        public Nullable<double> DELIVERY_DOVIZTUTAR { get; set; }
        public string DELIVERY_HARDOVIZI { get; set; }
        public Nullable<System.DateTime> DELIVERY_HARDOVIZTARIHI { get; set; }
        public Nullable<double> DELIVERY_HARDOVIZKUR { get; set; }
        public Nullable<decimal> DELIVERY_DOVIZHAR { get; set; }
        public string DELIVERY_VERGIDAIRESI { get; set; }
        public string DELIVERY_VERGINO { get; set; }
        public string DELIVERY_VERGISEHRI { get; set; }
        public Nullable<System.DateTime> DELIVERY_VADE { get; set; }
        public Nullable<short> DELIVERY_GUNVADE { get; set; }
        public Nullable<System.DateTime> DELIVERY_OPSIYONVADE { get; set; }
        public Nullable<short> DELIVERY_KATEGORIID { get; set; }
        public string DELIVERY_ODEMETIPIADI { get; set; }
        public Nullable<short> DELIVERY_ODEMETIPI { get; set; }
        public Nullable<bool> DELIVERY_IHRACKAYITLI { get; set; }
        public Nullable<double> DELIVERY_INDIRIMTUTAR1 { get; set; }
        public Nullable<double> DELIVERY_INDIRIMO1 { get; set; }
        public Nullable<double> DELIVERY_INDIRIMTUTAR2 { get; set; }
        public Nullable<double> DELIVERY_INDIRIMO2 { get; set; }
        public Nullable<decimal> DELIVERY_URUNTOPLAMI { get; set; }
        public Nullable<decimal> DELIVERY_TOPLAMINDIRIM { get; set; }
        public Nullable<decimal> DELIVERY_KDVTOPLAM { get; set; }
        public Nullable<decimal> DELIVERY_OTVTOPLAM { get; set; }
        public Nullable<decimal> DELIVERY_TEVKIFATVERGITOPLAMI { get; set; }
        public Nullable<bool> DELIVERY_MUHASEBEKONTROL { get; set; }
        public Nullable<double> DELIVERY_MALIYETFIYAT { get; set; }
        public Nullable<System.DateTime> DELIVERY_KDVVADE { get; set; }
        public Nullable<decimal> DELIVERY_YUVARLAMATUTARI { get; set; }
        public Nullable<decimal> DELIVERY_TEVKIFATCARPANI { get; set; }
        public Nullable<decimal> DELIVERY_TEVKIFATBOLENI { get; set; }
        public Nullable<decimal> DELIVERY_STOPAJRATE { get; set; }
        public Nullable<decimal> DELIVERY_STOPAJ { get; set; }
        public string DELIVERY_KASANO { get; set; }
        public string DELIVERY_KASAADI { get; set; }
        public string DELIVERY_KASATIPI { get; set; }
        public Nullable<int> DELIVERY_KASAID { get; set; }
        public string DELIVERY_DEPONO { get; set; }
        public string DELIVERY_DEPOADI { get; set; }
        public string DELIVERY_DEPOTIPI { get; set; }
        public Nullable<int> DELIVERY_DEPOREF { get; set; }
        public string DELIVERY_CARINO { get; set; }
        public string DELIVERY_CARIADI { get; set; }
        public string DELIVERY_CARITIPI { get; set; }
        public Nullable<int> DELIVERY_CARIID { get; set; }
        public string DELIVERY_BANKANO { get; set; }
        public string DELIVERY_BANKAADI { get; set; }
        public string DELIVERY_BANKATIPI { get; set; }
        public Nullable<int> DELIVERY_BANKAID { get; set; }
        public Nullable<decimal> DELIVERY_BANKTOTAL { get; set; }
        public string DELIVERY_ADI1 { get; set; }
        public string DELIVERY_ADI2 { get; set; }
        public Nullable<int> DELIVERY_ADRESID { get; set; }
        public Nullable<System.DateTime> DELIVERY_SEVKTARIHI { get; set; }
        public Nullable<int> DELIVERY_SEVKCARIID { get; set; }
        public string DELIVERY_SEVKADI { get; set; }
        public string DELIVERY_SEVKADI2 { get; set; }
        public Nullable<int> DELIVERY_SEVKADRESI { get; set; }
        public string DELIVERY_ACIKLAMA1 { get; set; }
        public string DELIVERY_ACIKLAMA2 { get; set; }
        public string DELIVERY_PROJENO { get; set; }
        public string DELIVERY_PROJEADI { get; set; }
        public Nullable<int> DELIVERY_PROJEID { get; set; }
        public string DELIVERY_MASRAFYERKODU { get; set; }
        public string DELIVERY_MASRAFYERADI { get; set; }
        public Nullable<int> DELIVERY_MASRAFYERREF { get; set; }
        public string DELIVERY_DOVIZHARTIPIADI { get; set; }
        public Nullable<bool> DELIVERY_DOVIZHARTIPI { get; set; }
        public string DELIVERY_RECEIPTTYPENAME { get; set; }
        public Nullable<int> DELIVERY_RECEIPTTYPE { get; set; }
        public Nullable<int> DELIVERY_SID { get; set; }
        public string DELIVERY_PAKETADI { get; set; }
        public Nullable<int> DELIVERY_STOKPAKETID { get; set; }
        public Nullable<short> DELIVERY_PARTCOUNT { get; set; }
        public Nullable<short> DELIVERY_GLBPAYMENTID { get; set; }
        public Nullable<double> DELIVERY_SHIPPING { get; set; }
        public Nullable<int> DELIVERY_ACCRECEIPTID { get; set; }
        public Nullable<bool> DELIVERY_MANUELVAT { get; set; }
        public Nullable<int> DELIVERY_STKFIYATTIPID { get; set; }
        public string DELIVERY_BUDGETNO { get; set; }
        public string DELIVERY_BUDGETNAME { get; set; }
        public string DELIVERY_BUDGETTYPE { get; set; }
        public Nullable<int> DELIVERY_BUDGETID { get; set; }
        public Nullable<double> DELIVERY_BREAKTOTAL { get; set; }
        public Nullable<bool> DELIVERY_SENDDOC { get; set; }
        public string DELIVERY_CRMCONTACTSFULLNAME { get; set; }
        public Nullable<int> DELIVERY_CRMCONTACTSID { get; set; }
        public Nullable<decimal> DELIVERY_CURRDISCOUNTTOTAL1 { get; set; }
        public Nullable<double> DELIVERY_BONUS { get; set; }
        public Nullable<int> DELIVERY_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> DELIVERY_KAYITTARIHI { get; set; }
        public Nullable<int> DELIVERY_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> DELIVERY_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> DELIVERY_UYARIID { get; set; }
    }
}
