//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_DCASPLC
    {
        public int DCASPLC_SIRKETID { get; set; }
        public int DCASPLC_DEVICEID { get; set; }
        public int DCASPLC_PARCANO { get; set; }
        public string DCASPLC_ISISTASYONUNO { get; set; }
        public string DCASPLC_ISISTASYONUADI { get; set; }
        public string DCASPLC_ISISTASYONUTIPI { get; set; }
        public Nullable<int> DCASPLC_ISISTASYONUID { get; set; }
        public Nullable<bool> DCASPLC_PROLOTINPUT { get; set; }
        public Nullable<bool> DCASPLC_MATLOTINPUT { get; set; }
        public Nullable<bool> DCASPLC_ERRORINPUT { get; set; }
        public Nullable<bool> DCASPLC_MULTEMPINPUT { get; set; }
        public Nullable<bool> DCASPLC_UNKNOWNSTOP { get; set; }
        public Nullable<int> DCASPLC_UNKNOWNDURATION { get; set; }
        public Nullable<short> DCASPLC_INPUT0 { get; set; }
        public Nullable<short> DCASPLC_INPUT1 { get; set; }
        public Nullable<short> DCASPLC_INPUT2 { get; set; }
        public Nullable<short> DCASPLC_INPUT3 { get; set; }
        public Nullable<short> DCASPLC_INPUT4 { get; set; }
        public Nullable<short> DCASPLC_INPUT5 { get; set; }
        public Nullable<short> DCASPLC_INPUT6 { get; set; }
        public Nullable<short> DCASPLC_INPUT7 { get; set; }
        public Nullable<short> DCASPLC_INPUT8 { get; set; }
        public Nullable<short> DCASPLC_INPUT9 { get; set; }
        public Nullable<short> DCASPLC_INPUT10 { get; set; }
        public Nullable<short> DCASPLC_INPUT11 { get; set; }
        public Nullable<short> DCASPLC_INPUT12 { get; set; }
        public Nullable<short> DCASPLC_INPUT13 { get; set; }
        public Nullable<short> DCASPLC_INPUT14 { get; set; }
        public Nullable<short> DCASPLC_INPUT15 { get; set; }
        public string DCASPLC_APPLICATIONTYPENAME { get; set; }
        public Nullable<short> DCASPLC_APPLICATIONTYPE { get; set; }
        public string DCASPLC_COUNTTYPENAME { get; set; }
        public Nullable<short> DCASPLC_COUNTTYPE { get; set; }
        public string DCASPLC_STOPTYPENAME { get; set; }
        public Nullable<short> DCASPLC_STOPTYPE { get; set; }
        public Nullable<double> DCASPLC_COUNTMULT { get; set; }
        public Nullable<double> DCASPLC_COUNTDIV { get; set; }
        public string DCASPLC_ISLEMNO { get; set; }
        public string DCASPLC_ISLEMADI { get; set; }
        public string DCASPLC_ISLEMTIPI { get; set; }
        public Nullable<int> DCASPLC_ISLEMID { get; set; }
        public Nullable<System.DateTime> DCASPLC_BASLANGICTARIHI { get; set; }
        public Nullable<int> DCASPLC_PID { get; set; }
        public Nullable<double> DCASPLC_LUSCOUNT { get; set; }
        public Nullable<System.DateTime> DCASPLC_BREAKSTART { get; set; }
        public Nullable<int> DCASPLC_PLANSTOPTIME { get; set; }
        public Nullable<int> DCASPLC_NOTPLANSTOPTIME { get; set; }
        public Nullable<System.DateTime> DCASPLC_CONNECTIONBREAK { get; set; }
        public Nullable<int> DCASPLC_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> DCASPLC_KAYITTARIHI { get; set; }
        public Nullable<int> DCASPLC_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> DCASPLC_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> DCASPLC_UYARIID { get; set; }
    }
}
