//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_DELIVERYTRANS
    {
        public int DELIVERYTRANS_SIRKETID { get; set; }
        public int DELIVERYTRANS_DONEMID { get; set; }
        public int DELIVERYTRANS_FISID { get; set; }
        public short DELIVERYTRANS_PARCANO { get; set; }
        public int DELIVERYTRANS_HARSIRANO { get; set; }
        public Nullable<short> DELIVERYTRANS_KAYNAK { get; set; }
        public Nullable<int> DELIVERYTRANS_KAYNAKID { get; set; }
        public string DELIVERYTRANS_KAYNAKFISNO { get; set; }
        public Nullable<int> DELIVERYTRANS_KAYNAKSIRA { get; set; }
        public Nullable<double> DELIVERYTRANS_MIKTAR { get; set; }
        public Nullable<double> DELIVERYTRANS_HARMIKTARI { get; set; }
        public Nullable<System.DateTime> DELIVERYTRANS_TARIH { get; set; }
        public Nullable<int> DELIVERYTRANS_TOPROOT { get; set; }
        public Nullable<int> DELIVERYTRANS_TOPROOTID { get; set; }
        public Nullable<int> DELIVERYTRANS_TOPROOTITEMNO { get; set; }
    }
}
