//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_DOCUMENTS
    {
        public int DOCUMENTS_SIRKETID { get; set; }
        public int DOCUMENTS_DONEMID { get; set; }
        public string DOCUMENTS_KAYNAK { get; set; }
        public int DOCUMENTS_KAYNAKID { get; set; }
        public short DOCUMENTS_PARCANO { get; set; }
        public string DOCUMENTS_ACIKLAMA { get; set; }
        public Nullable<int> DOCUMENTS_ROOTITEMNO { get; set; }
        public string DOCUMENTS_DOKUMANYOLU { get; set; }
        public byte[] DOCUMENTS_DOKUMAN { get; set; }
        public Nullable<bool> DOCUMENTS_LINK { get; set; }
        public Nullable<int> DOCUMENTS_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> DOCUMENTS_KAYITTARIHI { get; set; }
        public Nullable<int> DOCUMENTS_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> DOCUMENTS_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> DOCUMENTS_UYARIID { get; set; }
    }
}
