//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_DISEMIRCOZGU
    {
        public int DISEMIRCOZGU_SIRKETID { get; set; }
        public int DISEMIRCOZGU_DONEMID { get; set; }
        public int DISEMIRCOZGU_PARCANO { get; set; }
        public int DISEMIRCOZGU_ISEMIRID { get; set; }
        public Nullable<int> DISEMIRCOZGU_SIRANO { get; set; }
        public string DISEMIRCOZGU_STOKNO { get; set; }
        public string DISEMIRCOZGU_STOKADI { get; set; }
        public string DISEMIRCOZGU_STOKTIPI { get; set; }
        public Nullable<int> DISEMIRCOZGU_STOKID { get; set; }
        public string DISEMIRCOZGU_SLNO { get; set; }
        public string DISEMIRCOZGU_DEPONO { get; set; }
        public string DISEMIRCOZGU_DEPOADI { get; set; }
        public string DISEMIRCOZGU_DEPOTIPI { get; set; }
        public Nullable<int> DISEMIRCOZGU_DEPOREF { get; set; }
        public Nullable<double> DISEMIRCOZGU_MIKTAR { get; set; }
    }
}
