//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_EBEYANKGECICIIND
    {
        public int EBEYANKGECICIIND_SIRKETID { get; set; }
        public int EBEYANKGECICIIND_DONEMID { get; set; }
        public int EBEYANKGECICIIND_EBEYANKGECICIID { get; set; }
        public int EBEYANKGECICIIND_PARCANO { get; set; }
        public Nullable<int> EBEYANKGECICIIND_INDIRIMTURU { get; set; }
        public Nullable<double> EBEYANKGECICIIND_VERGI { get; set; }
        public Nullable<int> EBEYANKGECICIIND_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> EBEYANKGECICIIND_KAYITTARIHI { get; set; }
        public Nullable<int> EBEYANKGECICIIND_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> EBEYANKGECICIIND_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> EBEYANKGECICIIND_UYARIID { get; set; }
    }
}
