//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_EMPLOYEEPICTURE
    {
        public int EMPLOYEEPICTURE_SIRKETID { get; set; }
        public string EMPLOYEEPICTURE_PERSONELNO { get; set; }
        public string EMPLOYEEPICTURE_PERSONELADI { get; set; }
        public string EMPLOYEEPICTURE_PERSONELTIPI { get; set; }
        public int EMPLOYEEPICTURE_PERSONELID { get; set; }
        public short EMPLOYEEPICTURE_PARCANO { get; set; }
        public byte[] EMPLOYEEPICTURE_EMPLOYEEPICTURE { get; set; }
        public byte[] EMPLOYEEPICTURE_EMPLOYEESIGN { get; set; }
        public Nullable<bool> EMPLOYEEPICTURE_UZAT { get; set; }
        public string EMPLOYEEPICTURE_GRUPKODU { get; set; }
        public Nullable<int> EMPLOYEEPICTURE_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> EMPLOYEEPICTURE_KAYITTARIHI { get; set; }
        public Nullable<int> EMPLOYEEPICTURE_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> EMPLOYEEPICTURE_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> EMPLOYEEPICTURE_UYARIID { get; set; }
    }
}
