//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_EBEYANBABS
    {
        public int EBEYANBABS_SIRKETID { get; set; }
        public int EBEYANBABS_EBEYANBABSID { get; set; }
        public int EBEYANBABS_YIL { get; set; }
        public int EBEYANBABS_AY { get; set; }
        public Nullable<int> EBEYANBABS_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> EBEYANBABS_KAYITTARIHI { get; set; }
        public Nullable<int> EBEYANBABS_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> EBEYANBABS_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> EBEYANBABS_UYARIID { get; set; }
    }
}
