//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_EMPLOYEEWORKTRANS
    {
        public int EMPLOYEEWORKTRANS_SIRKETID { get; set; }
        public int EMPLOYEEWORKTRANS_DONEMID { get; set; }
        public int EMPLOYEEWORKTRANS_TRANSID { get; set; }
        public string EMPLOYEEWORKTRANS_PERSONELNO { get; set; }
        public string EMPLOYEEWORKTRANS_PERSONELADI { get; set; }
        public string EMPLOYEEWORKTRANS_PERSONELTIPI { get; set; }
        public int EMPLOYEEWORKTRANS_PERSONELID { get; set; }
        public Nullable<short> EMPLOYEEWORKTRANS_WEXIT { get; set; }
        public Nullable<short> EMPLOYEEWORKTRANS_WENTER { get; set; }
        public Nullable<System.DateTime> EMPLOYEEWORKTRANS_PASSDATE { get; set; }
        public Nullable<int> EMPLOYEEWORKTRANS_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> EMPLOYEEWORKTRANS_KAYITTARIHI { get; set; }
        public Nullable<int> EMPLOYEEWORKTRANS_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> EMPLOYEEWORKTRANS_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> EMPLOYEEWORKTRANS_UYARIID { get; set; }
    }
}
