//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_EINVOICEITEM
    {
        public int EINVOICEITEM_SIRKETID { get; set; }
        public int EINVOICEITEM_DONEMID { get; set; }
        public int EINVOICEITEM_FISID { get; set; }
        public short EINVOICEITEM_PARCANO { get; set; }
        public string EINVOICEITEM_ACTIONCODE { get; set; }
        public string EINVOICEITEM_PARCATIPIADI { get; set; }
        public Nullable<short> EINVOICEITEM_PARCATIPI { get; set; }
        public string EINVOICEITEM_STOKNO { get; set; }
        public string EINVOICEITEM_STOKADI { get; set; }
        public string EINVOICEITEM_STOKTIPI { get; set; }
        public Nullable<int> EINVOICEITEM_STOKID { get; set; }
        public string EINVOICEITEM_GGNO { get; set; }
        public string EINVOICEITEM_GGADI { get; set; }
        public string EINVOICEITEM_GGTIPI { get; set; }
        public Nullable<int> EINVOICEITEM_GGID { get; set; }
        public string EINVOICEITEM_FIXTURENO { get; set; }
        public string EINVOICEITEM_FIXTURENAME { get; set; }
        public string EINVOICEITEM_FIXTURETYPE { get; set; }
        public Nullable<int> EINVOICEITEM_FIXTUREID { get; set; }
        public string EINVOICEITEM_BARKOD { get; set; }
        public string EINVOICEITEM_ACIKLAMA { get; set; }
        public string EINVOICEITEM_GRUPKODU { get; set; }
        public string EINVOICEITEM_OZELKOD1 { get; set; }
        public string EINVOICEITEM_OZELKOD2 { get; set; }
        public string EINVOICEITEM_TRANSCODE { get; set; }
        public Nullable<double> EINVOICEITEM_QTRANS { get; set; }
        public Nullable<double> EINVOICEITEM_FIYAT { get; set; }
        public Nullable<double> EINVOICEITEM_DOVIZKURU { get; set; }
        public Nullable<decimal> EINVOICEITEM_DOVIZKURHAR { get; set; }
        public Nullable<decimal> EINVOICEITEM_TUTAR { get; set; }
        public string EINVOICEITEM_DOVIZ { get; set; }
        public Nullable<System.DateTime> EINVOICEITEM_DOVIZTARIHI { get; set; }
        public Nullable<double> EINVOICEITEM_DOVIZKUR { get; set; }
        public Nullable<double> EINVOICEITEM_DOVIZTUTAR { get; set; }
        public string EINVOICEITEM_NITELIKADI { get; set; }
        public Nullable<int> EINVOICEITEM_NITELIKID { get; set; }
        public Nullable<double> EINVOICEITEM_MIKTAR { get; set; }
        public Nullable<double> EINVOICEITEM_QUANTITY2 { get; set; }
        public Nullable<double> EINVOICEITEM_QUANTITY3 { get; set; }
        public Nullable<double> EINVOICEITEM_FQUANTITY { get; set; }
        public Nullable<double> EINVOICEITEM_FQUANTITY2 { get; set; }
        public Nullable<double> EINVOICEITEM_FQUANTITY3 { get; set; }
        public Nullable<double> EINVOICEITEM_HARMIKTARI { get; set; }
        public Nullable<short> EINVOICEITEM_BIRIMHAR { get; set; }
        public Nullable<double> EINVOICEITEM_MALIYETFIYAT { get; set; }
        public string EINVOICEITEM_DEPONO { get; set; }
        public string EINVOICEITEM_DEPOADI { get; set; }
        public string EINVOICEITEM_DEPOTIPI { get; set; }
        public Nullable<int> EINVOICEITEM_DEPOREF { get; set; }
        public Nullable<decimal> EINVOICEITEM_INDIRIMO1 { get; set; }
        public Nullable<decimal> EINVOICEITEM_INDIRIMO2 { get; set; }
        public Nullable<decimal> EINVOICEITEM_INDIRIMO3 { get; set; }
        public Nullable<decimal> EINVOICEITEM_DISCOUNT4 { get; set; }
        public Nullable<decimal> EINVOICEITEM_DISCOUNT5 { get; set; }
        public Nullable<decimal> EINVOICEITEM_DISCOUNT6 { get; set; }
        public Nullable<System.DateTime> EINVOICEITEM_VADE { get; set; }
        public Nullable<double> EINVOICEITEM_NETFIYAT { get; set; }
        public Nullable<decimal> EINVOICEITEM_KDV { get; set; }
        public Nullable<bool> EINVOICEITEM_INDIRILEN_HESAPLANANKDV { get; set; }
        public Nullable<decimal> EINVOICEITEM_OTV { get; set; }
        public Nullable<decimal> EINVOICEITEM_OTVTUTAR { get; set; }
        public Nullable<decimal> EINVOICEITEM_KDVTUTAR { get; set; }
        public Nullable<decimal> EINVOICEITEM_INDIRIMTUTAR { get; set; }
        public Nullable<decimal> EINVOICEITEM_DISCOUNTTOTALOUTVAT { get; set; }
        public string EINVOICEITEM_PERSONELNO { get; set; }
        public string EINVOICEITEM_PERSONELADI { get; set; }
        public string EINVOICEITEM_PERSONELTIPI { get; set; }
        public Nullable<int> EINVOICEITEM_PERSONELID { get; set; }
        public string EINVOICEITEM_BIRIMADI { get; set; }
        public string EINVOICEITEM_BIRIMIDADI { get; set; }
        public string EINVOICEITEM_INTUNITCODE { get; set; }
        public Nullable<int> EINVOICEITEM_BIRIMID { get; set; }
        public Nullable<decimal> EINVOICEITEM_NETTOPLAM { get; set; }
        public string EINVOICEITEM_QTYSELECT { get; set; }
        public Nullable<bool> EINVOICEITEM_NOTCONVERTUNIT { get; set; }
        public string EINVOICEITEM_POSKASA { get; set; }
        public string EINVOICEITEM_POSKASIYER { get; set; }
        public Nullable<int> EINVOICEITEM_POSDEPARTMAN { get; set; }
        public string EINVOICEITEM_PARTINO { get; set; }
        public Nullable<double> EINVOICEITEM_VADEFARKI { get; set; }
        public Nullable<double> EINVOICEITEM_SEVKEDILENMIK { get; set; }
        public string EINVOICEITEM_PROJENO { get; set; }
        public string EINVOICEITEM_PROJEADI { get; set; }
        public Nullable<int> EINVOICEITEM_PROJEID { get; set; }
        public string EINVOICEITEM_MASRAFYERKODU { get; set; }
        public string EINVOICEITEM_MASRAFYERADI { get; set; }
        public Nullable<int> EINVOICEITEM_MASRAFYERREF { get; set; }
        public string EINVOICEITEM_STATUSNAME { get; set; }
        public Nullable<short> EINVOICEITEM_DURUM { get; set; }
        public Nullable<int> EINVOICEITEM_STKFIYATTIPID { get; set; }
        public Nullable<bool> EINVOICEITEM_PRICEACT { get; set; }
        public Nullable<double> EINVOICEITEM_VARUNITVALUE { get; set; }
        public string EINVOICEITEM_BUDGETNO { get; set; }
        public string EINVOICEITEM_BUDGETNAME { get; set; }
        public string EINVOICEITEM_BUDGETTYPE { get; set; }
        public Nullable<int> EINVOICEITEM_BUDGETID { get; set; }
        public Nullable<decimal> EINVOICEITEM_DISCOUNTCURRTOTAL { get; set; }
        public Nullable<decimal> EINVOICEITEM_TAKEUPMULTITEM { get; set; }
        public Nullable<decimal> EINVOICEITEM_TAKEUPDIVITEM { get; set; }
        public Nullable<decimal> EINVOICEITEM_TAKEUPTAXSUMITEM { get; set; }
        public string EINVOICEITEM_REZERVE1 { get; set; }
        public string EINVOICEITEM_REZERVE2 { get; set; }
        public string EINVOICEITEM_REZERVE3 { get; set; }
        public string EINVOICEITEM_REZERVE4 { get; set; }
        public string EINVOICEITEM_REZERVE5 { get; set; }
        public string EINVOICEITEM_REZERVE6 { get; set; }
        public Nullable<double> EINVOICEITEM_GRAMS { get; set; }
        public Nullable<double> EINVOICEITEM_GENISLIK { get; set; }
        public Nullable<double> EINVOICEITEM_DIFFPRICEPER { get; set; }
        public Nullable<double> EINVOICEITEM_DIFFPRICEUNIT { get; set; }
        public Nullable<double> EINVOICEITEM_DIFFPRICETOTAL { get; set; }
        public Nullable<double> EINVOICEITEM_MINUSCOST { get; set; }
        public Nullable<int> EINVOICEITEM_STOREHOUSEID { get; set; }
        public Nullable<int> EINVOICEITEM_VEHICLEID { get; set; }
        public Nullable<double> EINVOICEITEM_VEHICLECOUNTSTART { get; set; }
        public Nullable<double> EINVOICEITEM_VEHICLECOUNTEND { get; set; }
        public Nullable<int> EINVOICEITEM_URUNAGACID { get; set; }
        public Nullable<double> EINVOICEITEM_FOBTOTAL { get; set; }
        public Nullable<int> EINVOICEITEM_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> EINVOICEITEM_KAYITTARIHI { get; set; }
        public Nullable<int> EINVOICEITEM_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> EINVOICEITEM_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> EINVOICEITEM_UYARIID { get; set; }
    }
}
