//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_FIXTURERECEIPT
    {
        public int FIXTURERECEIPT_SIRKETID { get; set; }
        public int FIXTURERECEIPT_DONEMID { get; set; }
        public int FIXTURERECEIPT_FISID { get; set; }
        public string FIXTURERECEIPT_FISNO { get; set; }
        public Nullable<System.DateTime> FIXTURERECEIPT_TARIH { get; set; }
        public Nullable<int> FIXTURERECEIPT_FIXYEAR { get; set; }
        public Nullable<short> FIXTURERECEIPT_FIXPERIOD { get; set; }
        public string FIXTURERECEIPT_ACIKLAMA { get; set; }
        public Nullable<bool> FIXTURERECEIPT_MUHASEBEKONTROL { get; set; }
        public string FIXTURERECEIPT_DOVIZ { get; set; }
        public Nullable<System.DateTime> FIXTURERECEIPT_DOVIZTARIHI { get; set; }
        public Nullable<decimal> FIXTURERECEIPT_DOVIZKUR { get; set; }
        public Nullable<double> FIXTURERECEIPT_DOVIZTUTAR { get; set; }
        public Nullable<int> FIXTURERECEIPT_ACCRECEIPTID { get; set; }
        public Nullable<int> FIXTURERECEIPT_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> FIXTURERECEIPT_KAYITTARIHI { get; set; }
        public Nullable<int> FIXTURERECEIPT_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> FIXTURERECEIPT_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> FIXTURERECEIPT_UYARIID { get; set; }
    }
}
