//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_FIXTURE
    {
        public int FIXTURE_SIRKETID { get; set; }
        public int FIXTURE_FIXTUREID { get; set; }
        public string FIXTURE_FIXTURETYPENAME { get; set; }
        public short FIXTURE_FIXTURETYPE { get; set; }
        public string FIXTURE_FIXTURENO { get; set; }
        public string FIXTURE_FIXTURENAME { get; set; }
        public string FIXTURE_GRUPKODU { get; set; }
        public string FIXTURE_OZELKOD1 { get; set; }
        public string FIXTURE_OZELKOD2 { get; set; }
        public string FIXTURE_PERSONELNO { get; set; }
        public string FIXTURE_PERSONELADI { get; set; }
        public string FIXTURE_PERSONELTIPI { get; set; }
        public Nullable<int> FIXTURE_PERSONELID { get; set; }
        public string FIXTURE_ACIKLAMA { get; set; }
        public string FIXTURE_STATUSNAME { get; set; }
        public short FIXTURE_DURUM { get; set; }
        public Nullable<System.DateTime> FIXTURE_IPTALTARIHI { get; set; }
        public Nullable<int> FIXTURE_NOTEID { get; set; }
        public string FIXTURE_DOVIZ { get; set; }
        public Nullable<double> FIXTURE_KDV { get; set; }
        public Nullable<bool> FIXTURE_INDIRILEN_HESAPLANANKDV { get; set; }
        public Nullable<System.DateTime> FIXTURE_PURDATE { get; set; }
        public string FIXTURE_PURNO { get; set; }
        public Nullable<decimal> FIXTURE_SATISKDV { get; set; }
        public Nullable<decimal> FIXTURE_ALIMKDV { get; set; }
        public Nullable<int> FIXTURE_PURACTID { get; set; }
        public Nullable<decimal> FIXTURE_PURPRICE { get; set; }
        public Nullable<System.DateTime> FIXTURE_SALDATE { get; set; }
        public string FIXTURE_SALNO { get; set; }
        public Nullable<int> FIXTURE_SALACTID { get; set; }
        public Nullable<decimal> FIXTURE_SALPRICE { get; set; }
        public Nullable<double> FIXTURE_AMORTRATE { get; set; }
        public Nullable<int> FIXTURE_ENDYEAR { get; set; }
        public Nullable<int> FIXTURE_REVALUATION { get; set; }
        public Nullable<int> FIXTURE_DEPVALUATION { get; set; }
        public Nullable<int> FIXTURE_PRODEPRECIATION { get; set; }
        public string FIXTURE_HESAPNO { get; set; }
        public string FIXTURE_HESAPADI { get; set; }
        public string FIXTURE_HESAPTIPI { get; set; }
        public Nullable<int> FIXTURE_HESAPID { get; set; }
        public Nullable<int> FIXTURE_ACCID1 { get; set; }
        public Nullable<int> FIXTURE_ACCID2 { get; set; }
        public Nullable<int> FIXTURE_ACCID3 { get; set; }
        public Nullable<int> FIXTURE_ACCID4 { get; set; }
        public Nullable<int> FIXTURE_ACCID5 { get; set; }
        public Nullable<int> FIXTURE_ACCID6 { get; set; }
        public Nullable<int> FIXTURE_ACCID7 { get; set; }
        public string FIXTURE_MARKA { get; set; }
        public string FIXTURE_MODEL { get; set; }
        public string FIXTURE_SERINO { get; set; }
        public string FIXTURE_PLATE { get; set; }
        public Nullable<bool> FIXTURE_CALCSTATUS { get; set; }
        public Nullable<decimal> FIXTURE_LASTCUMULATIVE { get; set; }
        public Nullable<decimal> FIXTURE_LASTNETTOTAL { get; set; }
        public Nullable<decimal> FIXTURE_LASTCUMULATIVETRANS { get; set; }
        public string FIXTURE_PROJENO { get; set; }
        public string FIXTURE_PROJEADI { get; set; }
        public Nullable<int> FIXTURE_PROJEID { get; set; }
        public Nullable<int> FIXTURE_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> FIXTURE_KAYITTARIHI { get; set; }
        public Nullable<int> FIXTURE_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> FIXTURE_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> FIXTURE_UYARIID { get; set; }
    }
}
