//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_FIXTURECALC
    {
        public int FIXTURECALC_SIRKETID { get; set; }
        public string FIXTURECALC_FIXTURENO { get; set; }
        public string FIXTURECALC_FIXTURENAME { get; set; }
        public string FIXTURECALC_FIXTURETYPE { get; set; }
        public int FIXTURECALC_FIXTUREID { get; set; }
        public int FIXTURECALC_PARCANO { get; set; }
        public int FIXTURECALC_YEAR { get; set; }
        public int FIXTURECALC_DONEM { get; set; }
        public Nullable<decimal> FIXTURECALC_CALCVALUE { get; set; }
        public Nullable<decimal> FIXTURECALC_INFRATE { get; set; }
        public Nullable<int> FIXTURECALC_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> FIXTURECALC_KAYITTARIHI { get; set; }
        public Nullable<int> FIXTURECALC_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> FIXTURECALC_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> FIXTURECALC_UYARIID { get; set; }
    }
}
