//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_GLBALERTSD
    {
        public int GLBALERTSD_SIRKETID { get; set; }
        public int GLBALERTSD_UYARIID { get; set; }
        public int GLBALERTSD_KULLANICIID { get; set; }
        public string GLBALERTSD_COMPNAME { get; set; }
        public string GLBALERTSD_EMAILADDR { get; set; }
        public Nullable<bool> GLBALERTSD_READIT { get; set; }
        public Nullable<System.DateTime> GLBALERTSD_SEVKTARIH { get; set; }
        public Nullable<System.DateTime> GLBALERTSD_READDATE { get; set; }
    }
}
