//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_GGKARTI
    {
        public int GGKARTI_SIRKETID { get; set; }
        public int GGKARTI_GGID { get; set; }
        public string GGKARTI_GGTIPIADI { get; set; }
        public Nullable<short> GGKARTI_GGTIPI { get; set; }
        public string GGKARTI_GGNO { get; set; }
        public string GGKARTI_GGADI { get; set; }
        public string GGKARTI_GRUPKODU { get; set; }
        public string GGKARTI_OZELKOD1 { get; set; }
        public string GGKARTI_OZELKOD2 { get; set; }
        public string GGKARTI_PERSONELNO { get; set; }
        public string GGKARTI_PERSONELADI { get; set; }
        public string GGKARTI_PERSONELTIPI { get; set; }
        public Nullable<int> GGKARTI_PERSONELID { get; set; }
        public string GGKARTI_STATUSNAME { get; set; }
        public Nullable<short> GGKARTI_DURUM { get; set; }
        public Nullable<int> GGKARTI_NOTEID { get; set; }
        public Nullable<System.DateTime> GGKARTI_IPTALTARIHI { get; set; }
        public string GGKARTI_ACIKLAMA { get; set; }
        public Nullable<decimal> GGKARTI_BORC { get; set; }
        public Nullable<decimal> GGKARTI_ALACAK { get; set; }
        public Nullable<decimal> GGKARTI_BAKIYE { get; set; }
        public string GGKARTI_BAKIYETIPIADI { get; set; }
        public Nullable<short> GGKARTI_BAKIYETIPI { get; set; }
        public string GGKARTI_DOVIZ { get; set; }
        public Nullable<decimal> GGKARTI_DOVIZBORC { get; set; }
        public Nullable<decimal> GGKARTI_DOVIZALACAK { get; set; }
        public Nullable<decimal> GGKARTI_DOVIZBAKIYE { get; set; }
        public string GGKARTI_DOVIZBAKIYEACIKADI { get; set; }
        public Nullable<short> GGKARTI_DOVIZBAKIYEACIK { get; set; }
        public string GGKARTI_HESAPNO { get; set; }
        public string GGKARTI_HESAPADI { get; set; }
        public string GGKARTI_HESAPTIPI { get; set; }
        public Nullable<int> GGKARTI_HESAPID { get; set; }
        public Nullable<decimal> GGKARTI_KDV { get; set; }
        public Nullable<bool> GGKARTI_INDIRILEN_HESAPLANANKDV { get; set; }
        public string GGKARTI_ACCGROUPCODE { get; set; }
        public string GGKARTI_BIRIMADI { get; set; }
        public string GGKARTI_BIRIMIDADI { get; set; }
        public string GGKARTI_INTUNITCODE { get; set; }
        public Nullable<int> GGKARTI_BIRIMID { get; set; }
        public string GGKARTI_ULKE { get; set; }
        public string GGKARTI_CLASSIFICATIONCODE { get; set; }
        public Nullable<int> GGKARTI_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> GGKARTI_KAYITTARIHI { get; set; }
        public Nullable<int> GGKARTI_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> GGKARTI_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> GGKARTI_UYARIID { get; set; }
    }
}
