//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_GLBALERTUSER
    {
        public int GLBALERTUSER_UYARIID { get; set; }
        public int GLBALERTUSER_KULLANICIID { get; set; }
        public Nullable<System.DateTime> GLBALERTUSER_TARIH { get; set; }
        public Nullable<bool> GLBALERTUSER_READMSJ { get; set; }
        public string GLBALERTUSER_ALERTSQL { get; set; }
    }
}
