//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_HRMPERFGRPRESULT
    {
        public int HRMPERFGRPRESULT_SIRKETID { get; set; }
        public string HRMPERFGRPRESULT_HRMPERFGRPDESCRIPTION { get; set; }
        public int HRMPERFGRPRESULT_HRMPERFGRPID { get; set; }
        public int HRMPERFGRPRESULT_PARCANO { get; set; }
        public Nullable<int> HRMPERFGRPRESULT_FIRSTRANGE { get; set; }
        public Nullable<int> HRMPERFGRPRESULT_LASTRANGE { get; set; }
        public string HRMPERFGRPRESULT_ACIKLAMA { get; set; }
        public Nullable<decimal> HRMPERFGRPRESULT_AWARDAMOUNT { get; set; }
        public Nullable<bool> HRMPERFGRPRESULT_AWARDADD { get; set; }
        public string HRMPERFGRPRESULT_HRMPERFAWARDDESCRIPTION { get; set; }
        public Nullable<int> HRMPERFGRPRESULT_HRMPERFAWARDID { get; set; }
        public Nullable<int> HRMPERFGRPRESULT_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> HRMPERFGRPRESULT_KAYITTARIHI { get; set; }
        public Nullable<int> HRMPERFGRPRESULT_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> HRMPERFGRPRESULT_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> HRMPERFGRPRESULT_UYARIID { get; set; }
    }
}
