//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_IMPORTDATA
    {
        public int IMPORTDATA_ID { get; set; }
        public Nullable<int> IMPORTDATA_SIRKETID { get; set; }
        public Nullable<int> IMPORTDATA_KAYNAK { get; set; }
        public Nullable<int> IMPORTDATA_FISID { get; set; }
        public string IMPORTDATA_DOKUMANNO { get; set; }
        public string IMPORTDATA_FISNO { get; set; }
        public Nullable<System.DateTime> IMPORTDATA_TARIH { get; set; }
        public Nullable<int> IMPORTDATA_PARCANO { get; set; }
        public string IMPORTDATA_CARINO { get; set; }
        public string IMPORTDATA_CARIADI { get; set; }
        public string IMPORTDATA_CARITIPI { get; set; }
        public Nullable<int> IMPORTDATA_CARIID { get; set; }
        public string IMPORTDATA_ACTCARDNO { get; set; }
        public string IMPORTDATA_BANKANO { get; set; }
        public string IMPORTDATA_BANKAADI { get; set; }
        public string IMPORTDATA_BANKATIPI { get; set; }
        public Nullable<int> IMPORTDATA_BANKAID { get; set; }
        public string IMPORTDATA_BANKCARDNO { get; set; }
        public string IMPORTDATA_KASANO { get; set; }
        public string IMPORTDATA_KASAADI { get; set; }
        public string IMPORTDATA_KASATIPI { get; set; }
        public Nullable<int> IMPORTDATA_KASAID { get; set; }
        public string IMPORTDATA_CASHCARDNO { get; set; }
        public string IMPORTDATA_STOKNO { get; set; }
        public string IMPORTDATA_STOKADI { get; set; }
        public string IMPORTDATA_STOKTIPI { get; set; }
        public Nullable<int> IMPORTDATA_STOKID { get; set; }
        public string IMPORTDATA_STOCKCARDNO { get; set; }
        public Nullable<double> IMPORTDATA_MIKTAR { get; set; }
        public Nullable<double> IMPORTDATA_FIYAT { get; set; }
        public string IMPORTDATA_BIRIMADI { get; set; }
        public string IMPORTDATA_BIRIMIDADI { get; set; }
        public string IMPORTDATA_INTUNITCODE { get; set; }
        public Nullable<int> IMPORTDATA_BIRIMID { get; set; }
        public string IMPORTDATA_UNITNAMES { get; set; }
        public string IMPORTDATA_GIRISDEPONO { get; set; }
        public string IMPORTDATA_GIRISDEPOADI { get; set; }
        public string IMPORTDATA_DEPOTTYPEENTRY { get; set; }
        public Nullable<int> IMPORTDATA_GIRISDEPOID { get; set; }
        public string IMPORTDATA_DENTRYCARDNO { get; set; }
        public string IMPORTDATA_CIKISDEPONO { get; set; }
        public string IMPORTDATA_CIKISDEPOADI { get; set; }
        public string IMPORTDATA_DEPOTTYPEEXIT { get; set; }
        public Nullable<int> IMPORTDATA_CIKISDEPOID { get; set; }
        public string IMPORTDATA_DEXITCARDNO { get; set; }
        public Nullable<System.DateTime> IMPORTDATA_VADE { get; set; }
        public Nullable<int> IMPORTDATA_KDV { get; set; }
        public Nullable<bool> IMPORTDATA_INDIRILEN_HESAPLANANKDV { get; set; }
        public Nullable<double> IMPORTDATA_INDIRIMO1 { get; set; }
        public Nullable<double> IMPORTDATA_INDIRIMO2 { get; set; }
        public Nullable<double> IMPORTDATA_INDIRIMO3 { get; set; }
        public Nullable<double> IMPORTDATA_BDISCOUNT1 { get; set; }
        public Nullable<double> IMPORTDATA_BDISCOUNT2 { get; set; }
        public Nullable<double> IMPORTDATA_INDIRIMTUTAR1 { get; set; }
        public Nullable<double> IMPORTDATA_INDIRIMTUTAR2 { get; set; }
        public Nullable<double> IMPORTDATA_TUTAR { get; set; }
        public string IMPORTDATA_BANKACEKNO { get; set; }
        public string IMPORTDATA_ACIKLAMA { get; set; }
        public string IMPORTDATA_ACIKLAMA1 { get; set; }
        public string IMPORTDATA_ACIKLAMA2 { get; set; }
        public string IMPORTDATA_PERSONELNO { get; set; }
        public string IMPORTDATA_PERSONELADI { get; set; }
        public string IMPORTDATA_PERSONELTIPI { get; set; }
        public Nullable<int> IMPORTDATA_PERSONELID { get; set; }
        public string IMPORTDATA_EMPLOYEECARDNO { get; set; }
        public string IMPORTDATA_CSBANKNAME { get; set; }
        public string IMPORTDATA_BANKASUBE { get; set; }
        public string IMPORTDATA_BANKASEHIR { get; set; }
        public string IMPORTDATA_BANKAHESEPNO { get; set; }
        public Nullable<int> IMPORTDATA_KULLANICIID { get; set; }
        public string IMPORTDATA_ODEMETIPIADI { get; set; }
        public Nullable<int> IMPORTDATA_ODEMETIPI { get; set; }
        public Nullable<bool> IMPORTDATA_AKTARIM { get; set; }
        public string IMPORTDATA_RECEIPTTYPENAME { get; set; }
        public Nullable<int> IMPORTDATA_RECEIPTTYPE { get; set; }
        public Nullable<int> IMPORTDATA_SID { get; set; }
        public Nullable<int> IMPORTDATA_DOCUMENTTYPEID { get; set; }
        public string IMPORTDATA_DOCUMENTTYPENAME { get; set; }
        public string IMPORTDATA_DOCUMENTTYPE { get; set; }
    }
}
