//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_INVOICEPAYMENT
    {
        public int INVOICEPAYMENT_SIRKETID { get; set; }
        public int INVOICEPAYMENT_DONEMID { get; set; }
        public int INVOICEPAYMENT_FISID { get; set; }
        public Nullable<double> INVOICEPAYMENT_TUTAR { get; set; }
        public Nullable<double> INVOICEPAYMENT_CASHTOTAL { get; set; }
        public Nullable<double> INVOICEPAYMENT_BANKTOTAL { get; set; }
        public Nullable<double> INVOICEPAYMENT_BANKDIFFTOTAL { get; set; }
        public Nullable<double> INVOICEPAYMENT_CRATE { get; set; }
        public Nullable<double> INVOICEPAYMENT_CTOTAL { get; set; }
        public Nullable<double> INVOICEPAYMENT_CDIFFTOTAL { get; set; }
        public Nullable<double> INVOICEPAYMENT_STOTAL { get; set; }
        public Nullable<double> INVOICEPAYMENT_SDIFFTOTAL { get; set; }
        public Nullable<double> INVOICEPAYMENT_DISCOUNT { get; set; }
        public Nullable<double> INVOICEPAYMENT_INDIRIMTUTAR { get; set; }
        public Nullable<double> INVOICEPAYMENT_SRATE { get; set; }
        public Nullable<System.DateTime> INVOICEPAYMENT_SSTARTDATE { get; set; }
        public Nullable<int> INVOICEPAYMENT_SPARTCOUNT { get; set; }
        public Nullable<int> INVOICEPAYMENT_SWEEKMONTH { get; set; }
        public Nullable<int> INVOICEPAYMENT_SSTARTDAY { get; set; }
        public Nullable<int> INVOICEPAYMENT_SMONTHDAY { get; set; }
        public Nullable<bool> INVOICEPAYMENT_CUTADDPRICE { get; set; }
        public Nullable<int> INVOICEPAYMENT_FATWHR { get; set; }
        public string INVOICEPAYMENT_OZELKOD1 { get; set; }
        public string INVOICEPAYMENT_DOVIZ { get; set; }
        public Nullable<System.DateTime> INVOICEPAYMENT_DOVIZTARIHI { get; set; }
        public Nullable<double> INVOICEPAYMENT_DOVIZKUR { get; set; }
        public Nullable<double> INVOICEPAYMENT_DOVIZTUTAR { get; set; }
        public string INVOICEPAYMENT_KASANO { get; set; }
        public string INVOICEPAYMENT_KASAADI { get; set; }
        public string INVOICEPAYMENT_KASATIPI { get; set; }
        public Nullable<int> INVOICEPAYMENT_KASAID { get; set; }
        public Nullable<int> INVOICEPAYMENT_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> INVOICEPAYMENT_KAYITTARIHI { get; set; }
        public Nullable<int> INVOICEPAYMENT_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> INVOICEPAYMENT_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> INVOICEPAYMENT_UYARIID { get; set; }
    }
}
