//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_ISISTASYONUTAKVIMSENARYO
    {
        public int ISISTASYONUTAKVIMSENARYO_SIRKETID { get; set; }
        public int ISISTASYONUTAKVIMSENARYO_URESIPARISSENARYOREF { get; set; }
        public string ISISTASYONUTAKVIMSENARYO_ISISTASYONUNO { get; set; }
        public string ISISTASYONUTAKVIMSENARYO_ISISTASYONUADI { get; set; }
        public string ISISTASYONUTAKVIMSENARYO_ISISTASYONUTIPI { get; set; }
        public int ISISTASYONUTAKVIMSENARYO_ISISTASYONUID { get; set; }
        public System.DateTime ISISTASYONUTAKVIMSENARYO_BASLANGICTARIHI { get; set; }
        public Nullable<System.DateTime> ISISTASYONUTAKVIMSENARYO_BITISTARIHI { get; set; }
        public Nullable<bool> ISISTASYONUTAKVIMSENARYO_ISWORKING { get; set; }
    }
}
