//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_IBTHREADPACK
    {
        public int IBTHREADPACK_SIRKETID { get; set; }
        public int IBTHREADPACK_DONEMID { get; set; }
        public int IBTHREADPACK_IBTHREADPACKID { get; set; }
        public Nullable<System.DateTime> IBTHREADPACK_TARIH { get; set; }
        public string IBTHREADPACK_IBPACKAGEID { get; set; }
        public string IBTHREADPACK_CARINO { get; set; }
        public string IBTHREADPACK_CARIADI { get; set; }
        public string IBTHREADPACK_CARITIPI { get; set; }
        public Nullable<int> IBTHREADPACK_CARIID { get; set; }
        public string IBTHREADPACK_STOKNO { get; set; }
        public string IBTHREADPACK_STOKADI { get; set; }
        public string IBTHREADPACK_STOKTIPI { get; set; }
        public Nullable<int> IBTHREADPACK_STOKID { get; set; }
        public Nullable<int> IBTHREADPACK_FISID { get; set; }
        public string IBTHREADPACK_RENKNO { get; set; }
        public string IBTHREADPACK_RENKADI { get; set; }
        public Nullable<int> IBTHREADPACK_RENKID { get; set; }
        public string IBTHREADPACK_DOORNO { get; set; }
        public string IBTHREADPACK_DOKUMANNO { get; set; }
        public Nullable<int> IBTHREADPACK_IBTHREADTYPEID { get; set; }
        public Nullable<int> IBTHREADPACK_IBPROORDERID { get; set; }
        public string IBTHREADPACK_LOTNO { get; set; }
        public string IBTHREADPACK_PERSONELNO { get; set; }
        public string IBTHREADPACK_PERSONELADI { get; set; }
        public string IBTHREADPACK_PERSONELTIPI { get; set; }
        public Nullable<int> IBTHREADPACK_PERSONELID { get; set; }
        public string IBTHREADPACK_OZELKOD1 { get; set; }
        public string IBTHREADPACK_OZELKOD2 { get; set; }
        public Nullable<int> IBTHREADPACK_TQUALITYID { get; set; }
        public Nullable<double> IBTHREADPACK_TOPLAMKG { get; set; }
        public Nullable<int> IBTHREADPACK_BOBINADET { get; set; }
        public Nullable<int> IBTHREADPACK_PAKETMIKTAR { get; set; }
        public Nullable<double> IBTHREADPACK_BOBINKG { get; set; }
        public Nullable<double> IBTHREADPACK_PAKETKG { get; set; }
        public Nullable<double> IBTHREADPACK_NETKG { get; set; }
        public Nullable<double> IBTHREADPACK_KAZANNO { get; set; }
    }
}
