//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_MWORKGROUP
    {
        public int MWORKGROUP_SIRKETID { get; set; }
        public int MWORKGROUP_MWORKGROUPID { get; set; }
        public string MWORKGROUP_MWORKGROUPNO { get; set; }
        public string MWORKGROUP_MWORKGROUPNAME { get; set; }
        public string MWORKGROUP_GRUPKODU { get; set; }
        public string MWORKGROUP_OZELKOD1 { get; set; }
        public string MWORKGROUP_OZELKOD2 { get; set; }
        public Nullable<int> MWORKGROUP_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> MWORKGROUP_KAYITTARIHI { get; set; }
        public Nullable<int> MWORKGROUP_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> MWORKGROUP_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> MWORKGROUP_UYARIID { get; set; }
    }
}
