//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_MAINTENANCETYPE
    {
        public int MAINTENANCETYPE_SIRKETID { get; set; }
        public int MAINTENANCETYPE_MAINTENANCETYPEID { get; set; }
        public string MAINTENANCETYPE_MAINTENANCETYPENO { get; set; }
        public string MAINTENANCETYPE_MAINTENANCETYPENAME { get; set; }
        public Nullable<int> MAINTENANCETYPE_MWORKGROUPID { get; set; }
        public Nullable<int> MAINTENANCETYPE_MPERIOD { get; set; }
        public Nullable<int> MAINTENANCETYPE_INTERVAL { get; set; }
        public Nullable<int> MAINTENANCETYPE_MDIRECTIONSID { get; set; }
        public string MAINTENANCETYPE_NOTEGENERAL { get; set; }
        public string MAINTENANCETYPE_NOTESAFETY { get; set; }
        public string MAINTENANCETYPE_NOTESPEC { get; set; }
        public string MAINTENANCETYPE_GRUPKODU { get; set; }
        public string MAINTENANCETYPE_OZELKOD1 { get; set; }
        public string MAINTENANCETYPE_OZELKOD2 { get; set; }
        public string MAINTENANCETYPE_STATUSNAME { get; set; }
        public Nullable<short> MAINTENANCETYPE_DURUM { get; set; }
        public Nullable<int> MAINTENANCETYPE_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> MAINTENANCETYPE_KAYITTARIHI { get; set; }
        public Nullable<int> MAINTENANCETYPE_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> MAINTENANCETYPE_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> MAINTENANCETYPE_UYARIID { get; set; }
    }
}
