//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_MUSTAHSILSATIS
    {
        public int MUSTAHSILSATIS_SIRKETID { get; set; }
        public int MUSTAHSILSATIS_DONEMID { get; set; }
        public int MUSTAHSILSATIS_FISID { get; set; }
        public short MUSTAHSILSATIS_PARCANO { get; set; }
        public string MUSTAHSILSATIS_STOKNO { get; set; }
        public string MUSTAHSILSATIS_STOKADI { get; set; }
        public string MUSTAHSILSATIS_STOKTIPI { get; set; }
        public Nullable<int> MUSTAHSILSATIS_STOKID { get; set; }
        public Nullable<double> MUSTAHSILSATIS_FIYAT { get; set; }
        public Nullable<decimal> MUSTAHSILSATIS_TUTAR { get; set; }
        public Nullable<double> MUSTAHSILSATIS_MIKTAR { get; set; }
        public Nullable<double> MUSTAHSILSATIS_QUANTITY2 { get; set; }
        public Nullable<double> MUSTAHSILSATIS_QUANTITY3 { get; set; }
        public Nullable<int> MUSTAHSILSATIS_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> MUSTAHSILSATIS_KAYITTARIHI { get; set; }
        public Nullable<int> MUSTAHSILSATIS_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> MUSTAHSILSATIS_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> MUSTAHSILSATIS_UYARIID { get; set; }
    }
}
