//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_MUNITSTOCK
    {
        public int MUNITSTOCK_SIRKETID { get; set; }
        public string MUNITSTOCK_MUNITNO { get; set; }
        public string MUNITSTOCK_MUNITNAME { get; set; }
        public int MUNITSTOCK_MUNITID { get; set; }
        public int MUNITSTOCK_PARCANO { get; set; }
        public string MUNITSTOCK_STOKNO { get; set; }
        public string MUNITSTOCK_STOKADI { get; set; }
        public string MUNITSTOCK_STOKTIPI { get; set; }
        public Nullable<int> MUNITSTOCK_STOKID { get; set; }
        public string MUNITSTOCK_NITELIKADI { get; set; }
        public Nullable<int> MUNITSTOCK_NITELIKID { get; set; }
        public Nullable<double> MUNITSTOCK_MIKTAR { get; set; }
        public string MUNITSTOCK_ACIKLAMA { get; set; }
        public Nullable<int> MUNITSTOCK_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> MUNITSTOCK_KAYITTARIHI { get; set; }
        public Nullable<int> MUNITSTOCK_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> MUNITSTOCK_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> MUNITSTOCK_UYARIID { get; set; }
    }
}
