//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_MESSAGEEMP
    {
        public int MESSAGEEMP_SIRKETID { get; set; }
        public int MESSAGEEMP_MESSAGEEMPID { get; set; }
        public int MESSAGEEMP_SENDEREMP { get; set; }
        public int MESSAGEEMP_RECEIVEREMP { get; set; }
        public Nullable<System.DateTime> MESSAGEEMP_SEVKTARIH { get; set; }
        public Nullable<System.DateTime> MESSAGEEMP_READDATE { get; set; }
        public Nullable<System.DateTime> MESSAGEEMP_SHOWTIME { get; set; }
        public string MESSAGEEMP_MESSAGE { get; set; }
        public string MESSAGEEMP_MESSAGETYPENAME { get; set; }
        public Nullable<int> MESSAGEEMP_MESSAGETYPE { get; set; }
    }
}
