//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_ORDERSPROCESS
    {
        public int ORDERSPROCESS_SIRKETID { get; set; }
        public int ORDERSPROCESS_ORDERSPROCESSID { get; set; }
        public string ORDERSPROCESS_ORDERSPROCESSTYPENAME { get; set; }
        public Nullable<short> ORDERSPROCESS_ORDERSPROCESSTYPE { get; set; }
        public string ORDERSPROCESS_ORDERSPROCESSNO { get; set; }
        public string ORDERSPROCESS_ORDERSPROCESSNAME { get; set; }
        public string ORDERSPROCESS_GRUPKODU { get; set; }
        public string ORDERSPROCESS_OZELKOD1 { get; set; }
        public string ORDERSPROCESS_OZELKOD2 { get; set; }
        public string ORDERSPROCESS_PERSONELNO { get; set; }
        public string ORDERSPROCESS_PERSONELADI { get; set; }
        public string ORDERSPROCESS_PERSONELTIPI { get; set; }
        public Nullable<int> ORDERSPROCESS_PERSONELID { get; set; }
        public string ORDERSPROCESS_STATUSNAME { get; set; }
        public Nullable<short> ORDERSPROCESS_DURUM { get; set; }
        public Nullable<int> ORDERSPROCESS_NOTEID { get; set; }
        public Nullable<System.DateTime> ORDERSPROCESS_IPTALTARIHI { get; set; }
        public string ORDERSPROCESS_ACIKLAMA { get; set; }
        public Nullable<int> ORDERSPROCESS_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> ORDERSPROCESS_KAYITTARIHI { get; set; }
        public Nullable<int> ORDERSPROCESS_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> ORDERSPROCESS_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> ORDERSPROCESS_UYARIID { get; set; }
    }
}
