//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_OUTINFO
    {
        public int OUTINFO_SIRKETID { get; set; }
        public int OUTINFO_OUTINFOID { get; set; }
        public string OUTINFO_OUTINFONAME { get; set; }
        public string OUTINFO_TABLEADI { get; set; }
        public Nullable<int> OUTINFO_BREAKFORM { get; set; }
        public Nullable<int> OUTINFO_NOREADROW { get; set; }
        public string OUTINFO_BREAKCHAR { get; set; }
        public string OUTINFO_PATH { get; set; }
        public string OUTINFO_EXC { get; set; }
        public Nullable<short> OUTINFO_MD { get; set; }
        public string OUTINFO_DETAYTABLENAME { get; set; }
        public Nullable<int> OUTINFO_KAYNAK { get; set; }
        public Nullable<bool> OUTINFO_SEPARATEFILE { get; set; }
    }
}
