//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PWSCELLPLANS
    {
        public int PWSCELLPLANS_SIRKETID { get; set; }
        public int PWSCELLPLANS_DONEMID { get; set; }
        public int PWSCELLPLANS_PLANID { get; set; }
        public string PWSCELLPLANS_PJOBORDERRECEIPTNO { get; set; }
        public int PWSCELLPLANS_ISEMRIID { get; set; }
        public int PWSCELLPLANS_PROLLPROID { get; set; }
        public string PWSCELLPLANS_ISISTASYONUNO { get; set; }
        public string PWSCELLPLANS_ISISTASYONUADI { get; set; }
        public string PWSCELLPLANS_ISISTASYONUTIPI { get; set; }
        public int PWSCELLPLANS_ISISTASYONUID { get; set; }
        public int PWSCELLPLANS_PCELLID { get; set; }
        public Nullable<System.DateTime> PWSCELLPLANS_TARIH { get; set; }
        public Nullable<double> PWSCELLPLANS_MIKTAR { get; set; }
        public string PWSCELLPLANS_STATUSNAME { get; set; }
        public Nullable<short> PWSCELLPLANS_DURUM { get; set; }
        public Nullable<short> PWSCELLPLANS_ENTSTATUS { get; set; }
        public Nullable<bool> PWSCELLPLANS_SEND { get; set; }
        public string PWSCELLPLANS_ENTDESCRIPTION { get; set; }
        public string PWSCELLPLANS_PROCESSTYPE { get; set; }
        public Nullable<double> PWSCELLPLANS_KAPASITE { get; set; }
        public Nullable<int> PWSCELLPLANS_SEQID { get; set; }
        public Nullable<double> PWSCELLPLANS_PROCESSDURATION { get; set; }
        public Nullable<int> PWSCELLPLANS_NEWGRADEID { get; set; }
        public Nullable<int> PWSCELLPLANS_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PWSCELLPLANS_KAYITTARIHI { get; set; }
        public Nullable<int> PWSCELLPLANS_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PWSCELLPLANS_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PWSCELLPLANS_UYARIID { get; set; }
    }
}
