//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PMANAPPROWRQ
    {
        public int PMANAPPROWRQ_SIRKETID { get; set; }
        public int PMANAPPROWRQ_DONEMID { get; set; }
        public int PMANAPPROWRQ_FISID { get; set; }
        public int PMANAPPROWRQ_ROOTITEMNO { get; set; }
        public string PMANAPPROWRQ_LOTNO { get; set; }
        public string PMANAPPROWRQ_KARSILOTNO { get; set; }
        public string PMANAPPROWRQ_BATCHNO { get; set; }
        public int PMANAPPROWRQ_STOKLOTID { get; set; }
        public int PMANAPPROWRQ_PINPCONTDEFSTAID { get; set; }
        public Nullable<double> PMANAPPROWRQ_MIKTAR { get; set; }
        public Nullable<int> PMANAPPROWRQ_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PMANAPPROWRQ_KAYITTARIHI { get; set; }
        public Nullable<int> PMANAPPROWRQ_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PMANAPPROWRQ_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PMANAPPROWRQ_UYARIID { get; set; }
    }
}
