//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PQSUGGESTION
    {
        public int PQSUGGESTION_SIRKETID { get; set; }
        public int PQSUGGESTION_DONEMID { get; set; }
        public int PQSUGGESTION_PQSUGGESTIONID { get; set; }
        public Nullable<System.DateTime> PQSUGGESTION_TARIH { get; set; }
        public string PQSUGGESTION_PERSONELNO { get; set; }
        public string PQSUGGESTION_PERSONELADI { get; set; }
        public string PQSUGGESTION_PERSONELTIPI { get; set; }
        public Nullable<int> PQSUGGESTION_PERSONELID { get; set; }
        public string PQSUGGESTION_GRUPKODU { get; set; }
        public string PQSUGGESTION_OZELKOD1 { get; set; }
        public string PQSUGGESTION_OZELKOD2 { get; set; }
        public string PQSUGGESTION_ACIKLAMA { get; set; }
        public string PQSUGGESTION_SUGGESTIONNOTES { get; set; }
        public string PQSUGGESTION_RESULTNOTES { get; set; }
        public Nullable<int> PQSUGGESTION_NOTEID { get; set; }
        public Nullable<int> PQSUGGESTION_ASTATUS { get; set; }
        public Nullable<int> PQSUGGESTION_APPROVEEMPLOYEEID { get; set; }
        public Nullable<System.DateTime> PQSUGGESTION_APPROVEDATE { get; set; }
        public string PQSUGGESTION_APPROVEDESC { get; set; }
        public Nullable<int> PQSUGGESTION_EVALEMPLOYEEID { get; set; }
        public Nullable<System.DateTime> PQSUGGESTION_EVALDATE { get; set; }
        public Nullable<System.DateTime> PQSUGGESTION_CLOSEDATE { get; set; }
        public Nullable<int> PQSUGGESTION_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PQSUGGESTION_KAYITTARIHI { get; set; }
        public Nullable<int> PQSUGGESTION_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PQSUGGESTION_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PQSUGGESTION_UYARIID { get; set; }
    }
}
