//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PJOBORDERPROT
    {
        public int PJOBORDERPROT_SIRKETID { get; set; }
        public int PJOBORDERPROT_DONEMID { get; set; }
        public int PJOBORDERPROT_FISID { get; set; }
        public string PJOBORDERPROT_FISNO { get; set; }
        public Nullable<System.DateTime> PJOBORDERPROT_TARIH { get; set; }
        public string PJOBORDERPROT_RECEIPTTYPENAME { get; set; }
        public Nullable<int> PJOBORDERPROT_RECEIPTTYPE { get; set; }
        public Nullable<int> PJOBORDERPROT_URUNAGACID { get; set; }
        public Nullable<int> PJOBORDERPROT_ITEMID { get; set; }
        public string PJOBORDERPROT_STOKNO { get; set; }
        public string PJOBORDERPROT_STOKADI { get; set; }
        public string PJOBORDERPROT_STOKTIPI { get; set; }
        public Nullable<int> PJOBORDERPROT_STOKID { get; set; }
        public string PJOBORDERPROT_GRADENAME { get; set; }
        public Nullable<int> PJOBORDERPROT_NITELIKID { get; set; }
        public Nullable<int> PJOBORDERPROT_URETIMSIPARISID { get; set; }
        public Nullable<System.DateTime> PJOBORDERPROT_BASLANGICTARIHI { get; set; }
        public Nullable<System.DateTime> PJOBORDERPROT_SONTARIH { get; set; }
        public string PJOBORDERPROT_ISISTASYONUNO { get; set; }
        public string PJOBORDERPROT_ISISTASYONUADI { get; set; }
        public string PJOBORDERPROT_ISISTASYONUTIPI { get; set; }
        public Nullable<int> PJOBORDERPROT_ISISTASYONUID { get; set; }
        public string PJOBORDERPROT_ISMERKEZINO { get; set; }
        public string PJOBORDERPROT_ISMERKEZIADI { get; set; }
        public string PJOBORDERPROT_ISMERKEZITIPI { get; set; }
        public Nullable<int> PJOBORDERPROT_ISMERKEZIID { get; set; }
        public string PJOBORDERPROT_EKIPMANNO { get; set; }
        public string PJOBORDERPROT_EKIPMANADI { get; set; }
        public string PJOBORDERPROT_EKIPMANTIPI { get; set; }
        public Nullable<int> PJOBORDERPROT_EKIPMANID { get; set; }
        public string PJOBORDERPROT_ISLEMNO { get; set; }
        public string PJOBORDERPROT_ISLEMADI { get; set; }
        public string PJOBORDERPROT_ISLEMTIPI { get; set; }
        public Nullable<int> PJOBORDERPROT_ISLEMID { get; set; }
        public Nullable<decimal> PJOBORDERPROT_SURE { get; set; }
        public Nullable<decimal> PJOBORDERPROT_SETUPSURESI { get; set; }
        public Nullable<double> PJOBORDERPROT_MIKTAR { get; set; }
        public Nullable<double> PJOBORDERPROT_QUANTITY2 { get; set; }
        public Nullable<double> PJOBORDERPROT_QUANTITY3 { get; set; }
        public Nullable<double> PJOBORDERPROT_QUANTITYPRO { get; set; }
        public string PJOBORDERPROT_DEPONO { get; set; }
        public string PJOBORDERPROT_DEPOADI { get; set; }
        public string PJOBORDERPROT_DEPOTIPI { get; set; }
        public Nullable<int> PJOBORDERPROT_DEPOID { get; set; }
        public string PJOBORDERPROT_GRUPKODU { get; set; }
        public string PJOBORDERPROT_OZELKOD1 { get; set; }
        public string PJOBORDERPROT_OZELKOD2 { get; set; }
        public string PJOBORDERPROT_STATUSNAME { get; set; }
        public Nullable<short> PJOBORDERPROT_DURUM { get; set; }
        public Nullable<int> PJOBORDERPROT_NOTEID { get; set; }
        public Nullable<System.DateTime> PJOBORDERPROT_IPTALTARIHI { get; set; }
        public string PJOBORDERPROT_ACIKLAMA { get; set; }
        public Nullable<int> PJOBORDERPROT_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PJOBORDERPROT_KAYITTARIHI { get; set; }
        public Nullable<int> PJOBORDERPROT_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PJOBORDERPROT_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PJOBORDERPROT_UYARIID { get; set; }
    }
}
