//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PORDERSPLANWSCALC
    {
        public int PORDERSPLANWSCALC_SIRKETID { get; set; }
        public int PORDERSPLANWSCALC_DONEMID { get; set; }
        public string PORDERSPLANWSCALC_SIPARISPLANNO { get; set; }
        public string PORDERSPLANWSCALC_SIPARISPLANADI { get; set; }
        public int PORDERSPLANWSCALC_SIPARISPLANREF { get; set; }
        public string PORDERSPLANWSCALC_DONEMNO { get; set; }
        public string PORDERSPLANWSCALC_DONEMADI { get; set; }
        public int PORDERSPLANWSCALC_GLBDONEMID { get; set; }
        public string PORDERSPLANWSCALC_ISISTASYONUNO { get; set; }
        public string PORDERSPLANWSCALC_ISISTASYONUADI { get; set; }
        public string PORDERSPLANWSCALC_ISISTASYONUTIPI { get; set; }
        public int PORDERSPLANWSCALC_ISISTASYONUID { get; set; }
        public Nullable<double> PORDERSPLANWSCALC_SURE { get; set; }
        public Nullable<double> PORDERSPLANWSCALC_DURATIONCALC { get; set; }
        public Nullable<double> PORDERSPLANWSCALC_DURATIONPER { get; set; }
        public Nullable<int> PORDERSPLANWSCALC_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PORDERSPLANWSCALC_KAYITTARIHI { get; set; }
        public Nullable<int> PORDERSPLANWSCALC_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PORDERSPLANWSCALC_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PORDERSPLANWSCALC_UYARIID { get; set; }
    }
}
