//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PCUTTYPE
    {
        public int PCUTTYPE_SIRKETID { get; set; }
        public int PCUTTYPE_PCUTTYPEID { get; set; }
        public string PCUTTYPE_PCUTTYPENO { get; set; }
        public string PCUTTYPE_PCUTTYPENAME { get; set; }
        public string PCUTTYPE_PCUTTYPETYPENAME { get; set; }
        public Nullable<int> PCUTTYPE_PCUTTYPETYPE { get; set; }
        public string PCUTTYPE_ACIKLAMA { get; set; }
        public string PCUTTYPE_PERSONELNO { get; set; }
        public string PCUTTYPE_PERSONELADI { get; set; }
        public string PCUTTYPE_PERSONELTIPI { get; set; }
        public Nullable<int> PCUTTYPE_PERSONELID { get; set; }
        public string PCUTTYPE_GRUPKODU { get; set; }
        public string PCUTTYPE_OZELKOD1 { get; set; }
        public string PCUTTYPE_OZELKOD2 { get; set; }
        public string PCUTTYPE_STATUSNAME { get; set; }
        public Nullable<short> PCUTTYPE_DURUM { get; set; }
        public Nullable<System.DateTime> PCUTTYPE_IPTALTARIHI { get; set; }
        public Nullable<int> PCUTTYPE_NOTEID { get; set; }
        public Nullable<int> PCUTTYPE_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PCUTTYPE_KAYITTARIHI { get; set; }
        public Nullable<int> PCUTTYPE_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PCUTTYPE_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PCUTTYPE_UYARIID { get; set; }
    }
}
