//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PMANAPPROWIQ
    {
        public int PMANAPPROWIQ_SIRKETID { get; set; }
        public int PMANAPPROWIQ_DONEMID { get; set; }
        public int PMANAPPROWIQ_FISID { get; set; }
        public int PMANAPPROWIQ_ROOTITEMNO { get; set; }
        public string PMANAPPROWIQ_LOTNO { get; set; }
        public string PMANAPPROWIQ_KARSILOTNO { get; set; }
        public string PMANAPPROWIQ_BATCHNO { get; set; }
        public int PMANAPPROWIQ_STOKLOTID { get; set; }
        public int PMANAPPROWIQ_PINPCONTDEFSTAID { get; set; }
        public Nullable<double> PMANAPPROWIQ_MIKTAR { get; set; }
        public Nullable<int> PMANAPPROWIQ_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PMANAPPROWIQ_KAYITTARIHI { get; set; }
        public Nullable<int> PMANAPPROWIQ_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PMANAPPROWIQ_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PMANAPPROWIQ_UYARIID { get; set; }
    }
}
