//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PPROTECCONTIQFREQ
    {
        public int PPROTECCONTIQFREQ_SIRKETID { get; set; }
        public int PPROTECCONTIQFREQ_DONEMID { get; set; }
        public int PPROTECCONTIQFREQ_FISID { get; set; }
        public int PPROTECCONTIQFREQ_ROOTITEMNO { get; set; }
        public string PPROTECCONTIQFREQ_LOTNO { get; set; }
        public string PPROTECCONTIQFREQ_KARSILOTNO { get; set; }
        public string PPROTECCONTIQFREQ_BATCHNO { get; set; }
        public int PPROTECCONTIQFREQ_STOKLOTID { get; set; }
        public int PPROTECCONTIQFREQ_PINPCONTDEFSTAID { get; set; }
        public Nullable<double> PPROTECCONTIQFREQ_MIKTAR { get; set; }
        public Nullable<int> PPROTECCONTIQFREQ_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PPROTECCONTIQFREQ_KAYITTARIHI { get; set; }
        public Nullable<int> PPROTECCONTIQFREQ_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PPROTECCONTIQFREQ_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PPROTECCONTIQFREQ_UYARIID { get; set; }
    }
}
