//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PPROCONFOPSSTOCK
    {
        public int PPROCONFOPSSTOCK_SIRKETID { get; set; }
        public int PPROCONFOPSSTOCK_PPROCONFID { get; set; }
        public int PPROCONFOPSSTOCK_ITEMID { get; set; }
        public string PPROCONFOPSSTOCK_STOKNO { get; set; }
        public string PPROCONFOPSSTOCK_STOKADI { get; set; }
        public string PPROCONFOPSSTOCK_STOKTIPI { get; set; }
        public int PPROCONFOPSSTOCK_STOKID { get; set; }
        public string PPROCONFOPSSTOCK_NITELIKADI { get; set; }
        public int PPROCONFOPSSTOCK_NITELIKID { get; set; }
        public Nullable<int> PPROCONFOPSSTOCK_PARCANO { get; set; }
        public Nullable<int> PPROCONFOPSSTOCK_USTREF { get; set; }
        public Nullable<double> PPROCONFOPSSTOCK_MIKTAR { get; set; }
        public Nullable<double> PPROCONFOPSSTOCK_NETMIKTAR { get; set; }
        public string PPROCONFOPSSTOCK_BIRIMADI { get; set; }
        public string PPROCONFOPSSTOCK_BIRIMIDADI { get; set; }
        public string PPROCONFOPSSTOCK_INTUNITCODE { get; set; }
        public Nullable<int> PPROCONFOPSSTOCK_BIRIMID { get; set; }
    }
}
