//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PUBLICRECEIPTITEM
    {
        public int PUBLICRECEIPTITEM_SIRKETID { get; set; }
        public int PUBLICRECEIPTITEM_DONEMID { get; set; }
        public int PUBLICRECEIPTITEM_FISID { get; set; }
        public short PUBLICRECEIPTITEM_PARCANO { get; set; }
        public Nullable<System.DateTime> PUBLICRECEIPTITEM_TARIH { get; set; }
        public string PUBLICRECEIPTITEM_TRANSCODE { get; set; }
        public string PUBLICRECEIPTITEM_DOKUMANNO { get; set; }
        public string PUBLICRECEIPTITEM_ACIKLAMA { get; set; }
        public string PUBLICRECEIPTITEM_GRUPKODU { get; set; }
        public string PUBLICRECEIPTITEM_OZELKOD1 { get; set; }
        public string PUBLICRECEIPTITEM_OZELKOD2 { get; set; }
        public Nullable<double> PUBLICRECEIPTITEM_MIKTAR { get; set; }
        public Nullable<decimal> PUBLICRECEIPTITEM_BORC { get; set; }
        public Nullable<decimal> PUBLICRECEIPTITEM_ALACAK { get; set; }
        public string PUBLICRECEIPTITEM_DOVIZ { get; set; }
        public Nullable<System.DateTime> PUBLICRECEIPTITEM_DOVIZTARIHI { get; set; }
        public Nullable<double> PUBLICRECEIPTITEM_DOVIZKUR { get; set; }
        public Nullable<decimal> PUBLICRECEIPTITEM_DOVIZBORC { get; set; }
        public Nullable<decimal> PUBLICRECEIPTITEM_DOVIZALACAK { get; set; }
        public Nullable<System.DateTime> PUBLICRECEIPTITEM_VADE { get; set; }
        public Nullable<int> PUBLICRECEIPTITEM_GUNVADE { get; set; }
        public Nullable<int> PUBLICRECEIPTITEM_KARTID { get; set; }
        public string PUBLICRECEIPTITEM_ISLEMTIPIADI { get; set; }
        public Nullable<int> PUBLICRECEIPTITEM_ISLEMTIPI { get; set; }
        public string PUBLICRECEIPTITEM_PROJENO { get; set; }
        public string PUBLICRECEIPTITEM_PROJEADI { get; set; }
        public Nullable<int> PUBLICRECEIPTITEM_PROJEID { get; set; }
        public string PUBLICRECEIPTITEM_BUDGETNO { get; set; }
        public string PUBLICRECEIPTITEM_BUDGETNAME { get; set; }
        public string PUBLICRECEIPTITEM_BUDGETTYPE { get; set; }
        public Nullable<int> PUBLICRECEIPTITEM_BUDGETID { get; set; }
        public Nullable<short> PUBLICRECEIPTITEM_MULTIPLIER { get; set; }
        public Nullable<int> PUBLICRECEIPTITEM_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PUBLICRECEIPTITEM_KAYITTARIHI { get; set; }
        public Nullable<int> PUBLICRECEIPTITEM_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PUBLICRECEIPTITEM_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PUBLICRECEIPTITEM_UYARIID { get; set; }
    }
}
