//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PUANPROMOSYONSTOCKTARGET
    {
        public int PUANPROMOSYONSTOCKTARGET_SIRKETID { get; set; }
        public int PUANPROMOSYONSTOCKTARGET_DONEMID { get; set; }
        public int PUANPROMOSYONSTOCKTARGET_FISID { get; set; }
        public int PUANPROMOSYONSTOCKTARGET_PARCANO { get; set; }
        public string PUANPROMOSYONSTOCKTARGET_STOKNO { get; set; }
        public string PUANPROMOSYONSTOCKTARGET_STOKADI { get; set; }
        public string PUANPROMOSYONSTOCKTARGET_STOKTIPI { get; set; }
        public Nullable<int> PUANPROMOSYONSTOCKTARGET_STOKID { get; set; }
        public string PUANPROMOSYONSTOCKTARGET_GRUPKODU { get; set; }
        public string PUANPROMOSYONSTOCKTARGET_OZELKOD1 { get; set; }
        public string PUANPROMOSYONSTOCKTARGET_OZELKOD2 { get; set; }
        public string PUANPROMOSYONSTOCKTARGET_OZELKOD3 { get; set; }
        public string PUANPROMOSYONSTOCKTARGET_OZELKOD4 { get; set; }
        public string PUANPROMOSYONSTOCKTARGET_OZELKOD5 { get; set; }
        public string PUANPROMOSYONSTOCKTARGET_OZELKOD6 { get; set; }
        public string PUANPROMOSYONSTOCKTARGET_OZELKOD7 { get; set; }
        public string PUANPROMOSYONSTOCKTARGET_OZELKOD8 { get; set; }
        public string PUANPROMOSYONSTOCKTARGET_OZELKOD9 { get; set; }
        public string PUANPROMOSYONSTOCKTARGET_OZELKOD10 { get; set; }
        public Nullable<int> PUANPROMOSYONSTOCKTARGET_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PUANPROMOSYONSTOCKTARGET_KAYITTARIHI { get; set; }
        public Nullable<int> PUANPROMOSYONSTOCKTARGET_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PUANPROMOSYONSTOCKTARGET_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PUANPROMOSYONSTOCKTARGET_UYARIID { get; set; }
    }
}
