//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PWSSTATUSITEM
    {
        public int PWSSTATUSITEM_SIRKETID { get; set; }
        public string PWSSTATUSITEM_ISISTASYONUNO { get; set; }
        public string PWSSTATUSITEM_ISISTASYONUADI { get; set; }
        public string PWSSTATUSITEM_ISISTASYONUTIPI { get; set; }
        public int PWSSTATUSITEM_ISISTASYONUID { get; set; }
        public int PWSSTATUSITEM_PID { get; set; }
        public int PWSSTATUSITEM_PARCANO { get; set; }
        public string PWSSTATUSITEM_STOKNO { get; set; }
        public string PWSSTATUSITEM_STOKADI { get; set; }
        public string PWSSTATUSITEM_STOKTIPI { get; set; }
        public int PWSSTATUSITEM_STOKID { get; set; }
        public Nullable<double> PWSSTATUSITEM_URETIMMIKTAR { get; set; }
        public Nullable<double> PWSSTATUSITEM_PQUANTITY2 { get; set; }
        public Nullable<double> PWSSTATUSITEM_PQUANTITY3 { get; set; }
        public Nullable<double> PWSSTATUSITEM_LASTQTY { get; set; }
        public Nullable<double> PWSSTATUSITEM_LASTQTY2 { get; set; }
        public Nullable<double> PWSSTATUSITEM_LASTQTY3 { get; set; }
        public Nullable<double> PWSSTATUSITEM_LASTSECTION { get; set; }
        public Nullable<double> PWSSTATUSITEM_LASTSECTION2 { get; set; }
        public Nullable<double> PWSSTATUSITEM_LASTSECTION3 { get; set; }
        public Nullable<double> PWSSTATUSITEM_LOSSQTY { get; set; }
        public Nullable<double> PWSSTATUSITEM_LOSSQTY2 { get; set; }
        public Nullable<double> PWSSTATUSITEM_LOSSQTY3 { get; set; }
        public string PWSSTATUSITEM_ACIKLAMA { get; set; }
        public Nullable<int> PWSSTATUSITEM_ISEMRIID { get; set; }
        public Nullable<System.DateTime> PWSSTATUSITEM_STARTTIME { get; set; }
        public Nullable<int> PWSSTATUSITEM_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PWSSTATUSITEM_KAYITTARIHI { get; set; }
        public Nullable<int> PWSSTATUSITEM_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PWSSTATUSITEM_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PWSSTATUSITEM_UYARIID { get; set; }
    }
}
