//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PDESIGNITEM
    {
        public int PDESIGNITEM_SIRKETID { get; set; }
        public string PDESIGNITEM_PDESIGNNAME { get; set; }
        public int PDESIGNITEM_PDESIGNID { get; set; }
        public int PDESIGNITEM_PARCANO { get; set; }
        public string PDESIGNITEM_ISLEMTIPIADI { get; set; }
        public Nullable<int> PDESIGNITEM_ISLEMTIPI { get; set; }
        public Nullable<double> PDESIGNITEM_SUMWIRECNT { get; set; }
        public Nullable<double> PDESIGNITEM_DN { get; set; }
        public Nullable<double> PDESIGNITEM_RQUANTITY { get; set; }
        public Nullable<double> PDESIGNITEM_LOSS { get; set; }
        public Nullable<double> PDESIGNITEM_MIKTAR { get; set; }
        public string PDESIGNITEM_PPROCONFOPSPRONO { get; set; }
        public string PDESIGNITEM_PPROCONFOPSPRONAME { get; set; }
        public Nullable<int> PDESIGNITEM_PPROCONFOPSPROID { get; set; }
        public string PDESIGNITEM_STOCKNOOTHER { get; set; }
        public string PDESIGNITEM_STOCKNAMEOTHER { get; set; }
        public Nullable<int> PDESIGNITEM_DIGERSTOKID { get; set; }
        public Nullable<int> PDESIGNITEM_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PDESIGNITEM_KAYITTARIHI { get; set; }
        public Nullable<int> PDESIGNITEM_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PDESIGNITEM_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PDESIGNITEM_UYARIID { get; set; }
    }
}
