//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PQNEWPROJECTO
    {
        public int PQNEWPROJECTO_SIRKETID { get; set; }
        public int PQNEWPROJECTO_PQNEWPROJECTID { get; set; }
        public int PQNEWPROJECTO_PARCANO { get; set; }
        public string PQNEWPROJECTO_GRUPKODU { get; set; }
        public string PQNEWPROJECTO_ACIKLAMA { get; set; }
    }
}
