//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PORDERSORDER
    {
        public int PORDERSORDER_SIRKETID { get; set; }
        public int PORDERSORDER_DONEMID { get; set; }
        public string PORDERSORDER_SIPARISNO { get; set; }
        public int PORDERSORDER_URETIMSIPARISID { get; set; }
        public int PORDERSORDER_SIPARISID { get; set; }
        public int PORDERSORDER_SIPARISSIRANO { get; set; }
        public Nullable<double> PORDERSORDER_MIKTAR { get; set; }
        public Nullable<double> PORDERSORDER_QUANTITY2 { get; set; }
        public Nullable<double> PORDERSORDER_QUANTITY3 { get; set; }
        public Nullable<int> PORDERSORDER_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PORDERSORDER_KAYITTARIHI { get; set; }
        public Nullable<int> PORDERSORDER_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PORDERSORDER_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PORDERSORDER_UYARIID { get; set; }
    }
}
