//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PSTRONGBOXTRANS
    {
        public int PSTRONGBOXTRANS_SIRKETID { get; set; }
        public int PSTRONGBOXTRANS_DONEMID { get; set; }
        public int PSTRONGBOXTRANS_PSTRONGBOXTRANSID { get; set; }
        public short PSTRONGBOXTRANS_KAYNAK { get; set; }
        public int PSTRONGBOXTRANS_KAYNAKID { get; set; }
        public string PSTRONGBOXTRANS_PSTRONGBOXNO { get; set; }
        public string PSTRONGBOXTRANS_PSTRONGBOXNAME { get; set; }
        public string PSTRONGBOXTRANS_PSTRONGBOXTYPE { get; set; }
        public int PSTRONGBOXTRANS_PSTRONGBOXID { get; set; }
        public string PSTRONGBOXTRANS_KAYNAKFISNO { get; set; }
        public Nullable<System.DateTime> PSTRONGBOXTRANS_TARIH { get; set; }
        public Nullable<double> PSTRONGBOXTRANS_MIKTAR { get; set; }
        public Nullable<short> PSTRONGBOXTRANS_GIRISCIKIS { get; set; }
        public string PSTRONGBOXTRANS_CARINO { get; set; }
        public string PSTRONGBOXTRANS_CARIADI { get; set; }
        public string PSTRONGBOXTRANS_CARITIPI { get; set; }
        public Nullable<int> PSTRONGBOXTRANS_CARIID { get; set; }
        public string PSTRONGBOXTRANS_ACIKLAMA { get; set; }
        public Nullable<int> PSTRONGBOXTRANS_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PSTRONGBOXTRANS_KAYITTARIHI { get; set; }
        public Nullable<int> PSTRONGBOXTRANS_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PSTRONGBOXTRANS_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PSTRONGBOXTRANS_UYARIID { get; set; }
    }
}
