//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PARTSALESINFO
    {
        public int PARTSALESINFO_SIRKETID { get; set; }
        public int PARTSALESINFO_DONEMID { get; set; }
        public int PARTSALESINFO_FISID { get; set; }
        public Nullable<double> PARTSALESINFO_CASHTOTAL { get; set; }
        public Nullable<System.DateTime> PARTSALESINFO_BASLANGICTARIHI { get; set; }
        public Nullable<int> PARTSALESINFO_PARTCOUNT { get; set; }
        public Nullable<int> PARTSALESINFO_WEEKMONTH { get; set; }
        public Nullable<int> PARTSALESINFO_STARTDAY { get; set; }
        public Nullable<int> PARTSALESINFO_MONTHDAY { get; set; }
    }
}
