//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PPROCYCLE
    {
        public short PPROCYCLE_SIRKETID { get; set; }
        public string PPROCYCLE_ISISTASYONUNO { get; set; }
        public string PPROCYCLE_ISISTASYONUADI { get; set; }
        public string PPROCYCLE_ISISTASYONUTIPI { get; set; }
        public short PPROCYCLE_ISISTASYONUID { get; set; }
        public System.DateTime PPROCYCLE_KAYITTARIHI { get; set; }
        public string PPROCYCLE_STOKNO { get; set; }
        public string PPROCYCLE_STOKADI { get; set; }
        public string PPROCYCLE_STOKTIPI { get; set; }
        public int PPROCYCLE_STOKID { get; set; }
        public string PPROCYCLE_NITELIKADI { get; set; }
        public Nullable<short> PPROCYCLE_NITELIKID { get; set; }
        public Nullable<int> PPROCYCLE_DONEM { get; set; }
        public Nullable<int> PPROCYCLE_PID { get; set; }
        public Nullable<double> PPROCYCLE_CYCLE { get; set; }
        public Nullable<double> PPROCYCLE_AVGCYCLE { get; set; }
        public Nullable<double> PPROCYCLE_QTY { get; set; }
        public Nullable<double> PPROCYCLE_QTY2 { get; set; }
        public Nullable<double> PPROCYCLE_QTY3 { get; set; }
        public string PPROCYCLE_EKIPMANNO { get; set; }
        public string PPROCYCLE_EKIPMANADI { get; set; }
        public string PPROCYCLE_EKIPMANTIPI { get; set; }
        public Nullable<short> PPROCYCLE_EKIPMANID { get; set; }
        public string PPROCYCLE_PERSONELNO { get; set; }
        public string PPROCYCLE_PERSONELADI { get; set; }
        public string PPROCYCLE_PERSONELTIPI { get; set; }
        public Nullable<short> PPROCYCLE_PERSONELID { get; set; }
        public Nullable<short> PPROCYCLE_EMPLOYEEID1 { get; set; }
        public string PPROCYCLE_EMPLOYEENO2 { get; set; }
        public string PPROCYCLE_EMPLOYEENAME2 { get; set; }
        public string PPROCYCLE_EMPLOYEETYPE2 { get; set; }
        public Nullable<short> PPROCYCLE_EMPLOYEEID2 { get; set; }
        public Nullable<byte> PPROCYCLE_SHIFT { get; set; }
        public string PPROCYCLE_DURUSNEDENNO { get; set; }
        public string PPROCYCLE_DURUSNEDENADI { get; set; }
        public string PPROCYCLE_DURUSNEDENTIPI { get; set; }
        public Nullable<short> PPROCYCLE_DURUSNEDENREF { get; set; }
        public Nullable<System.DateTime> PPROCYCLE_STOPSTARTTIME { get; set; }
        public Nullable<int> PPROCYCLE_STOPDURATION { get; set; }
        public Nullable<byte> PPROCYCLE_PSTOPSECTION { get; set; }
        public string PPROCYCLE_HATANO { get; set; }
        public string PPROCYCLE_HATAADI { get; set; }
        public Nullable<short> PPROCYCLE_HATAREF { get; set; }
        public Nullable<byte> PPROCYCLE_PEQUIPMENTCOE { get; set; }
        public Nullable<bool> PPROCYCLE_PLANNEDSTOP { get; set; }
        public Nullable<int> PPROCYCLE_REASONPEQID { get; set; }
    }
}
