//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PROLLPRO
    {
        public int PROLLPRO_SIRKETID { get; set; }
        public int PROLLPRO_DONEMID { get; set; }
        public int PROLLPRO_PROLLPROID { get; set; }
        public string PROLLPRO_PROLLPRONO { get; set; }
        public string PROLLPRO_PJOBORDERRECEIPTNO { get; set; }
        public Nullable<int> PROLLPRO_ISEMRIID { get; set; }
        public Nullable<System.DateTime> PROLLPRO_TARIH { get; set; }
        public string PROLLPRO_STOKNO { get; set; }
        public string PROLLPRO_STOKADI { get; set; }
        public string PROLLPRO_STOKTIPI { get; set; }
        public Nullable<int> PROLLPRO_STOKID { get; set; }
        public string PROLLPRO_NITELIKADI { get; set; }
        public Nullable<int> PROLLPRO_NITELIKID { get; set; }
        public string PROLLPRO_PERSONELNO { get; set; }
        public string PROLLPRO_PERSONELADI { get; set; }
        public string PROLLPRO_PERSONELTIPI { get; set; }
        public Nullable<int> PROLLPRO_PERSONELID { get; set; }
        public string PROLLPRO_EMPLOYEENO2 { get; set; }
        public string PROLLPRO_EMPLOYEENAME2 { get; set; }
        public string PROLLPRO_EMPLOYEETYPE2 { get; set; }
        public Nullable<int> PROLLPRO_EMPLOYEEID2 { get; set; }
        public string PROLLPRO_GRUPKODU { get; set; }
        public string PROLLPRO_OZELKOD1 { get; set; }
        public string PROLLPRO_OZELKOD2 { get; set; }
        public Nullable<int> PROLLPRO_OLDPROLLPROID { get; set; }
        public string PROLLPRO_ISLEMNO { get; set; }
        public string PROLLPRO_ISLEMADI { get; set; }
        public string PROLLPRO_ISLEMTIPI { get; set; }
        public Nullable<int> PROLLPRO_ISLEMID { get; set; }
        public Nullable<double> PROLLPRO_MIKTARMT { get; set; }
        public Nullable<double> PROLLPRO_MIKTARKG { get; set; }
        public Nullable<double> PROLLPRO_QUANTITY3 { get; set; }
        public Nullable<double> PROLLPRO_QTYKG { get; set; }
        public Nullable<int> PROLLPRO_STOKLOTID { get; set; }
        public string PROLLPRO_LOTNO { get; set; }
        public string PROLLPRO_KARSILOTNO { get; set; }
        public string PROLLPRO_PARTY { get; set; }
        public string PROLLPRO_DEPONO { get; set; }
        public string PROLLPRO_DEPOADI { get; set; }
        public string PROLLPRO_DEPOTIPI { get; set; }
        public Nullable<int> PROLLPRO_DEPOREF { get; set; }
        public Nullable<bool> PROLLPRO_ISPRINT { get; set; }
        public string PROLLPRO_PAKETNO { get; set; }
        public Nullable<int> PROLLPRO_PAKETREF { get; set; }
        public string PROLLPRO_STATUSNAME { get; set; }
        public Nullable<short> PROLLPRO_DURUM { get; set; }
        public string PROLLPRO_QUALITYGROUP { get; set; }
        public string PROLLPRO_CARINO { get; set; }
        public string PROLLPRO_CARIADI { get; set; }
        public string PROLLPRO_CARITIPI { get; set; }
        public Nullable<int> PROLLPRO_CARIID { get; set; }
        public Nullable<int> PROLLPRO_STOCKLOTSIDMAT { get; set; }
        public Nullable<int> PROLLPRO_TRANSFERID { get; set; }
        public string PROLLPRO_ACIKLAMA { get; set; }
        public string PROLLPRO_ACIKLAMA2 { get; set; }
        public Nullable<double> PROLLPRO_PIECES { get; set; }
        public Nullable<int> PROLLPRO_PRINTLABELID { get; set; }
        public string PROLLPRO_ISISTASYONUNO { get; set; }
        public string PROLLPRO_ISISTASYONUADI { get; set; }
        public string PROLLPRO_ISISTASYONUTIPI { get; set; }
        public Nullable<int> PROLLPRO_ISISTASYONUID { get; set; }
        public Nullable<int> PROLLPRO_FIRSTPROLLPROID { get; set; }
        public string PROLLPRO_CARNO { get; set; }
        public Nullable<double> PROLLPRO_FABRICWIDTH { get; set; }
        public Nullable<System.DateTime> PROLLPRO_EMPSTARTDATE { get; set; }
        public Nullable<System.DateTime> PROLLPRO_EMPENDDATE { get; set; }
        public Nullable<int> PROLLPRO_SIPARISID { get; set; }
        public Nullable<int> PROLLPRO_SIPARISSIRANO { get; set; }
        public string PROLLPRO_AREANO { get; set; }
        public Nullable<int> PROLLPRO_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PROLLPRO_KAYITTARIHI { get; set; }
        public Nullable<int> PROLLPRO_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PROLLPRO_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PROLLPRO_UYARIID { get; set; }
    }
}
