//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PTECCONTI
    {
        public int PTECCONTI_SIRKETID { get; set; }
        public int PTECCONTI_DONEMID { get; set; }
        public int PTECCONTI_FISID { get; set; }
        public int PTECCONTI_ROOTITEMNO { get; set; }
        public string PTECCONTI_LOTNO { get; set; }
        public string PTECCONTI_KARSILOTNO { get; set; }
        public string PTECCONTI_BATCHNO { get; set; }
        public int PTECCONTI_STOKLOTID { get; set; }
        public Nullable<int> PTECCONTI_KAYNAK { get; set; }
        public Nullable<int> PTECCONTI_KAYNAKID { get; set; }
        public string PTECCONTI_STOKNO { get; set; }
        public string PTECCONTI_STOKADI { get; set; }
        public string PTECCONTI_STOKTIPI { get; set; }
        public Nullable<int> PTECCONTI_STOKID { get; set; }
        public string PTECCONTI_NITELIKADI { get; set; }
        public Nullable<int> PTECCONTI_NITELIKID { get; set; }
        public string PTECCONTI_DEPONO { get; set; }
        public string PTECCONTI_DEPOADI { get; set; }
        public string PTECCONTI_DEPOTIPI { get; set; }
        public Nullable<int> PTECCONTI_DEPOREF { get; set; }
        public Nullable<double> PTECCONTI_ACCEPTQUANTITY { get; set; }
        public Nullable<double> PTECCONTI_MIKTAR { get; set; }
        public string PTECCONTI_STATUSNAME { get; set; }
        public Nullable<short> PTECCONTI_DURUM { get; set; }
        public Nullable<System.DateTime> PTECCONTI_IPTALTARIHI { get; set; }
        public string PTECCONTI_ACIKLAMA { get; set; }
        public string PTECCONTI_ACIKLAMA2 { get; set; }
        public Nullable<int> PTECCONTI_SAMPLEQUANTITY { get; set; }
        public Nullable<int> PTECCONTI_PKONTROLREF { get; set; }
        public Nullable<int> PTECCONTI_MEASUREACCEPT { get; set; }
        public Nullable<int> PTECCONTI_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PTECCONTI_KAYITTARIHI { get; set; }
        public Nullable<int> PTECCONTI_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PTECCONTI_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PTECCONTI_UYARIID { get; set; }
    }
}
