//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PAINTJOB
    {
        public int PAINTJOB_SIRKETID { get; set; }
        public int PAINTJOB_DONEMID { get; set; }
        public int PAINTJOB_PAINTJOBID { get; set; }
        public string PAINTJOB_PJOBORDERRECEIPTNO { get; set; }
        public Nullable<int> PAINTJOB_ISEMRIID { get; set; }
        public string PAINTJOB_STOKNO { get; set; }
        public string PAINTJOB_STOKADI { get; set; }
        public string PAINTJOB_STOKTIPI { get; set; }
        public Nullable<int> PAINTJOB_STOKID { get; set; }
        public Nullable<double> PAINTJOB_MIKTAR { get; set; }
        public Nullable<double> PAINTJOB_QUANTITY2 { get; set; }
        public Nullable<double> PAINTJOB_QUANTITY3 { get; set; }
        public string PAINTJOB_NITELIKADI { get; set; }
        public Nullable<int> PAINTJOB_NITELIKID { get; set; }
        public string PAINTJOB_ISLEMNO { get; set; }
        public string PAINTJOB_ISLEMADI { get; set; }
        public string PAINTJOB_ISLEMTIPI { get; set; }
        public Nullable<int> PAINTJOB_ISLEMID { get; set; }
        public string PAINTJOB_GRUPKODU { get; set; }
        public string PAINTJOB_OZELKOD1 { get; set; }
        public string PAINTJOB_OZELKOD2 { get; set; }
        public string PAINTJOB_ACIKLAMA { get; set; }
        public Nullable<System.DateTime> PAINTJOB_TARIH { get; set; }
        public Nullable<bool> PAINTJOB_FAULTY { get; set; }
        public Nullable<int> PAINTJOB_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PAINTJOB_KAYITTARIHI { get; set; }
        public Nullable<int> PAINTJOB_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PAINTJOB_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PAINTJOB_UYARIID { get; set; }
    }
}
