//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PMOULDSPLAN
    {
        public int PMOULDSPLAN_SIRKETID { get; set; }
        public int PMOULDSPLAN_PMOULDSID { get; set; }
        public string PMOULDSPLAN_PLANGROUPCODE { get; set; }
        public Nullable<System.DateTime> PMOULDSPLAN_PLANLANANBASLANGIC { get; set; }
        public Nullable<System.DateTime> PMOULDSPLAN_PLANLANANBITIS { get; set; }
        public Nullable<System.DateTime> PMOULDSPLAN_GERCEKBASLANGIC { get; set; }
        public Nullable<System.DateTime> PMOULDSPLAN_GERCEKBITIS { get; set; }
        public Nullable<int> PMOULDSPLAN_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PMOULDSPLAN_KAYITTARIHI { get; set; }
        public Nullable<int> PMOULDSPLAN_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PMOULDSPLAN_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PMOULDSPLAN_UYARIID { get; set; }
    }
}
