//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PJOBORDERPROW
    {
        public int PJOBORDERPROW_SIRKETID { get; set; }
        public int PJOBORDERPROW_DONEMID { get; set; }
        public int PJOBORDERPROW_FISID { get; set; }
        public string PJOBORDERPROW_ISISTASYONUNO { get; set; }
        public string PJOBORDERPROW_ISISTASYONUADI { get; set; }
        public string PJOBORDERPROW_ISISTASYONUTIPI { get; set; }
        public int PJOBORDERPROW_ISISTASYONUID { get; set; }
        public Nullable<System.DateTime> PJOBORDERPROW_PSTARTDATE { get; set; }
        public Nullable<System.DateTime> PJOBORDERPROW_PENDDATE { get; set; }
        public string PJOBORDERPROW_ISMERKEZINO { get; set; }
        public string PJOBORDERPROW_ISMERKEZIADI { get; set; }
        public string PJOBORDERPROW_ISMERKEZITIPI { get; set; }
        public Nullable<int> PJOBORDERPROW_ISMERKEZIID { get; set; }
        public string PJOBORDERPROW_EKIPMANNO { get; set; }
        public string PJOBORDERPROW_EKIPMANADI { get; set; }
        public string PJOBORDERPROW_EKIPMANTIPI { get; set; }
        public Nullable<int> PJOBORDERPROW_EKIPMANID { get; set; }
        public Nullable<decimal> PJOBORDERPROW_SURE { get; set; }
        public Nullable<decimal> PJOBORDERPROW_SETUPSURESI { get; set; }
        public Nullable<double> PJOBORDERPROW_MIKTAR { get; set; }
        public Nullable<double> PJOBORDERPROW_QUANTITYPRO { get; set; }
        public string PJOBORDERPROW_DEPONO { get; set; }
        public string PJOBORDERPROW_DEPOADI { get; set; }
        public string PJOBORDERPROW_DEPOTIPI { get; set; }
        public Nullable<int> PJOBORDERPROW_DEPOID { get; set; }
        public string PJOBORDERPROW_GRUPKODU { get; set; }
        public string PJOBORDERPROW_OZELKOD1 { get; set; }
        public string PJOBORDERPROW_OZELKOD2 { get; set; }
        public string PJOBORDERPROW_STATUSNAME { get; set; }
        public Nullable<short> PJOBORDERPROW_DURUM { get; set; }
        public Nullable<int> PJOBORDERPROW_NOTEID { get; set; }
        public Nullable<System.DateTime> PJOBORDERPROW_IPTALTARIHI { get; set; }
        public string PJOBORDERPROW_ACIKLAMA { get; set; }
        public Nullable<int> PJOBORDERPROW_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PJOBORDERPROW_KAYITTARIHI { get; set; }
        public Nullable<int> PJOBORDERPROW_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PJOBORDERPROW_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PJOBORDERPROW_UYARIID { get; set; }
    }
}
