//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PLINEDET
    {
        public int PLINEDET_SIRKETID { get; set; }
        public int PLINEDET_PLINEID { get; set; }
        public string PLINEDET_ISISTASYONUNO { get; set; }
        public string PLINEDET_ISISTASYONUADI { get; set; }
        public string PLINEDET_ISISTASYONUTIPI { get; set; }
        public int PLINEDET_ISISTASYONUID { get; set; }
        public Nullable<int> PLINEDET_PARCANO { get; set; }
        public string PLINEDET_ISLEMNO { get; set; }
        public string PLINEDET_ISLEMADI { get; set; }
        public string PLINEDET_ISLEMTIPI { get; set; }
        public Nullable<int> PLINEDET_ISLEMID { get; set; }
        public Nullable<bool> PLINEDET_OPTIONAL { get; set; }
        public Nullable<bool> PLINEDET_PRODWORKSTATION { get; set; }
        public Nullable<bool> PLINEDET_MASTERSTATION { get; set; }
        public Nullable<bool> PLINEDET_CTPACKING { get; set; }
        public Nullable<bool> PLINEDET_CTPALETTING { get; set; }
        public Nullable<bool> PLINEDET_CYCLEFORPWS { get; set; }
        public Nullable<bool> PLINEDET_WSIMAGEVIDEO { get; set; }
        public string PLINEDET_WSIMAGEVIDEOPATH { get; set; }
        public Nullable<int> PLINEDET_PLINEITEMNO { get; set; }
        public Nullable<int> PLINEDET_PLINEITEMNO2 { get; set; }
        public Nullable<bool> PLINEDET_LOADPIDNOTCONTROL { get; set; }
        public Nullable<int> PLINEDET_PWORKSTATIONIDREL { get; set; }
        public Nullable<short> PLINEDET_SPEEDDIVPERCENT { get; set; }
        public Nullable<bool> PLINEDET_RANDOMWORK { get; set; }
        public Nullable<bool> PLINEDET_SHOWPLANSCREEN { get; set; }
        public Nullable<int> PLINEDET_PREVEQPSCID { get; set; }
        public Nullable<int> PLINEDET_NEXTEQPSCID { get; set; }
        public Nullable<int> PLINEDET_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PLINEDET_KAYITTARIHI { get; set; }
        public Nullable<int> PLINEDET_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PLINEDET_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PLINEDET_UYARIID { get; set; }
    }
}
