//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PCOSTWCEMP
    {
        public int PCOSTWCEMP_SIRKETID { get; set; }
        public int PCOSTWCEMP_DONEMID { get; set; }
        public int PCOSTWCEMP_PCOSTPERIODID { get; set; }
        public string PCOSTWCEMP_ISMERKEZINO { get; set; }
        public string PCOSTWCEMP_ISMERKEZIADI { get; set; }
        public string PCOSTWCEMP_ISMERKEZITIPI { get; set; }
        public int PCOSTWCEMP_ISMERKEZIID { get; set; }
        public Nullable<int> PCOSTWCEMP_PERSONELSAYISI { get; set; }
        public Nullable<double> PCOSTWCEMP_OVERTIMEDURATION { get; set; }
        public Nullable<double> PCOSTWCEMP_TUTAR { get; set; }
        public Nullable<int> PCOSTWCEMP_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PCOSTWCEMP_KAYITTARIHI { get; set; }
        public Nullable<int> PCOSTWCEMP_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PCOSTWCEMP_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PCOSTWCEMP_UYARIID { get; set; }
    }
}
