//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PRETOUCHWORKTIME
    {
        public int PRETOUCHWORKTIME_SIRKETID { get; set; }
        public int PRETOUCHWORKTIME_DONEMID { get; set; }
        public int PRETOUCHWORKTIME_FISID { get; set; }
        public int PRETOUCHWORKTIME_PARCANO { get; set; }
        public string PRETOUCHWORKTIME_PERSONELNO { get; set; }
        public string PRETOUCHWORKTIME_PERSONELADI { get; set; }
        public string PRETOUCHWORKTIME_PERSONELTIPI { get; set; }
        public Nullable<int> PRETOUCHWORKTIME_PERSONELID { get; set; }
        public Nullable<double> PRETOUCHWORKTIME_MIKTAR { get; set; }
        public Nullable<double> PRETOUCHWORKTIME_QUANTITY2 { get; set; }
        public Nullable<double> PRETOUCHWORKTIME_QUANTITY3 { get; set; }
        public Nullable<System.DateTime> PRETOUCHWORKTIME_BASLANGICTARIHI { get; set; }
        public Nullable<System.DateTime> PRETOUCHWORKTIME_SONTARIH { get; set; }
        public Nullable<double> PRETOUCHWORKTIME_SURE { get; set; }
        public Nullable<double> PRETOUCHWORKTIME_MATMULT { get; set; }
        public Nullable<double> PRETOUCHWORKTIME_EMPLOYEEMULT { get; set; }
        public Nullable<double> PRETOUCHWORKTIME_SETUPSURESI { get; set; }
    }
}
