//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PSHIFTSCHEDULERCALC
    {
        public int PSHIFTSCHEDULERCALC_SIRKETID { get; set; }
        public int PSHIFTSCHEDULERCALC_SHIFT { get; set; }
        public int PSHIFTSCHEDULERCALC_PARCANO { get; set; }
        public string PSHIFTSCHEDULERCALC_DURUSNEDENNO { get; set; }
        public string PSHIFTSCHEDULERCALC_DURUSNEDENADI { get; set; }
        public string PSHIFTSCHEDULERCALC_DURUSNEDENTIPI { get; set; }
        public Nullable<int> PSHIFTSCHEDULERCALC_DURUSNEDENREF { get; set; }
        public Nullable<System.DateTime> PSHIFTSCHEDULERCALC_STARTTIME { get; set; }
        public Nullable<System.DateTime> PSHIFTSCHEDULERCALC_FINISHTIME { get; set; }
        public Nullable<bool> PSHIFTSCHEDULERCALC_ADDDAYSTARTTIME { get; set; }
        public Nullable<bool> PSHIFTSCHEDULERCALC_ADDDAYFINISHTIME { get; set; }
        public Nullable<bool> PSHIFTSCHEDULERCALC_MINUSSTARTTIME { get; set; }
        public Nullable<bool> PSHIFTSCHEDULERCALC_MINUSFINISHTIME { get; set; }
        public Nullable<int> PSHIFTSCHEDULERCALC_OVERTIME { get; set; }
        public Nullable<int> PSHIFTSCHEDULERCALC_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PSHIFTSCHEDULERCALC_KAYITTARIHI { get; set; }
        public Nullable<int> PSHIFTSCHEDULERCALC_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PSHIFTSCHEDULERCALC_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PSHIFTSCHEDULERCALC_UYARIID { get; set; }
    }
}
