//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PMANAPPROWI
    {
        public int PMANAPPROWI_SIRKETID { get; set; }
        public int PMANAPPROWI_DONEMID { get; set; }
        public int PMANAPPROWI_FISID { get; set; }
        public int PMANAPPROWI_ROOTITEMNO { get; set; }
        public string PMANAPPROWI_LOTNO { get; set; }
        public string PMANAPPROWI_KARSILOTNO { get; set; }
        public string PMANAPPROWI_BATCHNO { get; set; }
        public int PMANAPPROWI_STOKLOTID { get; set; }
        public Nullable<int> PMANAPPROWI_KAYNAK { get; set; }
        public Nullable<int> PMANAPPROWI_KAYNAKID { get; set; }
        public string PMANAPPROWI_STOKNO { get; set; }
        public string PMANAPPROWI_STOKADI { get; set; }
        public string PMANAPPROWI_STOKTIPI { get; set; }
        public Nullable<int> PMANAPPROWI_STOKID { get; set; }
        public string PMANAPPROWI_NITELIKADI { get; set; }
        public Nullable<int> PMANAPPROWI_NITELIKID { get; set; }
        public string PMANAPPROWI_DEPONO { get; set; }
        public string PMANAPPROWI_DEPOADI { get; set; }
        public string PMANAPPROWI_DEPOTIPI { get; set; }
        public Nullable<int> PMANAPPROWI_DEPOREF { get; set; }
        public Nullable<double> PMANAPPROWI_ACCEPTQUANTITY { get; set; }
        public Nullable<double> PMANAPPROWI_MIKTAR { get; set; }
        public string PMANAPPROWI_STATUSNAME { get; set; }
        public Nullable<short> PMANAPPROWI_DURUM { get; set; }
        public Nullable<System.DateTime> PMANAPPROWI_IPTALTARIHI { get; set; }
        public string PMANAPPROWI_ACIKLAMA { get; set; }
        public Nullable<int> PMANAPPROWI_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PMANAPPROWI_KAYITTARIHI { get; set; }
        public Nullable<int> PMANAPPROWI_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PMANAPPROWI_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PMANAPPROWI_UYARIID { get; set; }
    }
}
