//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PIDRECEIPTEVENT
    {
        public int PIDRECEIPTEVENT_SIRKETID { get; set; }
        public int PIDRECEIPTEVENT_FISID { get; set; }
        public string PIDRECEIPTEVENT_ISISTASYONUNO { get; set; }
        public string PIDRECEIPTEVENT_ISISTASYONUADI { get; set; }
        public string PIDRECEIPTEVENT_ISISTASYONUTIPI { get; set; }
        public int PIDRECEIPTEVENT_ISISTASYONUID { get; set; }
        public int PIDRECEIPTEVENT_PID { get; set; }
        public System.DateTime PIDRECEIPTEVENT_KAYITTARIHI { get; set; }
        public Nullable<double> PIDRECEIPTEVENT_STARTQUANTITY { get; set; }
        public Nullable<double> PIDRECEIPTEVENT_FINISHQUANTITY { get; set; }
        public string PIDRECEIPTEVENT_HATANO { get; set; }
        public string PIDRECEIPTEVENT_HATAADI { get; set; }
        public Nullable<int> PIDRECEIPTEVENT_HATAREF { get; set; }
        public string PIDRECEIPTEVENT_PERSONELNO { get; set; }
        public string PIDRECEIPTEVENT_PERSONELADI { get; set; }
        public string PIDRECEIPTEVENT_PERSONELTIPI { get; set; }
        public Nullable<int> PIDRECEIPTEVENT_PERSONELID { get; set; }
        public string PIDRECEIPTEVENT_ACIKLAMA { get; set; }
    }
}
