//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PWORKCENTERCALSEN
    {
        public int PWORKCENTERCALSEN_SIRKETID { get; set; }
        public int PWORKCENTERCALSEN_PORDERSSENERIOID { get; set; }
        public string PWORKCENTERCALSEN_ISMERKEZINO { get; set; }
        public string PWORKCENTERCALSEN_ISMERKEZIADI { get; set; }
        public string PWORKCENTERCALSEN_ISMERKEZITIPI { get; set; }
        public int PWORKCENTERCALSEN_ISMERKEZIID { get; set; }
        public System.DateTime PWORKCENTERCALSEN_BASLANGICTARIHI { get; set; }
        public Nullable<System.DateTime> PWORKCENTERCALSEN_BITISTARIHI { get; set; }
        public Nullable<bool> PWORKCENTERCALSEN_ISWORKING { get; set; }
    }
}
