//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PPROTECCONTTI
    {
        public int PPROTECCONTTI_SIRKETID { get; set; }
        public int PPROTECCONTTI_DONEMID { get; set; }
        public int PPROTECCONTTI_FISID { get; set; }
        public int PPROTECCONTTI_CONTDEFITEMNO { get; set; }
        public string PPROTECCONTTI_REZERVEC1 { get; set; }
        public string PPROTECCONTTI_REZERVEC2 { get; set; }
        public string PPROTECCONTTI_REZERVEC3 { get; set; }
        public string PPROTECCONTTI_REZERVEC4 { get; set; }
        public string PPROTECCONTTI_REZERVEC5 { get; set; }
        public string PPROTECCONTTI_REZERVEC6 { get; set; }
        public string PPROTECCONTTI_OZELKOD1 { get; set; }
        public string PPROTECCONTTI_OZELKOD2 { get; set; }
        public Nullable<double> PPROTECCONTTI_REJECTQUANTITY { get; set; }
        public string PPROTECCONTTI_PCONTDEVICENO { get; set; }
        public string PPROTECCONTTI_PCONTDEVICENAME { get; set; }
        public Nullable<int> PPROTECCONTTI_PCONTDEVICEID { get; set; }
        public string PPROTECCONTTI_ACIKLAMA2 { get; set; }
        public Nullable<int> PPROTECCONTTI_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PPROTECCONTTI_KAYITTARIHI { get; set; }
        public Nullable<int> PPROTECCONTTI_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PPROTECCONTTI_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PPROTECCONTTI_UYARIID { get; set; }
    }
}
