//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PLINESTOPREL
    {
        public int PLINESTOPREL_SIRKETID { get; set; }
        public int PLINESTOPREL_PLINEID { get; set; }
        public string PLINESTOPREL_ISISTASYONUNO { get; set; }
        public string PLINESTOPREL_ISISTASYONUADI { get; set; }
        public string PLINESTOPREL_ISISTASYONUTIPI { get; set; }
        public int PLINESTOPREL_ISISTASYONUID { get; set; }
        public Nullable<int> PLINESTOPREL_CAUSEPWORKSTATIONID { get; set; }
        public string PLINESTOPREL_DURUSNEDENNO { get; set; }
        public string PLINESTOPREL_DURUSNEDENADI { get; set; }
        public string PLINESTOPREL_DURUSNEDENTIPI { get; set; }
        public Nullable<int> PLINESTOPREL_DURUSNEDENREF { get; set; }
        public Nullable<System.DateTime> PLINESTOPREL_STARTTIME { get; set; }
        public Nullable<System.DateTime> PLINESTOPREL_BITISSAAT { get; set; }
    }
}
