//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PCOSTWORKSTATION
    {
        public int PCOSTWORKSTATION_SIRKETID { get; set; }
        public int PCOSTWORKSTATION_DONEMID { get; set; }
        public int PCOSTWORKSTATION_PCOSTPERIODID { get; set; }
        public string PCOSTWORKSTATION_ISISTASYONUNO { get; set; }
        public string PCOSTWORKSTATION_ISISTASYONUADI { get; set; }
        public string PCOSTWORKSTATION_ISISTASYONUTIPI { get; set; }
        public int PCOSTWORKSTATION_ISISTASYONUID { get; set; }
        public int PCOSTWORKSTATION_PCOSTTYPEID { get; set; }
        public string PCOSTWORKSTATION_HESAPNO { get; set; }
        public string PCOSTWORKSTATION_HESAPADI { get; set; }
        public string PCOSTWORKSTATION_HESAPTIPI { get; set; }
        public int PCOSTWORKSTATION_HESAPID { get; set; }
        public string PCOSTWORKSTATION_MASRAFYERKODU { get; set; }
        public string PCOSTWORKSTATION_MASRAFYERADI { get; set; }
        public int PCOSTWORKSTATION_MASRAFYERREF { get; set; }
        public Nullable<double> PCOSTWORKSTATION_CALDURATION { get; set; }
        public Nullable<double> PCOSTWORKSTATION_ACTUALDURATION { get; set; }
        public Nullable<double> PCOSTWORKSTATION_TUTAR { get; set; }
        public Nullable<double> PCOSTWORKSTATION_FIYAT { get; set; }
        public Nullable<double> PCOSTWORKSTATION_PRICEFORECAST { get; set; }
        public Nullable<double> PCOSTWORKSTATION_TOTALFORECAST { get; set; }
        public Nullable<decimal> PCOSTWORKSTATION_BORC { get; set; }
        public Nullable<decimal> PCOSTWORKSTATION_ALACAK { get; set; }
        public string PCOSTWORKSTATION_OPPACCNO { get; set; }
        public string PCOSTWORKSTATION_OPPACCNAME { get; set; }
        public string PCOSTWORKSTATION_OPPACCTYPE { get; set; }
        public Nullable<int> PCOSTWORKSTATION_ACCIDOPP { get; set; }
        public string PCOSTWORKSTATION_OPPACCCOSTCENTERNO { get; set; }
        public string PCOSTWORKSTATION_OPPACCCOSTCENTERNAME { get; set; }
        public Nullable<int> PCOSTWORKSTATION_ACCCOSTCENTERIDOPP { get; set; }
        public string PCOSTWORKSTATION_EXPACCNO { get; set; }
        public string PCOSTWORKSTATION_EXPACCNAME { get; set; }
        public string PCOSTWORKSTATION_EXPACCTYPE { get; set; }
        public Nullable<int> PCOSTWORKSTATION_ACCIDEXP { get; set; }
        public Nullable<int> PCOSTWORKSTATION_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PCOSTWORKSTATION_KAYITTARIHI { get; set; }
        public Nullable<int> PCOSTWORKSTATION_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PCOSTWORKSTATION_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PCOSTWORKSTATION_UYARIID { get; set; }
    }
}
