//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PTECCONTM
    {
        public int PTECCONTM_SIRKETID { get; set; }
        public int PTECCONTM_DONEMID { get; set; }
        public int PTECCONTM_FISID { get; set; }
        public int PTECCONTM_ROOTITEMNO { get; set; }
        public string PTECCONTM_LOTNO { get; set; }
        public string PTECCONTM_KARSILOTNO { get; set; }
        public string PTECCONTM_BATCHNO { get; set; }
        public int PTECCONTM_STOKLOTID { get; set; }
        public int PTECCONTM_CONTDEFITEMNO { get; set; }
        public short PTECCONTM_PARCANO { get; set; }
        public string PTECCONTM_MEASURE { get; set; }
        public Nullable<int> PTECCONTM_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PTECCONTM_KAYITTARIHI { get; set; }
        public Nullable<int> PTECCONTM_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PTECCONTM_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PTECCONTM_UYARIID { get; set; }
    }
}
