//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PTECCONTD
    {
        public int PTECCONTD_SIRKETID { get; set; }
        public int PTECCONTD_DONEMID { get; set; }
        public int PTECCONTD_FISID { get; set; }
        public int PTECCONTD_ROOTITEMNO { get; set; }
        public int PTECCONTD_CONTDEFITEMNO { get; set; }
        public string PTECCONTD_STOKNO { get; set; }
        public string PTECCONTD_STOKADI { get; set; }
        public string PTECCONTD_STOKTIPI { get; set; }
        public Nullable<int> PTECCONTD_STOKID { get; set; }
        public string PTECCONTD_NITELIKADI { get; set; }
        public Nullable<int> PTECCONTD_NITELIKID { get; set; }
        public Nullable<double> PTECCONTD_MIKTAR { get; set; }
        public string PTECCONTD_STATUSNAME { get; set; }
        public Nullable<int> PTECCONTD_DURUM { get; set; }
        public Nullable<int> PTECCONTD_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PTECCONTD_KAYITTARIHI { get; set; }
        public Nullable<int> PTECCONTD_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PTECCONTD_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PTECCONTD_UYARIID { get; set; }
    }
}
