//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PWRPINFO
    {
        public int PWRPINFO_SIRKETID { get; set; }
        public int PWRPINFO_PDSGNCARDID { get; set; }
        public int PWRPINFO_PARCANO { get; set; }
        public Nullable<int> PWRPINFO_STOKID { get; set; }
        public string PWRPINFO_WRPVARIANT { get; set; }
        public string PWRPINFO_WRPNAME { get; set; }
        public Nullable<int> PWRPINFO_PWRPCARDID { get; set; }
        public string PWRPINFO_ACIKLAMA { get; set; }
        public Nullable<int> PWRPINFO_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PWRPINFO_KAYITTARIHI { get; set; }
        public Nullable<int> PWRPINFO_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PWRPINFO_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PWRPINFO_UYARIID { get; set; }
    }
}
