//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PMOULDS
    {
        public int PMOULDS_SIRKETID { get; set; }
        public int PMOULDS_PMOULDSID { get; set; }
        public string PMOULDS_PMOULDSNO { get; set; }
        public string PMOULDS_PMOULDSNAME { get; set; }
        public string PMOULDS_PMOULDSTYPENAME { get; set; }
        public Nullable<int> PMOULDS_PMOULDSTYPE { get; set; }
        public string PMOULDS_CARINO { get; set; }
        public string PMOULDS_CARIADI { get; set; }
        public string PMOULDS_CARITIPI { get; set; }
        public Nullable<int> PMOULDS_CARIID { get; set; }
        public Nullable<System.DateTime> PMOULDS_TARIH { get; set; }
        public string PMOULDS_GRUPKODU { get; set; }
        public string PMOULDS_OZELKOD1 { get; set; }
        public string PMOULDS_OZELKOD2 { get; set; }
        public string PMOULDS_PROJENO { get; set; }
        public string PMOULDS_PROJEADI { get; set; }
        public Nullable<int> PMOULDS_PROJEID { get; set; }
        public string PMOULDS_STATUSNAME { get; set; }
        public Nullable<int> PMOULDS_DURUM { get; set; }
        public Nullable<System.DateTime> PMOULDS_SEVKTARIHI { get; set; }
        public string PMOULDS_MOULDDIMENSION { get; set; }
        public string PMOULDS_PRESSINFORMATION { get; set; }
        public Nullable<int> PMOULDS_OPERATIONNUMBER { get; set; }
        public string PMOULDS_MATERAIALDESC { get; set; }
        public string PMOULDS_SHEETIRONTHICK { get; set; }
        public string PMOULDS_BANDWIDTH { get; set; }
        public string PMOULDS_STEPDESC { get; set; }
        public Nullable<int> PMOULDS_EMPLOYEEIDDESIGNER { get; set; }
        public Nullable<int> PMOULDS_EMPLOYEEIDPROJECT { get; set; }
        public Nullable<int> PMOULDS_EMPLOYEEIDCONTROL { get; set; }
        public Nullable<int> PMOULDS_EMPLOYEEIDAPPROVE { get; set; }
        public string PMOULDS_EKIPMANNO { get; set; }
        public string PMOULDS_EKIPMANADI { get; set; }
        public string PMOULDS_EKIPMANTIPI { get; set; }
        public Nullable<int> PMOULDS_EKIPMANID { get; set; }
        public Nullable<int> PMOULDS_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PMOULDS_KAYITTARIHI { get; set; }
        public Nullable<int> PMOULDS_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PMOULDS_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PMOULDS_UYARIID { get; set; }
    }
}
