//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PPRODUCTPLANWSITEM
    {
        public int PPRODUCTPLANWSITEM_SIRKETID { get; set; }
        public int PPRODUCTPLANWSITEM_DONEMID { get; set; }
        public int PPRODUCTPLANWSITEM_PID { get; set; }
        public string PPRODUCTPLANWSITEM_PJOBORDERRECEIPTNO { get; set; }
        public int PPRODUCTPLANWSITEM_ISEMRIID { get; set; }
        public Nullable<double> PPRODUCTPLANWSITEM_MIKTAR { get; set; }
        public Nullable<double> PPRODUCTPLANWSITEM_QUANTITY2 { get; set; }
        public Nullable<double> PPRODUCTPLANWSITEM_QUANTITY3 { get; set; }
        public Nullable<bool> PPRODUCTPLANWSITEM_RECEIPTPOST { get; set; }
        public Nullable<int> PPRODUCTPLANWSITEM_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PPRODUCTPLANWSITEM_KAYITTARIHI { get; set; }
        public Nullable<int> PPRODUCTPLANWSITEM_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PPRODUCTPLANWSITEM_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PPRODUCTPLANWSITEM_UYARIID { get; set; }
    }
}
