//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_POFFER
    {
        public int POFFER_SIRKETID { get; set; }
        public int POFFER_POFFERID { get; set; }
        public string POFFER_POFFERNO { get; set; }
        public Nullable<System.DateTime> POFFER_TARIH { get; set; }
        public string POFFER_STOKNO { get; set; }
        public string POFFER_STOKADI { get; set; }
        public string POFFER_STOKTIPI { get; set; }
        public Nullable<int> POFFER_STOKID { get; set; }
        public string POFFER_PARTNAME { get; set; }
        public string POFFER_CUSTOMERREFERANS { get; set; }
        public string POFFER_PICTURENO { get; set; }
        public string POFFER_CARINO { get; set; }
        public string POFFER_CARIADI { get; set; }
        public string POFFER_CARITIPI { get; set; }
        public Nullable<int> POFFER_CARIID { get; set; }
        public string POFFER_CUSTOMERNAME { get; set; }
        public string POFFER_ACIKLAMA { get; set; }
        public string POFFER_DOVIZ { get; set; }
        public Nullable<double> POFFER_DOVIZKUR { get; set; }
        public Nullable<double> POFFER_SALESTOTAL { get; set; }
        public Nullable<double> POFFER_SALESCURRTOTAL { get; set; }
        public Nullable<double> POFFER_MALIYETTUTAR { get; set; }
        public Nullable<double> POFFER_COSTCURRTOTAL { get; set; }
        public Nullable<double> POFFER_MATTOTAL { get; set; }
        public Nullable<double> POFFER_MATCURRTOTAL { get; set; }
        public Nullable<double> POFFER_PROCESSTOTAL { get; set; }
        public Nullable<double> POFFER_PROCESSCURRTOTAL { get; set; }
        public Nullable<double> POFFER_OTHERTOTAL { get; set; }
        public Nullable<double> POFFER_OTHERCURRTOTAL { get; set; }
        public Nullable<double> POFFER_SALESPRICE { get; set; }
        public Nullable<double> POFFER_SALESCURRPRICE { get; set; }
        public Nullable<double> POFFER_MALIYETFIYAT { get; set; }
        public Nullable<double> POFFER_COSTCURRPRICE { get; set; }
        public Nullable<double> POFFER_ANNUALUSAGE { get; set; }
        public Nullable<double> POFFER_PROJECTLIFE { get; set; }
        public Nullable<double> POFFER_PROFITPERCENT { get; set; }
        public Nullable<double> POFFER_PROFITTOTAL { get; set; }
        public Nullable<double> POFFER_NETWEIGHT { get; set; }
        public Nullable<int> POFFER_DELIVERYFREQ { get; set; }
        public Nullable<double> POFFER_DELIVERYQUANTITY { get; set; }
        public Nullable<double> POFFER_DELIVERYWEIGHT { get; set; }
        public Nullable<double> POFFER_CASEINQUANTITY { get; set; }
        public Nullable<double> POFFER_CASEWEIGHT { get; set; }
        public Nullable<double> POFFER_PALETTECASEQUANTITY { get; set; }
        public Nullable<double> POFFER_PALETTEWEIGHT { get; set; }
        public Nullable<double> POFFER_PALETTEQUANTITY { get; set; }
        public Nullable<double> POFFER_CASEQUANTITY { get; set; }
        public Nullable<int> POFFER_STKFIYATTIPID { get; set; }
        public byte[] POFFER_STOKRESIM { get; set; }
        public Nullable<System.DateTime> POFFER_REQUESTDATE { get; set; }
        public Nullable<System.DateTime> POFFER_SEVKTARIHI { get; set; }
        public Nullable<System.DateTime> POFFER_VADE { get; set; }
        public Nullable<bool> POFFER_APPROWED { get; set; }
        public Nullable<int> POFFER_OFFERSTATUS { get; set; }
        public string POFFER_YETKILIADI { get; set; }
        public string POFFER_GRUPKODU { get; set; }
        public string POFFER_OZELKOD1 { get; set; }
        public string POFFER_OZELKOD2 { get; set; }
        public string POFFER_PERSONELNO { get; set; }
        public string POFFER_PERSONELADI { get; set; }
        public string POFFER_PERSONELTIPI { get; set; }
        public Nullable<int> POFFER_PERSONELID { get; set; }
        public string POFFER_PROJENO { get; set; }
        public string POFFER_PROJEADI { get; set; }
        public Nullable<int> POFFER_PROJEID { get; set; }
        public byte[] POFFER_RESIM { get; set; }
        public string POFFER_STATUSNAME { get; set; }
        public Nullable<short> POFFER_DURUM { get; set; }
        public Nullable<int> POFFER_NOTEID { get; set; }
        public Nullable<System.DateTime> POFFER_IPTALTARIHI { get; set; }
        public Nullable<int> POFFER_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> POFFER_KAYITTARIHI { get; set; }
        public Nullable<int> POFFER_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> POFFER_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> POFFER_UYARIID { get; set; }
    }
}
