//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_PFURNITUREMODWS
    {
        public int PFURNITUREMODWS_SIRKETID { get; set; }
        public int PFURNITUREMODWS_PFURNITUREMODID { get; set; }
        public int PFURNITUREMODWS_PARCANO { get; set; }
        public int PFURNITUREMODWS_ITEMNOPROC { get; set; }
        public string PFURNITUREMODWS_ISLEMNO { get; set; }
        public string PFURNITUREMODWS_ISLEMADI { get; set; }
        public string PFURNITUREMODWS_ISLEMTIPI { get; set; }
        public Nullable<int> PFURNITUREMODWS_ISLEMID { get; set; }
        public string PFURNITUREMODWS_NITELIKADI { get; set; }
        public Nullable<int> PFURNITUREMODWS_NITELIKID { get; set; }
        public string PFURNITUREMODWS_ISISTASYONUNO { get; set; }
        public string PFURNITUREMODWS_ISISTASYONUADI { get; set; }
        public string PFURNITUREMODWS_ISISTASYONUTIPI { get; set; }
        public Nullable<int> PFURNITUREMODWS_ISISTASYONUID { get; set; }
        public Nullable<int> PFURNITUREMODWS_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> PFURNITUREMODWS_KAYITTARIHI { get; set; }
        public Nullable<int> PFURNITUREMODWS_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> PFURNITUREMODWS_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> PFURNITUREMODWS_UYARIID { get; set; }
    }
}
