//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_POFFERMATCOST
    {
        public int POFFERMATCOST_SIRKETID { get; set; }
        public int POFFERMATCOST_POFFERID { get; set; }
        public int POFFERMATCOST_PARCANO { get; set; }
        public string POFFERMATCOST_ACIKLAMA { get; set; }
        public Nullable<double> POFFERMATCOST_ORAN { get; set; }
        public Nullable<double> POFFERMATCOST_TUTAR { get; set; }
        public Nullable<double> POFFERMATCOST_OFFERTOTAL { get; set; }
        public Nullable<double> POFFERMATCOST_RATIO { get; set; }
        public Nullable<int> POFFERMATCOST_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> POFFERMATCOST_KAYITTARIHI { get; set; }
        public Nullable<int> POFFERMATCOST_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> POFFERMATCOST_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> POFFERMATCOST_UYARIID { get; set; }
    }
}
