//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_RECETEROTA
    {
        public int RECETEROTA_SIRKETID { get; set; }
        public int RECETEROTA_URUNAGACID { get; set; }
        public int RECETEROTA_PARCANO { get; set; }
        public string RECETEROTA_ISLEMNO { get; set; }
        public string RECETEROTA_ISLEMADI { get; set; }
        public string RECETEROTA_ISLEMTIPI { get; set; }
        public Nullable<int> RECETEROTA_ISLEMID { get; set; }
        public Nullable<decimal> RECETEROTA_SURE { get; set; }
        public Nullable<decimal> RECETEROTA_SETUPSURESI { get; set; }
        public string RECETEROTA_ISISTASYONUNO { get; set; }
        public string RECETEROTA_ISISTASYONUADI { get; set; }
        public string RECETEROTA_ISISTASYONUTIPI { get; set; }
        public Nullable<int> RECETEROTA_ISISTASYONUID { get; set; }
        public string RECETEROTA_ISMERKEZINO { get; set; }
        public string RECETEROTA_ISMERKEZIADI { get; set; }
        public string RECETEROTA_ISMERKEZITIPI { get; set; }
        public Nullable<int> RECETEROTA_ISMERKEZIID { get; set; }
        public string RECETEROTA_EKIPMANNO { get; set; }
        public string RECETEROTA_EKIPMANADI { get; set; }
        public string RECETEROTA_EKIPMANTIPI { get; set; }
        public Nullable<int> RECETEROTA_EKIPMANID { get; set; }
        public Nullable<short> RECETEROTA_PERSONELSAYISI { get; set; }
        public Nullable<int> RECETEROTA_PERSONELGOREVID { get; set; }
        public string RECETEROTA_NOTLAR { get; set; }
    }
}
