//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_RECETE
    {
        public int RECETE_SIRKETID { get; set; }
        public int RECETE_URUNAGACID { get; set; }
        public string RECETE_STOKNO { get; set; }
        public string RECETE_STOKADI { get; set; }
        public string RECETE_STOKTIPI { get; set; }
        public Nullable<int> RECETE_STOKID { get; set; }
        public string RECETE_NITELIKADI { get; set; }
        public Nullable<int> RECETE_NITELIKID { get; set; }
        public string RECETE_GRUPKODU { get; set; }
        public string RECETE_OZELKOD1 { get; set; }
        public string RECETE_OZELKOD2 { get; set; }
        public string RECETE_PERSONELNO { get; set; }
        public string RECETE_PERSONELADI { get; set; }
        public string RECETE_PERSONELTIPI { get; set; }
        public Nullable<int> RECETE_PERSONELID { get; set; }
        public string RECETE_STATUSNAME { get; set; }
        public Nullable<short> RECETE_DURUM { get; set; }
        public Nullable<int> RECETE_NOTEID { get; set; }
        public Nullable<double> RECETE_MIKTAR { get; set; }
        public Nullable<double> RECETE_QUANTITY2 { get; set; }
        public Nullable<double> RECETE_QUANTITY3 { get; set; }
        public Nullable<int> RECETE_MALZEMEDEPOID { get; set; }
        public Nullable<int> RECETE_MAMULDEPOID { get; set; }
        public Nullable<int> RECETE_KAYIPDEPOID { get; set; }
        public Nullable<System.DateTime> RECETE_IPTALTARIHI { get; set; }
        public string RECETE_ACIKLAMA { get; set; }
        public Nullable<int> RECETE_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> RECETE_KAYITTARIHI { get; set; }
        public Nullable<int> RECETE_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> RECETE_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> RECETE_UYARIID { get; set; }
    }
}
