//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_REPORTS
    {
        public int REPORTS_SIRKETID { get; set; }
        public int REPORTS_DONEMID { get; set; }
        public int REPORTS_RAPORID { get; set; }
        public Nullable<int> REPORTS_RAPORBOLUMU { get; set; }
        public string REPORTS_SYSTEMDESCTEXT { get; set; }
        public string REPORTS_USERDESCTEXT { get; set; }
        public Nullable<int> REPORTS_SECTIONORDER { get; set; }
        public string REPORTS_RAPORADI { get; set; }
        public string REPORTS_GRUPKODU { get; set; }
        public string REPORTS_RAPORBASLIGI { get; set; }
        public Nullable<bool> REPORTS_USRDEF { get; set; }
        public string REPORTS_SQLTEXT { get; set; }
        public string REPORTS_FROMTEXT { get; set; }
        public string REPORTS_WHERETEXT { get; set; }
        public string REPORTS_GROUPBYTEXT { get; set; }
        public string REPORTS_ORDERBYTEXT { get; set; }
        public string REPORTS_HAVINGTEXT { get; set; }
        public string REPORTS_COMPUTETEXT { get; set; }
        public string REPORTS_FILTERTEXT { get; set; }
        public Nullable<int> REPORTS_KAYNAK { get; set; }
        public Nullable<int> REPORTS_KULLANICIID { get; set; }
        public string REPORTS_PASSWORD { get; set; }
        public Nullable<int> REPORTS_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> REPORTS_KAYITTARIHI { get; set; }
        public Nullable<int> REPORTS_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> REPORTS_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> REPORTS_UYARIID { get; set; }
    }
}
