//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_SEVKIYATBASLIK
    {
        public int SEVKIYATBASLIK_SIRKETID { get; set; }
        public int SEVKIYATBASLIK_DONEMID { get; set; }
        public int SEVKIYATBASLIK_FISID { get; set; }
        public string SEVKIYATBASLIK_ISLEMTIPIADI { get; set; }
        public Nullable<short> SEVKIYATBASLIK_ISLEMTIPI { get; set; }
        public string SEVKIYATBASLIK_FISNO { get; set; }
        public Nullable<System.DateTime> SEVKIYATBASLIK_TARIH { get; set; }
        public string SEVKIYATBASLIK_GRUPKODU { get; set; }
        public string SEVKIYATBASLIK_OZELKOD1 { get; set; }
        public string SEVKIYATBASLIK_OZELKOD2 { get; set; }
        public string SEVKIYATBASLIK_TRANSCODE { get; set; }
        public string SEVKIYATBASLIK_PERSONELNO { get; set; }
        public string SEVKIYATBASLIK_PERSONELADI { get; set; }
        public string SEVKIYATBASLIK_PERSONELTIPI { get; set; }
        public Nullable<int> SEVKIYATBASLIK_PERSONELID { get; set; }
        public string SEVKIYATBASLIK_STATUSNAME { get; set; }
        public Nullable<short> SEVKIYATBASLIK_DURUM { get; set; }
        public Nullable<int> SEVKIYATBASLIK_NOTEID { get; set; }
        public Nullable<System.DateTime> SEVKIYATBASLIK_IPTALTARIHI { get; set; }
        public string SEVKIYATBASLIK_ACIKLAMA { get; set; }
        public string SEVKIYATBASLIK_DOKUMANNO { get; set; }
        public Nullable<decimal> SEVKIYATBASLIK_TUTAR { get; set; }
        public string SEVKIYATBASLIK_DOVIZ { get; set; }
        public Nullable<System.DateTime> SEVKIYATBASLIK_DOVIZTARIHI { get; set; }
        public Nullable<double> SEVKIYATBASLIK_DOVIZKUR { get; set; }
        public Nullable<double> SEVKIYATBASLIK_DOVIZTUTAR { get; set; }
        public string SEVKIYATBASLIK_HARDOVIZI { get; set; }
        public Nullable<System.DateTime> SEVKIYATBASLIK_HARDOVIZTARIHI { get; set; }
        public Nullable<double> SEVKIYATBASLIK_HARDOVIZKUR { get; set; }
        public Nullable<decimal> SEVKIYATBASLIK_DOVIZHAR { get; set; }
        public string SEVKIYATBASLIK_VERGIDAIRESI { get; set; }
        public string SEVKIYATBASLIK_VERGINO { get; set; }
        public string SEVKIYATBASLIK_VERGISEHRI { get; set; }
        public Nullable<System.DateTime> SEVKIYATBASLIK_VADE { get; set; }
        public Nullable<short> SEVKIYATBASLIK_GUNVADE { get; set; }
        public Nullable<System.DateTime> SEVKIYATBASLIK_OPSIYONVADE { get; set; }
        public Nullable<short> SEVKIYATBASLIK_KATEGORIID { get; set; }
        public string SEVKIYATBASLIK_ODEMETIPIADI { get; set; }
        public Nullable<short> SEVKIYATBASLIK_ODEMETIPI { get; set; }
        public Nullable<bool> SEVKIYATBASLIK_IHRACKAYITLI { get; set; }
        public Nullable<double> SEVKIYATBASLIK_INDIRIMTUTAR1 { get; set; }
        public Nullable<decimal> SEVKIYATBASLIK_INDIRIMO1 { get; set; }
        public Nullable<double> SEVKIYATBASLIK_INDIRIMTUTAR2 { get; set; }
        public Nullable<decimal> SEVKIYATBASLIK_INDIRIMO2 { get; set; }
        public Nullable<decimal> SEVKIYATBASLIK_URUNTOPLAMI { get; set; }
        public Nullable<decimal> SEVKIYATBASLIK_TOPLAMINDIRIM { get; set; }
        public Nullable<decimal> SEVKIYATBASLIK_PRODUCTSUMOUTVAT { get; set; }
        public Nullable<decimal> SEVKIYATBASLIK_DISCOUNTSUMOUTVAT { get; set; }
        public Nullable<decimal> SEVKIYATBASLIK_BREAKTOTALOUTVAT { get; set; }
        public Nullable<decimal> SEVKIYATBASLIK_KDVTOPLAM { get; set; }
        public Nullable<decimal> SEVKIYATBASLIK_OTVTOPLAM { get; set; }
        public Nullable<decimal> SEVKIYATBASLIK_TEVKIFATVERGITOPLAMI { get; set; }
        public Nullable<bool> SEVKIYATBASLIK_MUHASEBEKONTROL { get; set; }
        public Nullable<double> SEVKIYATBASLIK_MALIYETFIYAT { get; set; }
        public Nullable<System.DateTime> SEVKIYATBASLIK_KDVVADE { get; set; }
        public Nullable<decimal> SEVKIYATBASLIK_YUVARLAMATUTARI { get; set; }
        public Nullable<decimal> SEVKIYATBASLIK_TEVKIFATCARPANI { get; set; }
        public Nullable<decimal> SEVKIYATBASLIK_TEVKIFATBOLENI { get; set; }
        public Nullable<decimal> SEVKIYATBASLIK_STOPAJRATE { get; set; }
        public Nullable<decimal> SEVKIYATBASLIK_STOPAJ { get; set; }
        public string SEVKIYATBASLIK_KASANO { get; set; }
        public string SEVKIYATBASLIK_KASAADI { get; set; }
        public string SEVKIYATBASLIK_KASATIPI { get; set; }
        public Nullable<int> SEVKIYATBASLIK_KASAID { get; set; }
        public string SEVKIYATBASLIK_DEPONO { get; set; }
        public string SEVKIYATBASLIK_DEPOADI { get; set; }
        public string SEVKIYATBASLIK_DEPOTIPI { get; set; }
        public Nullable<int> SEVKIYATBASLIK_DEPOREF { get; set; }
        public string SEVKIYATBASLIK_CARINO { get; set; }
        public string SEVKIYATBASLIK_CARIADI { get; set; }
        public string SEVKIYATBASLIK_CARITIPI { get; set; }
        public Nullable<int> SEVKIYATBASLIK_CARIID { get; set; }
        public string SEVKIYATBASLIK_BANKANO { get; set; }
        public string SEVKIYATBASLIK_BANKAADI { get; set; }
        public string SEVKIYATBASLIK_BANKATIPI { get; set; }
        public Nullable<int> SEVKIYATBASLIK_BANKAID { get; set; }
        public Nullable<decimal> SEVKIYATBASLIK_BANKTOTAL { get; set; }
        public string SEVKIYATBASLIK_ADI1 { get; set; }
        public string SEVKIYATBASLIK_ADI2 { get; set; }
        public Nullable<int> SEVKIYATBASLIK_ADRESID { get; set; }
        public Nullable<System.DateTime> SEVKIYATBASLIK_SEVKTARIHI { get; set; }
        public Nullable<int> SEVKIYATBASLIK_SEVKCARIID { get; set; }
        public string SEVKIYATBASLIK_SEVKADI { get; set; }
        public string SEVKIYATBASLIK_SEVKADI2 { get; set; }
        public Nullable<int> SEVKIYATBASLIK_SEVKADRESI { get; set; }
        public string SEVKIYATBASLIK_ACIKLAMA1 { get; set; }
        public string SEVKIYATBASLIK_ACIKLAMA2 { get; set; }
        public string SEVKIYATBASLIK_PROJENO { get; set; }
        public string SEVKIYATBASLIK_PROJEADI { get; set; }
        public Nullable<int> SEVKIYATBASLIK_PROJEID { get; set; }
        public string SEVKIYATBASLIK_MASRAFYERKODU { get; set; }
        public string SEVKIYATBASLIK_MASRAFYERADI { get; set; }
        public Nullable<int> SEVKIYATBASLIK_MASRAFYERREF { get; set; }
        public string SEVKIYATBASLIK_DOVIZHARTIPIADI { get; set; }
        public Nullable<bool> SEVKIYATBASLIK_DOVIZHARTIPI { get; set; }
        public string SEVKIYATBASLIK_RECEIPTTYPENAME { get; set; }
        public Nullable<int> SEVKIYATBASLIK_RECEIPTTYPE { get; set; }
        public Nullable<int> SEVKIYATBASLIK_SID { get; set; }
        public string SEVKIYATBASLIK_PAKETADI { get; set; }
        public Nullable<int> SEVKIYATBASLIK_STOKPAKETID { get; set; }
        public Nullable<short> SEVKIYATBASLIK_PARTCOUNT { get; set; }
        public Nullable<short> SEVKIYATBASLIK_GLBPAYMENTID { get; set; }
        public Nullable<double> SEVKIYATBASLIK_SHIPPING { get; set; }
        public Nullable<int> SEVKIYATBASLIK_ACCRECEIPTID { get; set; }
        public Nullable<bool> SEVKIYATBASLIK_MANUELVAT { get; set; }
        public Nullable<int> SEVKIYATBASLIK_STKFIYATTIPID { get; set; }
        public string SEVKIYATBASLIK_BUDGETNO { get; set; }
        public string SEVKIYATBASLIK_BUDGETNAME { get; set; }
        public string SEVKIYATBASLIK_BUDGETTYPE { get; set; }
        public Nullable<int> SEVKIYATBASLIK_BUDGETID { get; set; }
        public Nullable<double> SEVKIYATBASLIK_BREAKTOTAL { get; set; }
        public Nullable<bool> SEVKIYATBASLIK_SENDDOC { get; set; }
        public string SEVKIYATBASLIK_CRMCONTACTSFULLNAME { get; set; }
        public Nullable<int> SEVKIYATBASLIK_CRMCONTACTSID { get; set; }
        public Nullable<decimal> SEVKIYATBASLIK_CURRDISCOUNTTOTAL1 { get; set; }
        public Nullable<double> SEVKIYATBASLIK_BONUS { get; set; }
        public Nullable<int> SEVKIYATBASLIK_RECEIPTIDRELATION { get; set; }
        public string SEVKIYATBASLIK_DOCUMENTTYPENAME { get; set; }
        public string SEVKIYATBASLIK_DOCUMENTTYPE { get; set; }
        public Nullable<System.DateTime> SEVKIYATBASLIK_ORTALAMOPSIYON { get; set; }
        public Nullable<decimal> SEVKIYATBASLIK_BABSTOTAL { get; set; }
        public string SEVKIYATBASLIK_IHRACATREASON { get; set; }
        public string SEVKIYATBASLIK_EDESGUID { get; set; }
        public string SEVKIYATBASLIK_EEDESGUID { get; set; }
        public string SEVKIYATBASLIK_EDESSTATUS { get; set; }
        public string SEVKIYATBASLIK_EDESTYPENAME { get; set; }
        public Nullable<int> SEVKIYATBASLIK_EDESTYPE { get; set; }
        public string SEVKIYATBASLIK_EDESSTATUSDESC { get; set; }
        public string SEVKIYATBASLIK_YKDEVICENO { get; set; }
        public string SEVKIYATBASLIK_YKZNO { get; set; }
        public string SEVKIYATBASLIK_YKSICNO { get; set; }
        public string SEVKIYATBASLIK_YKFISNO { get; set; }
        public string SEVKIYATBASLIK_CHECKMD5SUM { get; set; }
        public Nullable<int> SEVKIYATBASLIK_CARRIERID { get; set; }
        public string SEVKIYATBASLIK_CARRIERNAME { get; set; }
        public string SEVKIYATBASLIK_CARRIERNO { get; set; }
        public string SEVKIYATBASLIK_DRIVERIDS { get; set; }
        public string SEVKIYATBASLIK_VECHICLEIDS { get; set; }
        public string SEVKIYATBASLIK_DORSEIDS { get; set; }
        public Nullable<int> SEVKIYATBASLIK_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> SEVKIYATBASLIK_KAYITTARIHI { get; set; }
        public Nullable<int> SEVKIYATBASLIK_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> SEVKIYATBASLIK_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> SEVKIYATBASLIK_UYARIID { get; set; }
    }
}
