//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_STOCKPRICETYPEACCESS
    {
        public int STOCKPRICETYPEACCESS_SIRKETID { get; set; }
        public int STOCKPRICETYPEACCESS_KULLANICIID { get; set; }
        public short STOCKPRICETYPEACCESS_STKFIYATTIPID { get; set; }
        public Nullable<int> STOCKPRICETYPEACCESS_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> STOCKPRICETYPEACCESS_KAYITTARIHI { get; set; }
        public Nullable<int> STOCKPRICETYPEACCESS_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> STOCKPRICETYPEACCESS_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> STOCKPRICETYPEACCESS_UYARIID { get; set; }
    }
}
