//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_STOCKDYNPLCITEM
    {
        public int STOCKDYNPLCITEM_SIRKETID { get; set; }
        public int STOCKDYNPLCITEM_STOCKDYNPLCID { get; set; }
        public int STOCKDYNPLCITEM_TREEID { get; set; }
        public Nullable<int> STOCKDYNPLCITEM_USTREF { get; set; }
        public string STOCKDYNPLCITEM_STOKNO { get; set; }
        public string STOCKDYNPLCITEM_STOKADI { get; set; }
        public string STOCKDYNPLCITEM_STOKTIPI { get; set; }
        public Nullable<int> STOCKDYNPLCITEM_STOKID { get; set; }
        public string STOCKDYNPLCITEM_NITELIKADI { get; set; }
        public Nullable<int> STOCKDYNPLCITEM_NITELIKID { get; set; }
        public Nullable<double> STOCKDYNPLCITEM_MIKTAR { get; set; }
        public Nullable<double> STOCKDYNPLCITEM_QUANTITY2 { get; set; }
        public Nullable<double> STOCKDYNPLCITEM_QUANTITY3 { get; set; }
        public Nullable<int> STOCKDYNPLCITEM_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> STOCKDYNPLCITEM_KAYITTARIHI { get; set; }
        public Nullable<int> STOCKDYNPLCITEM_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> STOCKDYNPLCITEM_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> STOCKDYNPLCITEM_UYARIID { get; set; }
    }
}
