//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_STOCKTRANSMATRIX
    {
        public int STOCKTRANSMATRIX_SIRKETID { get; set; }
        public int STOCKTRANSMATRIX_DONEMID { get; set; }
        public string STOCKTRANSMATRIX_STOKNO { get; set; }
        public string STOCKTRANSMATRIX_STOKTIPI { get; set; }
        public string STOCKTRANSMATRIX_STOKADI { get; set; }
        public int STOCKTRANSMATRIX_STOKID { get; set; }
        public System.DateTime STOCKTRANSMATRIX_TARIH { get; set; }
        public int STOCKTRANSMATRIX_PARCANO { get; set; }
        public int STOCKTRANSMATRIX_MATRIXDEFIDCOL { get; set; }
        public int STOCKTRANSMATRIX_MATRIXDEFIDROW { get; set; }
        public int STOCKTRANSMATRIX_KAYNAK { get; set; }
        public int STOCKTRANSMATRIX_KAYNAKID { get; set; }
        public int STOCKTRANSMATRIX_ROOTITEMNO { get; set; }
        public Nullable<double> STOCKTRANSMATRIX_GIRISMIKTARI { get; set; }
        public Nullable<double> STOCKTRANSMATRIX_CIKISMIKTARI { get; set; }
    }
}
