//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_SALESSYSTEMPRICE
    {
        public int SALESSYSTEMPRICE_SIRKETID { get; set; }
        public int SALESSYSTEMPRICE_PARCANO { get; set; }
        public Nullable<double> SALESSYSTEMPRICE_MINPRICE { get; set; }
        public Nullable<double> SALESSYSTEMPRICE_MAXPRICE { get; set; }
        public string SALESSYSTEMPRICE_DOVIZ { get; set; }
        public Nullable<double> SALESSYSTEMPRICE_KDVORANI { get; set; }
        public Nullable<int> SALESSYSTEMPRICE_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> SALESSYSTEMPRICE_KAYITTARIHI { get; set; }
        public Nullable<int> SALESSYSTEMPRICE_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> SALESSYSTEMPRICE_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> SALESSYSTEMPRICE_UYARIID { get; set; }
    }
}
