//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_SATISTEKLIFBASLIK
    {
        public int SATISTEKLIFBASLIK_SIRKETID { get; set; }
        public int SATISTEKLIFBASLIK_DONEMID { get; set; }
        public int SATISTEKLIFBASLIK_FISID { get; set; }
        public string SATISTEKLIFBASLIK_ISLEMTIPIADI { get; set; }
        public Nullable<short> SATISTEKLIFBASLIK_ISLEMTIPI { get; set; }
        public string SATISTEKLIFBASLIK_FISNO { get; set; }
        public Nullable<System.DateTime> SATISTEKLIFBASLIK_TARIH { get; set; }
        public string SATISTEKLIFBASLIK_GRUPKODU { get; set; }
        public string SATISTEKLIFBASLIK_OZELKOD1 { get; set; }
        public string SATISTEKLIFBASLIK_OZELKOD2 { get; set; }
        public string SATISTEKLIFBASLIK_TRANSCODE { get; set; }
        public string SATISTEKLIFBASLIK_PERSONELNO { get; set; }
        public string SATISTEKLIFBASLIK_PERSONELADI { get; set; }
        public string SATISTEKLIFBASLIK_PERSONELTIPI { get; set; }
        public Nullable<int> SATISTEKLIFBASLIK_PERSONELID { get; set; }
        public Nullable<bool> SATISTEKLIFBASLIK_ONAY { get; set; }
        public Nullable<bool> SATISTEKLIFBASLIK_APPROVE2 { get; set; }
        public Nullable<bool> SATISTEKLIFBASLIK_APPROVE3 { get; set; }
        public string SATISTEKLIFBASLIK_STATUSNAME { get; set; }
        public Nullable<short> SATISTEKLIFBASLIK_DURUM { get; set; }
        public Nullable<int> SATISTEKLIFBASLIK_NOTEID { get; set; }
        public Nullable<System.DateTime> SATISTEKLIFBASLIK_IPTALTARIHI { get; set; }
        public string SATISTEKLIFBASLIK_ACIKLAMA { get; set; }
        public string SATISTEKLIFBASLIK_DOKUMANNO { get; set; }
        public Nullable<decimal> SATISTEKLIFBASLIK_TUTAR { get; set; }
        public string SATISTEKLIFBASLIK_DOVIZ { get; set; }
        public Nullable<System.DateTime> SATISTEKLIFBASLIK_DOVIZTARIHI { get; set; }
        public Nullable<double> SATISTEKLIFBASLIK_DOVIZKUR { get; set; }
        public Nullable<double> SATISTEKLIFBASLIK_DOVIZTUTAR { get; set; }
        public string SATISTEKLIFBASLIK_HARDOVIZI { get; set; }
        public Nullable<System.DateTime> SATISTEKLIFBASLIK_HARDOVIZTARIHI { get; set; }
        public Nullable<double> SATISTEKLIFBASLIK_HARDOVIZKUR { get; set; }
        public Nullable<decimal> SATISTEKLIFBASLIK_DOVIZHAR { get; set; }
        public string SATISTEKLIFBASLIK_VERGIDAIRESI { get; set; }
        public string SATISTEKLIFBASLIK_VERGINO { get; set; }
        public string SATISTEKLIFBASLIK_VERGISEHRI { get; set; }
        public Nullable<System.DateTime> SATISTEKLIFBASLIK_VADE { get; set; }
        public Nullable<short> SATISTEKLIFBASLIK_GUNVADE { get; set; }
        public Nullable<System.DateTime> SATISTEKLIFBASLIK_OPSIYONVADE { get; set; }
        public Nullable<short> SATISTEKLIFBASLIK_KATEGORIID { get; set; }
        public string SATISTEKLIFBASLIK_ODEMETIPIADI { get; set; }
        public Nullable<short> SATISTEKLIFBASLIK_ODEMETIPI { get; set; }
        public Nullable<bool> SATISTEKLIFBASLIK_IHRACKAYITLI { get; set; }
        public Nullable<decimal> SATISTEKLIFBASLIK_INDIRIMTUTAR1 { get; set; }
        public Nullable<decimal> SATISTEKLIFBASLIK_INDIRIMO1 { get; set; }
        public Nullable<decimal> SATISTEKLIFBASLIK_INDIRIMTUTAR2 { get; set; }
        public Nullable<decimal> SATISTEKLIFBASLIK_INDIRIMO2 { get; set; }
        public Nullable<decimal> SATISTEKLIFBASLIK_URUNTOPLAMI { get; set; }
        public Nullable<decimal> SATISTEKLIFBASLIK_TOPLAMINDIRIM { get; set; }
        public Nullable<decimal> SATISTEKLIFBASLIK_PRODUCTSUMOUTVAT { get; set; }
        public Nullable<decimal> SATISTEKLIFBASLIK_DISCOUNTSUMOUTVAT { get; set; }
        public Nullable<decimal> SATISTEKLIFBASLIK_BREAKTOTALOUTVAT { get; set; }
        public Nullable<decimal> SATISTEKLIFBASLIK_KDVTOPLAM { get; set; }
        public Nullable<decimal> SATISTEKLIFBASLIK_OTVTOPLAM { get; set; }
        public Nullable<decimal> SATISTEKLIFBASLIK_TEVKIFATVERGITOPLAMI { get; set; }
        public Nullable<bool> SATISTEKLIFBASLIK_MUHASEBEKONTROL { get; set; }
        public Nullable<double> SATISTEKLIFBASLIK_MALIYETFIYAT { get; set; }
        public Nullable<System.DateTime> SATISTEKLIFBASLIK_KDVVADE { get; set; }
        public Nullable<decimal> SATISTEKLIFBASLIK_YUVARLAMATUTARI { get; set; }
        public Nullable<decimal> SATISTEKLIFBASLIK_TEVKIFATCARPANI { get; set; }
        public Nullable<decimal> SATISTEKLIFBASLIK_TEVKIFATBOLENI { get; set; }
        public Nullable<decimal> SATISTEKLIFBASLIK_STOPAJRATE { get; set; }
        public Nullable<decimal> SATISTEKLIFBASLIK_STOPAJ { get; set; }
        public string SATISTEKLIFBASLIK_KASANO { get; set; }
        public string SATISTEKLIFBASLIK_KASAADI { get; set; }
        public string SATISTEKLIFBASLIK_KASATIPI { get; set; }
        public Nullable<int> SATISTEKLIFBASLIK_KASAID { get; set; }
        public string SATISTEKLIFBASLIK_DEPONO { get; set; }
        public string SATISTEKLIFBASLIK_DEPOADI { get; set; }
        public string SATISTEKLIFBASLIK_DEPOTIPI { get; set; }
        public Nullable<int> SATISTEKLIFBASLIK_DEPOREF { get; set; }
        public string SATISTEKLIFBASLIK_CARINO { get; set; }
        public string SATISTEKLIFBASLIK_CARIADI { get; set; }
        public string SATISTEKLIFBASLIK_CARITIPI { get; set; }
        public Nullable<int> SATISTEKLIFBASLIK_CARIID { get; set; }
        public string SATISTEKLIFBASLIK_BANKANO { get; set; }
        public string SATISTEKLIFBASLIK_BANKAADI { get; set; }
        public string SATISTEKLIFBASLIK_BANKATIPI { get; set; }
        public Nullable<int> SATISTEKLIFBASLIK_BANKAID { get; set; }
        public Nullable<decimal> SATISTEKLIFBASLIK_BANKTOTAL { get; set; }
        public string SATISTEKLIFBASLIK_ADI1 { get; set; }
        public string SATISTEKLIFBASLIK_ADI2 { get; set; }
        public Nullable<int> SATISTEKLIFBASLIK_ADRESID { get; set; }
        public Nullable<System.DateTime> SATISTEKLIFBASLIK_VALIDDATE { get; set; }
        public Nullable<System.DateTime> SATISTEKLIFBASLIK_SEVKTARIHI { get; set; }
        public Nullable<int> SATISTEKLIFBASLIK_SEVKCARIID { get; set; }
        public string SATISTEKLIFBASLIK_SEVKADI { get; set; }
        public string SATISTEKLIFBASLIK_SEVKADI2 { get; set; }
        public Nullable<int> SATISTEKLIFBASLIK_SEVKADRESI { get; set; }
        public string SATISTEKLIFBASLIK_ACIKLAMA1 { get; set; }
        public string SATISTEKLIFBASLIK_ACIKLAMA2 { get; set; }
        public string SATISTEKLIFBASLIK_PROJENO { get; set; }
        public string SATISTEKLIFBASLIK_PROJEADI { get; set; }
        public Nullable<int> SATISTEKLIFBASLIK_PROJEID { get; set; }
        public string SATISTEKLIFBASLIK_MASRAFYERKODU { get; set; }
        public string SATISTEKLIFBASLIK_MASRAFYERADI { get; set; }
        public Nullable<int> SATISTEKLIFBASLIK_MASRAFYERREF { get; set; }
        public string SATISTEKLIFBASLIK_DOVIZHARTIPIADI { get; set; }
        public Nullable<bool> SATISTEKLIFBASLIK_DOVIZHARTIPI { get; set; }
        public string SATISTEKLIFBASLIK_RECEIPTTYPENAME { get; set; }
        public Nullable<int> SATISTEKLIFBASLIK_RECEIPTTYPE { get; set; }
        public Nullable<int> SATISTEKLIFBASLIK_SID { get; set; }
        public string SATISTEKLIFBASLIK_PAKETADI { get; set; }
        public Nullable<int> SATISTEKLIFBASLIK_STOKPAKETID { get; set; }
        public Nullable<short> SATISTEKLIFBASLIK_PARTCOUNT { get; set; }
        public Nullable<short> SATISTEKLIFBASLIK_GLBPAYMENTID { get; set; }
        public Nullable<int> SATISTEKLIFBASLIK_ACCRECEIPTID { get; set; }
        public Nullable<bool> SATISTEKLIFBASLIK_MANUELVAT { get; set; }
        public Nullable<double> SATISTEKLIFBASLIK_PARTYSIZE { get; set; }
        public Nullable<int> SATISTEKLIFBASLIK_STKFIYATTIPID { get; set; }
        public Nullable<int> SATISTEKLIFBASLIK_CRMINTERVIEWID { get; set; }
        public string SATISTEKLIFBASLIK_CRMCONTACTSFULLNAME { get; set; }
        public Nullable<int> SATISTEKLIFBASLIK_CRMCONTACTSID { get; set; }
        public string SATISTEKLIFBASLIK_BUDGETNO { get; set; }
        public string SATISTEKLIFBASLIK_BUDGETNAME { get; set; }
        public string SATISTEKLIFBASLIK_BUDGETTYPE { get; set; }
        public Nullable<int> SATISTEKLIFBASLIK_BUDGETID { get; set; }
        public Nullable<double> SATISTEKLIFBASLIK_BREAKTOTAL { get; set; }
        public Nullable<bool> SATISTEKLIFBASLIK_SENDDOC { get; set; }
        public Nullable<decimal> SATISTEKLIFBASLIK_CURRDISCOUNTTOTAL1 { get; set; }
        public string SATISTEKLIFBASLIK_REJECTREASON { get; set; }
        public string SATISTEKLIFBASLIK_CHECKMD5SUM { get; set; }
        public Nullable<int> SATISTEKLIFBASLIK_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> SATISTEKLIFBASLIK_KAYITTARIHI { get; set; }
        public Nullable<int> SATISTEKLIFBASLIK_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> SATISTEKLIFBASLIK_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> SATISTEKLIFBASLIK_UYARIID { get; set; }
    }
}
