//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_STOREHOUSETRANS
    {
        public int STOREHOUSETRANS_SIRKETID { get; set; }
        public int STOREHOUSETRANS_PARCANO { get; set; }
        public Nullable<int> STOREHOUSETRANS_STOREHOUSEID { get; set; }
        public Nullable<System.DateTime> STOREHOUSETRANS_TARIH { get; set; }
        public string STOREHOUSETRANS_STOKNO { get; set; }
        public string STOREHOUSETRANS_STOKADI { get; set; }
        public string STOREHOUSETRANS_STOKTIPI { get; set; }
        public int STOREHOUSETRANS_STOKID { get; set; }
        public string STOREHOUSETRANS_LOTNO { get; set; }
        public string STOREHOUSETRANS_KARSILOTNO { get; set; }
        public string STOREHOUSETRANS_BATCHNO { get; set; }
        public Nullable<int> STOREHOUSETRANS_STOKLOTID { get; set; }
        public short STOREHOUSETRANS_KAYNAK { get; set; }
        public int STOREHOUSETRANS_KAYNAKID { get; set; }
        public Nullable<short> STOREHOUSETRANS_TROOT { get; set; }
        public Nullable<int> STOREHOUSETRANS_TROOTID { get; set; }
        public string STOREHOUSETRANS_KAYNAKFISNO { get; set; }
        public Nullable<int> STOREHOUSETRANS_KAYNAKSIRA { get; set; }
        public string STOREHOUSETRANS_DEPONO { get; set; }
        public string STOREHOUSETRANS_DEPOADI { get; set; }
        public string STOREHOUSETRANS_DEPOTIPI { get; set; }
        public Nullable<int> STOREHOUSETRANS_DEPOREF { get; set; }
        public string STOREHOUSETRANS_NITELIKADI { get; set; }
        public Nullable<int> STOREHOUSETRANS_NITELIKID { get; set; }
        public Nullable<double> STOREHOUSETRANS_GIRISMIKTARI { get; set; }
        public Nullable<double> STOREHOUSETRANS_CIKISMIKTARI { get; set; }
        public Nullable<int> STOREHOUSETRANS_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> STOREHOUSETRANS_KAYITTARIHI { get; set; }
        public Nullable<int> STOREHOUSETRANS_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> STOREHOUSETRANS_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> STOREHOUSETRANS_UYARIID { get; set; }
    }
}
