//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_STOCKPACKAGE
    {
        public int STOCKPACKAGE_SIRKETID { get; set; }
        public int STOCKPACKAGE_STOKPAKETID { get; set; }
        public string STOCKPACKAGE_STOCKPACKAGETYPENAME { get; set; }
        public Nullable<int> STOCKPACKAGE_STOCKPACKAGETYPE { get; set; }
        public string STOCKPACKAGE_PAKETADI { get; set; }
        public Nullable<double> STOCKPACKAGE_GENISLIK { get; set; }
        public Nullable<double> STOCKPACKAGE_UZUNLUK { get; set; }
        public Nullable<double> STOCKPACKAGE_YUKSEKLIK { get; set; }
        public Nullable<double> STOCKPACKAGE_AGIRLIK { get; set; }
        public Nullable<double> STOCKPACKAGE_NETWEIGHT { get; set; }
        public Nullable<double> STOCKPACKAGE_CUBICMETER { get; set; }
        public Nullable<decimal> STOCKPACKAGE_TUTAR { get; set; }
        public Nullable<int> STOCKPACKAGE_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> STOCKPACKAGE_KAYITTARIHI { get; set; }
        public Nullable<int> STOCKPACKAGE_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> STOCKPACKAGE_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> STOCKPACKAGE_UYARIID { get; set; }
    }
}
