//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_STOCKPRICE
    {
        public int STOCKPRICE_SIRKETID { get; set; }
        public string STOCKPRICE_STOKNO { get; set; }
        public string STOCKPRICE_STOKADI { get; set; }
        public string STOCKPRICE_STOKTIPI { get; set; }
        public int STOCKPRICE_STOKID { get; set; }
        public string STOCKPRICE_NITELIKADI { get; set; }
        public int STOCKPRICE_NITELIKID { get; set; }
        public short STOCKPRICE_STKFIYATTIPID { get; set; }
        public string STOCKPRICE_DOVIZ { get; set; }
        public string STOCKPRICE_ACIKLAMA { get; set; }
        public Nullable<double> STOCKPRICE_FIYAT { get; set; }
        public Nullable<int> STOCKPRICE_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> STOCKPRICE_KAYITTARIHI { get; set; }
        public Nullable<int> STOCKPRICE_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> STOCKPRICE_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> STOCKPRICE_UYARIID { get; set; }
    }
}
