//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_SIPARISHAREKET
    {
        public int SIPARISHAREKET_SIRKETID { get; set; }
        public int SIPARISHAREKET_DONEMID { get; set; }
        public int SIPARISHAREKET_FISID { get; set; }
        public short SIPARISHAREKET_PARCANO { get; set; }
        public int SIPARISHAREKET_HARSIRANO { get; set; }
        public Nullable<short> SIPARISHAREKET_KAYNAK { get; set; }
        public Nullable<int> SIPARISHAREKET_KAYNAKID { get; set; }
        public string SIPARISHAREKET_KAYNAKFISNO { get; set; }
        public Nullable<int> SIPARISHAREKET_KAYNAKSIRA { get; set; }
        public Nullable<double> SIPARISHAREKET_MIKTAR { get; set; }
        public Nullable<double> SIPARISHAREKET_QUANTITY2 { get; set; }
        public Nullable<double> SIPARISHAREKET_QUANTITY3 { get; set; }
        public Nullable<double> SIPARISHAREKET_HARMIKTARI { get; set; }
        public Nullable<System.DateTime> SIPARISHAREKET_TARIH { get; set; }
        public Nullable<bool> SIPARISHAREKET_MANUELCLOSE { get; set; }
        public Nullable<int> SIPARISHAREKET_TOPROOT { get; set; }
        public Nullable<int> SIPARISHAREKET_TOPROOTID { get; set; }
        public Nullable<int> SIPARISHAREKET_TOPROOTITEMNO { get; set; }
    }
}
