//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_TPACKAGEPRO
    {
        public int TPACKAGEPRO_SIRKETID { get; set; }
        public int TPACKAGEPRO_DONEMID { get; set; }
        public int TPACKAGEPRO_TPACKAGEPROID { get; set; }
        public Nullable<System.DateTime> TPACKAGEPRO_TARIH { get; set; }
        public string TPACKAGEPRO_SEVKIYATPAKETTIPID { get; set; }
        public string TPACKAGEPRO_BPACKAGETYPEID { get; set; }
        public Nullable<int> TPACKAGEPRO_FISID { get; set; }
        public string TPACKAGEPRO_PERSONELNO { get; set; }
        public string TPACKAGEPRO_PERSONELTIPI { get; set; }
        public string TPACKAGEPRO_PERSONELADI { get; set; }
        public Nullable<int> TPACKAGEPRO_PERSONELID { get; set; }
        public string TPACKAGEPRO_OZELKOD1 { get; set; }
        public string TPACKAGEPRO_OZELKOD2 { get; set; }
    }
}
