//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_TDSTOCKITEMTRANSFER
    {
        public int TDSTOCKITEMTRANSFER_SIRKETID { get; set; }
        public int TDSTOCKITEMTRANSFER_DONEMID { get; set; }
        public int TDSTOCKITEMTRANSFER_FISID { get; set; }
        public short TDSTOCKITEMTRANSFER_PARCANO { get; set; }
        public string TDSTOCKITEMTRANSFER_INITEMTYPENAME { get; set; }
        public Nullable<short> TDSTOCKITEMTRANSFER_INITEMTYPE { get; set; }
        public string TDSTOCKITEMTRANSFER_OUTITEMTYPENAME { get; set; }
        public Nullable<short> TDSTOCKITEMTRANSFER_OUTITEMTYPE { get; set; }
        public string TDSTOCKITEMTRANSFER_STOKNO { get; set; }
        public string TDSTOCKITEMTRANSFER_STOKTIPI { get; set; }
        public string TDSTOCKITEMTRANSFER_STOKADI { get; set; }
        public Nullable<int> TDSTOCKITEMTRANSFER_STOKID { get; set; }
        public Nullable<int> TDSTOCKITEMTRANSFER_OUTSTOCKID { get; set; }
        public Nullable<short> TDSTOCKITEMTRANSFER_KAYNAK { get; set; }
        public Nullable<int> TDSTOCKITEMTRANSFER_KAYNAKID { get; set; }
        public string TDSTOCKITEMTRANSFER_ROOTITEMNO { get; set; }
        public Nullable<int> TDSTOCKITEMTRANSFER_DTEX { get; set; }
        public Nullable<int> TDSTOCKITEMTRANSFER_TELSAY { get; set; }
        public Nullable<int> TDSTOCKITEMTRANSFER_MT { get; set; }
        public Nullable<int> TDSTOCKITEMTRANSFER_NUMBER { get; set; }
        public string TDSTOCKITEMTRANSFER_ACIKLAMA { get; set; }
        public Nullable<double> TDSTOCKITEMTRANSFER_QTRANS { get; set; }
        public Nullable<decimal> TDSTOCKITEMTRANSFER_FIYAT { get; set; }
        public Nullable<decimal> TDSTOCKITEMTRANSFER_TUTAR { get; set; }
        public Nullable<double> TDSTOCKITEMTRANSFER_MIKTAR { get; set; }
        public Nullable<double> TDSTOCKITEMTRANSFER_BRUTQUANTITY { get; set; }
        public Nullable<double> TDSTOCKITEMTRANSFER_IRSQUANTITY { get; set; }
        public Nullable<double> TDSTOCKITEMTRANSFER_BDARAQ { get; set; }
        public Nullable<double> TDSTOCKITEMTRANSFER_KDARAQ { get; set; }
        public Nullable<int> TDSTOCKITEMTRANSFER_BNUMBER { get; set; }
        public Nullable<int> TDSTOCKITEMTRANSFER_KNUMBER { get; set; }
        public Nullable<double> TDSTOCKITEMTRANSFER_HARMIKTARI { get; set; }
        public Nullable<short> TDSTOCKITEMTRANSFER_BIRIMHAR { get; set; }
        public Nullable<int> TDSTOCKITEMTRANSFER_INDEPOTID { get; set; }
        public Nullable<int> TDSTOCKITEMTRANSFER_OUTDEPOTID { get; set; }
        public string TDSTOCKITEMTRANSFER_SLOTNO { get; set; }
        public string TDSTOCKITEMTRANSFER_LOTNO { get; set; }
        public Nullable<int> TDSTOCKITEMTRANSFER_PAKETMIKTAR { get; set; }
        public Nullable<int> TDSTOCKITEMTRANSFER_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> TDSTOCKITEMTRANSFER_KAYITTARIHI { get; set; }
    }
}
