//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_TDQUALITYTRANS
    {
        public int TDQUALITYTRANS_SIRKETID { get; set; }
        public int TDQUALITYTRANS_DONEMID { get; set; }
        public int TDQUALITYTRANS_PARCANO { get; set; }
        public int TDQUALITYTRANS_TOPID { get; set; }
        public Nullable<int> TDQUALITYTRANS_KAYNAK { get; set; }
        public Nullable<int> TDQUALITYTRANS_ROOTRECEIPTID { get; set; }
        public Nullable<int> TDQUALITYTRANS_ROOTRECEIPTITEM { get; set; }
        public string TDQUALITYTRANS_PROSES { get; set; }
        public Nullable<double> TDQUALITYTRANS_IRSMT { get; set; }
        public Nullable<double> TDQUALITYTRANS_IRSKG { get; set; }
        public string TDQUALITYTRANS_ACIKLAMA { get; set; }
        public Nullable<System.DateTime> TDQUALITYTRANS_DEGISTIRMETARIHI { get; set; }
    }
}
