//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_TDPROFINJ
    {
        public int TDPROFINJ_SIRKETID { get; set; }
        public int TDPROFINJ_DONEMID { get; set; }
        public int TDPROFINJ_FISID { get; set; }
        public Nullable<int> TDPROFINJ_YEARID { get; set; }
        public Nullable<int> TDPROFINJ_MONTHID { get; set; }
        public Nullable<double> TDPROFINJ_DOLLARRATE { get; set; }
        public Nullable<double> TDPROFINJ_EURORATE { get; set; }
        public Nullable<int> TDPROFINJ_WORKDAYS { get; set; }
        public Nullable<int> TDPROFINJ_WORKERSCNT { get; set; }
        public Nullable<double> TDPROFINJ_KARZARAR { get; set; }
    }
}
