//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_TDGLBDEF
    {
        public int TDGLBDEF_GRUPID { get; set; }
        public int TDGLBDEF_PARCANO { get; set; }
        public Nullable<double> TDGLBDEF_DEGER1 { get; set; }
        public Nullable<double> TDGLBDEF_DEGER2 { get; set; }
        public Nullable<double> TDGLBDEF_DEGER3 { get; set; }
        public Nullable<double> TDGLBDEF_DEGER4 { get; set; }
        public Nullable<double> TDGLBDEF_DEGER5 { get; set; }
        public Nullable<bool> TDGLBDEF_SYSTEMST { get; set; }
        public string TDGLBDEF_ACIKLAMA { get; set; }
        public string TDGLBDEF_ACIKLAMA2 { get; set; }
        public string TDGLBDEF_ACIKLAMA3 { get; set; }
        public string TDGLBDEF_DESCRIPTION4 { get; set; }
        public string TDGLBDEF_SQLALAN { get; set; }
    }
}
