//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_TPAKETLEMEBASLIK
    {
        public int TPAKETLEMEBASLIK_SIRKETID { get; set; }
        public int TPAKETLEMEBASLIK_DONEMID { get; set; }
        public int TPAKETLEMEBASLIK_TPACKAGEPROID { get; set; }
        public Nullable<System.DateTime> TPAKETLEMEBASLIK_TARIH { get; set; }
        public string TPAKETLEMEBASLIK_SEVKIYATPAKETTIPID { get; set; }
        public string TPAKETLEMEBASLIK_BPACKAGETYPEID { get; set; }
        public string TPAKETLEMEBASLIK_CARINO { get; set; }
        public string TPAKETLEMEBASLIK_CARIADI { get; set; }
        public string TPAKETLEMEBASLIK_CARITIPI { get; set; }
        public Nullable<int> TPAKETLEMEBASLIK_CARIID { get; set; }
        public string TPAKETLEMEBASLIK_PERSONELNO { get; set; }
        public string TPAKETLEMEBASLIK_PERSONELADI { get; set; }
        public string TPAKETLEMEBASLIK_PERSONELTIPI { get; set; }
        public Nullable<int> TPAKETLEMEBASLIK_PERSONELID { get; set; }
        public string TPAKETLEMEBASLIK_DEPONO { get; set; }
        public string TPAKETLEMEBASLIK_DEPOADI { get; set; }
        public string TPAKETLEMEBASLIK_DEPOTIPI { get; set; }
        public Nullable<int> TPAKETLEMEBASLIK_DEPOREF { get; set; }
        public string TPAKETLEMEBASLIK_OZELKOD1 { get; set; }
        public string TPAKETLEMEBASLIK_OZELKOD2 { get; set; }
        public string TPAKETLEMEBASLIK_STATUSNAME { get; set; }
        public Nullable<short> TPAKETLEMEBASLIK_DURUM { get; set; }
    }
}
