//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_TDELIVLIST2
    {
        public int TDELIVLIST2_SIRKETID { get; set; }
        public int TDELIVLIST2_DONEMID { get; set; }
        public int TDELIVLIST2_FISID { get; set; }
        public int TDELIVLIST2_TDELIVLIST2ID { get; set; }
        public Nullable<int> TDELIVLIST2_STOKID { get; set; }
        public Nullable<int> TDELIVLIST2_RENKID { get; set; }
        public string TDELIVLIST2_DOORNO { get; set; }
        public string TDELIVLIST2_LOTNO { get; set; }
        public Nullable<double> TDELIVLIST2_TOPLAMKG { get; set; }
        public Nullable<int> TDELIVLIST2_BOBINADET { get; set; }
        public Nullable<double> TDELIVLIST2_BOBINKG { get; set; }
        public Nullable<double> TDELIVLIST2_PAKETKG { get; set; }
        public Nullable<double> TDELIVLIST2_KAZANNO { get; set; }
        public Nullable<double> TDELIVLIST2_NETKG { get; set; }
        public string TDELIVLIST2_STOKNO { get; set; }
        public string TDELIVLIST2_STOKADI { get; set; }
        public Nullable<int> TDELIVLIST2_TPRODUCTID { get; set; }
    }
}
