//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_YAZARKASASATISKART
    {
        public int YAZARKASASATISKART_SIRKETID { get; set; }
        public int YAZARKASASATISKART_YAZARKASASATISID { get; set; }
        public int YAZARKASASATISKART_PARCANO { get; set; }
        public Nullable<int> YAZARKASASATISKART_KARTTUS { get; set; }
        public Nullable<double> YAZARKASASATISKART_KARTCEKILEN { get; set; }
        public Nullable<int> YAZARKASASATISKART_TAKSITNO { get; set; }
    }
}
