//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_YETKILER
    {
        public int YETKILER_SIRKETID { get; set; }
        public int YETKILER_KULLANICIID { get; set; }
        public int YETKILER_FORMID { get; set; }
        public int YETKILER_BUTONID { get; set; }
        public Nullable<bool> YETKILER_YETKI { get; set; }
        public Nullable<int> YETKILER_KAYITEDENPERSID { get; set; }
        public Nullable<System.DateTime> YETKILER_KAYITTARIHI { get; set; }
        public Nullable<int> YETKILER_DEGISTIRENKULID { get; set; }
        public Nullable<System.DateTime> YETKILER_DEGISTIRMETARIHI { get; set; }
        public Nullable<int> YETKILER_UYARIID { get; set; }
    }
}
