//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VU_AYGRUPLISATISLAR
    {
        public string YERI { get; set; }
        public int COMPANYID { get; set; }
        public string ACTNO { get; set; }
        public string ACTNAME { get; set; }
        public Nullable<int> YIL { get; set; }
        public string AY { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
    }
}
