//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VU_FINANSDURUM
    {
        public int COMPANYID { get; set; }
        public int TIP { get; set; }
        public string TIPADI { get; set; }
        public Nullable<int> KARTID { get; set; }
        public string KARTNO { get; set; }
        public string KARTADI { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<short> KAYNAK { get; set; }
        public Nullable<int> FISID { get; set; }
        public string FISNO { get; set; }
        public Nullable<int> FISSIRANO { get; set; }
        public string DOVIZ { get; set; }
        public Nullable<double> MIKTAR { get; set; }
        public Nullable<decimal> BORC { get; set; }
        public Nullable<decimal> ALACAK { get; set; }
        public Nullable<double> DOVIZBORC { get; set; }
        public Nullable<double> DOVIZALACAK { get; set; }
    }
}
