//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajApp.template (1).MaterialSkin-master.MaterialSkinExample.RDSPORTAL_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VU_IPBLOKELER
    {
        public int COMPANYID { get; set; }
        public string IpNo { get; set; }
        public string Yapi { get; set; }
        public string Cinsi { get; set; }
        public string Renk { get; set; }
        public string RKod { get; set; }
        public Nullable<int> Tur { get; set; }
        public Nullable<double> Bloke { get; set; }
        public int STOCKID { get; set; }
        public string SLNO { get; set; }
    }
}
